### ISSUE TITLE
Missing period at the end of the "Support hashtags symbols # in Auto Terms" sentence on the "Manage Auto Terms" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1004]
![WordPress_snapshot68](https://user-images.githubusercontent.com/87830117/137982134-f54860f9-4ba7-41ed-972e-8a0f1382356e.gif)

**Comment by stevejburge** [comment]
Looks like there are 2 of these:
<img width="588" alt="Screen Shot 2021-12-02 at 9 02 39 AM" src="https://user-images.githubusercontent.com/3868028/144436884-cf1575dc-6734-4c79-b99f-81a2f6cedbcf.png">
