### ISSUE TITLE
Ability to save data when the entered value contains a dot inside the value in the "Number of items per page" drop-down list box on "Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1013]
When inserting the value that contains a dot inside in the "Number of items per page" drop-down list box on "Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms --> Screen Options
Type in "1.00" in the "Number of items per page" drop-down list
Click "Apply" button
Note: the data updated successfully

![WordPress_snapshot80](https://user-images.githubusercontent.com/87830117/138480678-ffd05035-f539-4d66-920d-c5646d67a71a.gif)

**Comment by ojopaul** [comment]
This is not an issue as well. Wordpress is the one that handled screen option and when invalid data that's not an integer is entered, it update correct data stripping out the non integer. Can any of you confirm if the non integer exist after save as it doesn't here ? @stevejburge @olatechpro
