### ISSUE TITLE
Ability to save data when the entered value contains several spaces inside the value in the "Stop words" text field on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1017]
When inserting the value that contains several spaces inside the value in the "Stop words" text field on the "Manage Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms
Edit any Auto Term --> Terms to Use
Type in several spaces between words in the "Stop words" text field
Click "Save Auto Terms" button
Note: the message "Settings updated successfully" appears

![WordPress_snapshot83](https://user-images.githubusercontent.com/87830117/138900991-584c56ef-9223-412c-9552-d209b2974708.gif)

**Comment by ojopaul** [comment]
@stevejburge @olatechpro , this shoudn't be an issue as well as space is allowed in the text input and no validation that handle how many space in-between words or any suggestion ? @stevejburge @olatechpro
