### ISSUE TITLE
Ability to save data when the entered value contains several spaces inside the value in the "Choose terms to use" text field on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1018]
When inserting the value that contains several spaces inside the value in the "Choose terms to use" text field on the "Manage Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms
Edit any Auto Term --> Terms to Use
Type in several spaces between words in the "Choose terms to use" text field
Click "Save Auto Terms" button
Note: the message "Settings updated successfully" appears

![WordPress_snapshot84](https://user-images.githubusercontent.com/87830117/138907913-56fa4704-d679-4849-8365-3ae946b6d925.gif)

**Comment by ojopaul** [comment]
@stevejburge @olatechpro , just like other issue, this shoudn't be an issue as well since space is allowed in the text input and no validation that handle how many space in-between words ? @stevejburge @olatechpro
