### ISSUE TITLE
Ability to save data when the entered value starts with a space in "Choose terms to use" text field on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1019]
When inserting the value that starts with a space in the "Choose terms to use" text field on the "Manage Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms
Edit any Auto Terms --> Terms to Use
Type in several spaces in the "Choose terms to use" text field
Click "Save Auto Terms" button
Note: the message "Settings updated successfully" appears

![WordPress_snapshot85](https://user-images.githubusercontent.com/87830117/138909275-77280648-c007-4a97-a396-14c47460c65e.gif)

**Comment by ojopaul** [comment]
This shouldn't be an issue as well. User has total control and will on value entered on the field. @stevejburge @olatechpro
