### ISSUE TITLE
Uncaught Error: Class 'taxopress_admin_ui' not found

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1051]
Bug report that caused a fatal error for a customer

```
E_ERROR /public_html/wp-content/plugins/taxopress-pro/inc/autoterms.php. Κωδικός σφάλματος: Uncaught Error: Class 'taxopress_admin_ui' not found in /home/de435268/public_html/wp-content/plugins/taxopress-pro/inc/autoterms.php:226
Stack trace:
#0 /home/de435268/public_html/wp-content/plugins/taxopress-pro/inc/autoterms.php(174): SimpleTags_Autoterms->taxopress_manage_autoterms()
#1 /home/de435268/public_html/wp-includes/class-wp-hook.php(303): SimpleTags_Autoterms->page_manage_autoterms('')
#2 /home/de435268/public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#3 /home/de435268/public_html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#4 /home/de435268/public_html/wp-admin/admin.php(259): do_action('taxopress_page_...')
#5 {main}
```

**Comment by ojopaul** [comment]
@stevejburge , i came across reason for this error while working on something else, it's as a result of the table class been restricted to taxonomy. So, if taxonomy is disabled, all other pages that use the class will be throwing up error.

**Comment by stevejburge** [comment]
@ojopaul Thanks. Is there a way we can avoid this error, or show a better message?

**Comment by ojopaul** [comment]
> @ojopaul Thanks. Is there a way we can avoid this error, or show a better message?

Yes, the fix is simply making the table class available to all pages that uses it.

So, you can add the issue to current milestone and i'll fix it.

**Comment by stevejburge** [comment]
Awesome, thanks
