### ISSUE TITLE
The data is successfully saved with special characters in the "Dandelion API confidence value" text field on "TaxoPress: Options" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1066]
Despite the message "Choose a value between 0 and 1..." it's still possible to save a value that contains the special characters only.

TaxoPress -->Settings
Type in the special characters in the "Dandelion API confidence value" text field
Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot119](https://user-images.githubusercontent.com/87830117/142018381-201d5058-e413-4064-8e53-f6b702c85954.gif)

**Comment by ojopaul** [comment]
The "Dandelion API confidence value" input type is "text" and as a result, the validation type will accept both text, number and character and when i checked the administration settings, custom validation is not in place for them to determine such issue. How do you want me to handle issues like this ? @stevejburge

**Comment by ojopaul** [comment]
Seems some of the issues here are the same. So, will drop the comment here once and do follow up on others on what your decision is on them as text field type accepts texts, numbers and characters and that's the standard form way @stevejburge

**Comment by ojopaul** [comment]
To add custom validation, we'll need to change the way current form is implemented as it's implemented in such a way that an addition to a field will require a change to all. So, should we go ahead with that approach since many issues are similar to this and simply change the way of the form ? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Yes, there are a lot of these validation issues. They cover many settings fields.

Yes, please - if you have a good idea, I'm eager to hear it

**Comment by ojopaul** [comment]
The only option available is in my last message. Current form is implemented in such a way that i doesn't have custom validation for scope out of normal validation. If we need custom validation outside normal form scope, we need to change the way it's implemented so there'll be room for custom validation. @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Thanks. Can we do this in a way that is safe for customer data?

**Comment by ojopaul** [comment]
Yes, and nothing will change in terms of visuals as well. @stevejburge

**Comment by stevejburge** [comment]
Great, thanks

Yes, our tester found more than a few of these

**Comment by ojopaul** [comment]
This field is no longer existing
