### ISSUE TITLE
The data is successfully saved with emoji in the "Dandelion API confidence value" text field on "TaxoPress: Options" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1068]
Despite the message "Choose a value between 0 and 1..." it's still possible to save a value that contains the emoji only.

TaxoPress -->Settings
Type in the emoji in the "Dandelion API confidence value" text field
Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot122](https://user-images.githubusercontent.com/87830117/142228056-ec3c28fe-c060-4b23-a0f9-80b3b494d2f8.gif)

**Comment by ojopaul** [comment]
This field is no longer existing
