### ISSUE TITLE
Ability to save data when the entered value starts with a space in the "OpenCalais API Key" text field on the "TaxoPress: Options" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1073]
When inserting the value that starts with a space in the "OpenCalais API Key" text field on the "TaxoPress: Options" page. the data is successfully saved.

1. TaxoPress -->Settings
2. Type in several spaces before the value in the "OpenCalais API Key" text field
3. Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot126](https://user-images.githubusercontent.com/87830117/142445948-b84cc65a-c123-4441-91b4-56986e225155.gif)

**Comment by ojopaul** [comment]
No longer existing
