### ISSUE TITLE
Ability to save data when the entered value starts with a space in the "Dandelion API token" text field on the "TaxoPress: Options" page. 

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1074]
When inserting the value that starts with a space in the "Dandelion API token" text field on the "TaxoPress: Options" page. the data is successfully saved.

TaxoPress -->Settings
Type in several spaces before the value in the "Dandelion API token" text field
Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot127](https://user-images.githubusercontent.com/87830117/142446495-01df0f4d-5f94-4fba-b0cd-5fd7ea5c71e8.gif)

**Comment by ojopaul** [comment]
No longer existing
