### ISSUE TITLE
Ability to save data when the entered value contains several spaces inside the value in the "Dandelion API token" text field on "Manage Taxonomy" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1079]
When inserting the value that contains several spaces inside the value in the "Dandelion API token" text field on the "TaxoPress: Options" page, the data is successfully saved.

1. TaxoPress -->Settings
2. Type in several spaces between words in the "Dandelion API token" text field
3. Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot128](https://user-images.githubusercontent.com/87830117/142645134-a16ba59f-4e05-4854-b166-296396fa17d7.gif)

**Comment by ojopaul** [comment]
No longer existing
