### ISSUE TITLE
Ability to save data when the entered value contains several spaces inside the value in the "OpenCalais API Key" text field on "Manage Taxonomy" page.

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#1080]
When inserting the value that contains several spaces inside the value in the "OpenCalais API Key" text field on the "TaxoPress: Options" page, the data is successfully saved.

1. TaxoPress -->Settings
2. Type in several spaces between words in the "OpenCalais API Key" text field
3. Click "Update options" button
Note: the options saved successfully

![WordPress_snapshot129](https://user-images.githubusercontent.com/87830117/142645613-db49c1af-9a32-4875-9a7c-0b7d311e6330.gif)

**Comment by ojopaul** [comment]
No longer existing
