### ISSUE TITLE
Check compatability of all 3 widgets with WordPress 5.9

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1119]
We have 3 widgets. The "Legacy" option can be ignored.

Let's check them with WordPress 5.9
<img width="348" alt="Screen Shot 2021-12-02 at 9 45 09 AM" src="https://user-images.githubusercontent.com/3868028/144444358-b5e917d2-92e7-44b8-8f7b-cdbdb76e8d3a.png">

In my initial testing, I could only get one to appear when writing posts:

<img width="826" alt="Screen Shot 2021-12-02 at 9 46 57 AM" src="https://user-images.githubusercontent.com/3868028/144444718-73d227d4-81db-4bda-8cc0-35ad0cfa891b.png">

The same is true with full-site editing:

<img width="733" alt="Screen Shot 2021-12-02 at 9 48 13 AM" src="https://user-images.githubusercontent.com/3868028/144444954-e0ad6729-76e0-4ae5-9106-b852de04fbeb.png">

**Comment by stevejburge** [comment]
Confirmed ... some of our widgets definitely are not available on the "Full Site Editing" screen
<img width="371" alt="Screen Shot 2022-03-09 at 8 26 27 AM" src="https://user-images.githubusercontent.com/3868028/157451100-1ce50f18-562a-48e6-9812-20d2a8a0b404.png">
<img width="376" alt="Screen Shot 2022-03-09 at 8 27 52 AM" src="https://user-images.githubusercontent.com/3868028/157451103-d6a09687-9651-41f3-a2a1-be99f1800b46.png">

**Comment by ojopaul** [comment]
@stevejburge this is not a problem from our end, i checked this and the TaxoPress Related Post that was available in that screen is not a widget but block.

So, widgets are generally not available for such theme(either TaxoPress or not) and if you notice, widget sub menu is also removed in admin menu which shows the themes doesn't support widget.

So, unless we want to create blocks for every of our widgets.


Also, while checking this [opened issue](https://github.com/TaxoPress/TaxoPress/issues/667), i saw this proposal made by @olatechpro and i think you should revisit it and probably update the request to gutenberg blocks for our widgets https://github.com/TaxoPress/TaxoPress/issues/667

**Comment by stevejburge** [comment]
Good points, thanks @ojopaul. I've reopened the other issue
