### ISSUE TITLE
Remove some words before automatically add terms

### ISSUE THREAD

**Issue by BFRjinhoff** [TaxoPress/TaxoPress#112]
Hello, 

in our case it would be really great if it where possible to exclude some words before the auto term functions searches trough the post to add the terms.

This would improve the overall quality of the Content because we could use filler words to make the content more readable.

Now to the questions.

- Do you plan to implement such an feature?
- If you dont want to implement this by yourself, do you mind if we contribute this to your plugin?
  - If so, is it possible that you support us on the integration of this feature? When we have questions?

Best regards

**Comment by herewithme** [comment]
Kind of "stop words"?
You can propose a patch on Github, I will merge it without problem.

**Comment by BFRjinhoff** [comment]
Yes, kind of. It serves a similar purpose like stop words.

What is your evaluation to implement this into the regex "_replace_by_links" function?
Specialy if the words should be definable at the backend.

**Comment by olatechpro** [comment]
Fixed in previous release
