### ISSUE TITLE
Change "Terms to Use" to Sources

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1122]
Let's change "Terms to Use" to "Sources"

<img width="898" alt="Screen Shot 2021-12-07 at 3 46 55 PM" src="https://user-images.githubusercontent.com/3868028/145103876-c235ebd8-c0cc-4d31-9d4d-0f76769ac780.png">

Then inside the tab there should be 3 settings:

Title: Existing taxonomy terms
Description: This will add existing terms from the taxonomy selected in the "General" tab.

Title: Dandelion API
Description: This will automatically add new terms from the Dandelion API service. Please test carefully before use.

Title: Open Calais
Description: This will automatically add new terms from the Open Calais service. Please test carefully before use.

**Comment by ojopaul** [comment]
Are we eliminating **"Use only some terms in the selected taxonomy"** option since you said 3 settings ? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Sorry, no. Both "Use only some terms in the selected taxonomy" and "Use all the terms in the selected taxonomy." will be options after you select "Existing taxonomy terms"

**Comment by ojopaul** [comment]
Then, we're having:
**Title**: Existing taxonomy terms
**Checkbox 1**:  This will add existing terms from the taxonomy selected in the "General" tab
**Checkbox 2**: Use only some terms in the selected taxonomy. @stevejburge ?

**Title**: Dandelion API
**Checkbox**: This will automatically add new terms from the Dandelion API service. Please test carefully before use.

**Title**: Open Calais
**Checkbox**: This will automatically add new terms from the Open Calais service. Please test carefully before use.

**Comment by ojopaul** [comment]
Then, we're having:
**Title**: Existing taxonomy terms
**Checkbox 1**:  This will add existing terms from the taxonomy selected in the "General" tab
**Checkbox 2**: Use only some terms in the selected taxonomy. @stevejburge ?

**Title**: Dandelion API
**Checkbox**: This will automatically add new terms from the Dandelion API service. Please test carefully before use.

**Title**: Open Calais
**Checkbox**: This will automatically add new terms from the Open Calais service. Please test carefully before use.

**Comment by ojopaul** [comment]
I'm trying to make clarification to be sure it's this structure as in all pages and not you having something else on mind since you use the term description and also some options coming after Existing taxonomy terms is selected. Want to be sure it's same as other forms field.
![pat](https://user-images.githubusercontent.com/92122385/145209674-479c4e15-d26c-4226-a429-05b0c863e805.jpg)

**Comment by stevejburge** [comment]
@ojopaul Ah, good point

Will these other settings also apply to Dandelion and Open Calais? I am thinking "no" ... is that correct?

**Comment by ojopaul** [comment]
I don't think you understand me. This is what you requested for right ?

The label updated like screenshot below and first checkbox label replaced from `"This will add existing terms from the taxonomy selected in the "General"` tab. to the new one as in the screenshot  ? @stevejburge 

![sources](https://user-images.githubusercontent.com/92122385/145213018-d7aca273-0809-4b33-b2a4-6e0aeda8a302.jpg)

**Comment by stevejburge** [comment]
@ojopaul Got it, thanks

So this looks correct, only if you select "Existing taxonomy terms", you will get two choices underneath:

- "Use only some terms in the selected taxonomy"
- "Use all the terms in the selected taxonomy."

**Comment by ojopaul** [comment]
That's where i'm getting confused, "Existing taxonomy terms" is just a label and not selecteable.

The "Existing taxonomy terms" has two options in it and it's those option that are selecteable which are:
"Use only some terms in the selected taxonomy"
"Use all the terms in the selected taxonomy."

or what you mean is, user can only select only one of:
- Existing taxonomy terms
- Dandelion
- Open Calais  ?
which shows they can't have "Dandelion" and "Open Calais" together like from where we copied it from ?

![source-2](https://user-images.githubusercontent.com/92122385/145214843-b770bc96-f4ff-48c6-8348-c4ddc7b4ec39.jpg)

**Comment by ojopaul** [comment]
Also, where does **"This will add existing terms from the taxonomy selected in the "General" tab"** goes in the above screenshot, under the label  ?

**Comment by ojopaul** [comment]
ok
