### ISSUE TITLE
Where to get Alchemy and Zemanta API Keys

### ISSUE THREAD

**Issue by dogday158** [TaxoPress/taxopress#115]
http://www.alchemyapi.com hasn't been accessible for months. Is there an alternative place to get an AAlchemy API key?

Also having problems finding a Zemanta API Key. Any suggestions on how to go about this as well?

Many thanks!

**Comment by dcweeks** [comment]
It is now part of IBM Cloud under "Natural Language Understanding" but I am sure the API interface in SimpleTags must be updated to get it to work.

**Comment by stevejburge** [comment]
Thanks @dogday158 @dcweeks 

We've removed Zemanta as that service is finished, but IBM Cloud is a possibility. Follow this ticket: https://github.com/TaxoPress/taxopress/issues/252
