### ISSUE TITLE
Include small promo to "Sources" tab

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1156]
Let's include a small promo for Dandelion / OpenCalais in here:

![Screen Shot 2022-01-06 at 10 52 45 AM](https://user-images.githubusercontent.com/3868028/148410951-7880db48-4985-4cb6-ab52-eb170e8f6a7d.png)

"Automatically add new terms to your content"
"TaxoPress Pro allows you to generate new terms for your content using the Dandelion and Open Calais services. These services can analyze your content and add new terms."

- It can be similar to the promo under "Schedule". 
- Maybe we add a small colored box for these promos?

<img width="910" alt="Screen Shot 2022-01-06 at 10 53 19 AM" src="https://user-images.githubusercontent.com/3868028/148410986-edeade00-53d4-455b-b233-62072afd464b.png">

**Comment by stevejburge** [comment]
@ojopaul We seem to have lost the promo on the "Sources" tab. Can we add that back?

**Comment by ojopaul** [comment]
That's strange, the border is still there in my testing. Will check why it's not showing for you
![banner](https://user-images.githubusercontent.com/92122385/151057425-947c5beb-f2f6-4cdb-a184-80c9a5612c2a.jpg)

**Comment by ojopaul** [comment]
Closing in favour of #1199
