### ISSUE TITLE
Make it clearer which options apply to which sources

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1157]
We have three options in Auto Terms:
- Existing taxonomy terms
- Dandelion
- Open Calaias

![Screen Shot 2022-01-06 at 2 44 59 PM](https://user-images.githubusercontent.com/3868028/148441984-73622faf-e410-40a5-8528-a2ba946c782d.png)

However, the other features don't apply consistently (Options, Existing Content, Schedule) to all 3

For example:
- Dandelion and Open Calais only work when content is published
- "Existing Content" does not work for Dandelion and Open Calais

I think we should
- Make sure "Existing Content" and "Schedule" do work for Dandelion and Open Calais
- If any options apply to only one source, move them to the "Sources" tab

**Comment by ojopaul** [comment]
@stevejburge, i just checked now and i can confirm there's no reason for 'schedule' or 'auto term existing content' not to work with Dandelion or Open Calais.

In source tab, there's a message that request new settings changes to be saved as we use saved data for auto terms and maybe you fail to save the data before using the settings ?

**Comment by stevejburge** [comment]
@ojopaul Agree. Can we add support for Dandelion or Open Calais?

In my testing on several sites, I can't get 'schedule' or 'auto term existing content' to work with Dandelion

**Comment by ojopaul** [comment]
@stevejburge  I just tested again right now and it works.
I created an auto terms, select 'Dandelion' as source option, entered Dandelion token and save.

After settings is saved, i clicked on Add auto terms to existing content and all posts were auto termed.

Can you confirm the post on your testing has content that could return result from the source ?

I really don't know how to debug this as same function that's responsible for auto term when post are created/updated is the same that apply for all other channel.

**Comment by ojopaul** [comment]
I'll suggest you try to create new post with auto term enabled to confirm if nothing is wrong with your configuration since it's same function

**Comment by stevejburge** [comment]
OK, thanks @ojopaul. I'll do some more debugging. It may be the size of the site ... it's working OK on my small test site, but not the large one. Dandelion and Open Calais may have problems if they need to process terms for many posts.
