### ISSUE TITLE
Disabling "Suggest existing terms on your site" causes trouble with other metabox

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1174]
If you disable the "Suggest existing terms on your site" box
![Screen Shot 2022-01-12 at 11 14 50 AM](https://user-images.githubusercontent.com/3868028/149178530-09b7906b-76df-467c-8d8e-1edfd6f5b4e4.png)

This happens with no terms showing:
![Screen Shot 2022-01-12 at 11 15 49 AM](https://user-images.githubusercontent.com/3868028/149178746-4f5eb857-f67e-4c1b-94cc-1dc4d767b333.png)

**Comment by ojopaul** [comment]
The metaboxes uses the suggest terms settings configuration to show metabox content. So, i'll update the code not to show metabox if it's disabled

**Comment by stevejburge** [comment]
@ojopaul Thanks. Yes, that's the correct approach
