### ISSUE TITLE
Stop the update of all old posts in archive

### ISSUE THREAD

**Issue by danielwebster-pongo** [TaxoPress/TaxoPress#1183]
I need to turn off/shut down and old mistake of asking TaxoPress Pro to update all old posts in archives. There should be some sort of a "STOP" button in that function. Every time TaxoPress is activated now, in the background the old post update, slams me with 429 errors until my site shuts down. I've tried reinstalling TaxoPress Pro and using new key codes. I am no longer able to have TaxoPress activated for more than mere seconds to minutes before my site is shut down. I've never used GitHub before. I'm not sure of the process here. Let me know what I need to provide to help with this issue. Thank You. Daniel

**Comment by danielwebster-pongo** [comment]
My note to WordPress Tech Support:

I sent your note to Steve at TaxoPress. I reinstalled the plugin from the link he gave me. My site was hit within 30 seconds. Can you see what shut it down this time and deactivate TaxoPress Pro for me so my site comes back?

Thank you
Daniel Webster

TaxoPress responded:
Hi Daniel

For some reason, that version of the plugin is installed at /TaxoPress-Pro-3.4.1/ which definitely isn't correct

I'd recommend removing that and trying again with this:
https://app.box.com/s/bswby3k5dx7yimdcgkhqsnef1syif1cs

**Comment by danielwebster-pongo** [comment]
Here is the response from WordPress tech support:

Shane T. (Automattic)

Jan 14, 2022, 19:00 UTC

Hi there,

I sent your note to Steve at TaxoPress. I reinstalled the plugin from the link he gave me. My site was hit within 30 seconds. Can you see what shut it down this time and deactivate TaxoPress Pro for me so my site comes back?

I tried reactivating the plugin and the same happened for me, it still breaks. Unfortunately, this time I'm not getting a specific PHP error related to the TaxoPress plugin, I'm just getting some other general WordPress errors. I'll share them with you, but the issue is still the plugin as the errors I'm about to send you exist even when the plugin is deactivated:

[14-Jan-2022 18:58:50 UTC] PHP Notice:  Trying to get property 'display_name' of non-object in /srv/htdocs/wp-content/themes/kadence/inc/components/breadcrumbs/component.php on line 655
[14-Jan-2022 18:58:52 UTC] PHP Notice:  Trying to access array offset on value of type bool in /wordpress/drop-ins/advanced-cache.php on line 495
I hope this helps! If you have any other questions we can help you with, please don't hesitate to ask. We're here to help!

**Comment by danielwebster-pongo** [comment]
Nic (Automattic)
Jan 16, 2022, 10:06 UTC

Hi Daniel,

I just wanted to reach out about the issue you've been having with the TaxoPress plugin.

I can see we responded on Friday after deactivating the plugin but I think the answer we gave might be a bit confusing so I wanted to clarify.

It looks like when the new version of the plugin was installed, the license error that we were seeing previously was no longer present. Additionally, it looks like that new version did not cause any other errors or warnings to indicate what might be going wrong. The notice that was previously mentioned appears to be unrelated to the plugin issue and can be ignored for now.

As to what specifically is triggering this overload when the plugin is on is difficult to say. I can share that we are seeing a lot of the failed requests going to sharing links. It's possible that one of your other automation plugins is conflicting with TaxoPress in this case. This can be tested if you'd like by disabling your other plugins and enabling TaxoPress. If the errors occur with just TaxoPress enabled then you know that plugin is the sole cause. Otherwise, you can one by one enable the plugins and see if the errors start after a specific one is activated.

Cheers,
Nic

Happiness Engineer @ Automattic

**Comment by ojopaul** [comment]
@danielwebster-pongo @stevejburge  is this issue refering to auto term schedule ?

**Comment by stevejburge** [comment]
@ojopaul Yes, but I'm not sure what process is being referred to here.

This is an issue with one site hosted on WordPress.com that we've been trying to track down for months. Neither us nor the WordPress.com team have been able to see what's causing this.

@danielwebster-pongo please try disabling TaxoPress features in TaxoPress' "Settings" area

**Comment by ojopaul** [comment]
Maybe we should add allow adding a specific parameter to settings page to reset/disable schedule auto terms or what approach do you want us to take on this issue ? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul I think we can do that with the TaxoPress' "Settings" area

Let's wait for @danielwebster-pongo feedback

**Comment by danielwebster-pongo** [comment]
I will try. The site shuts down within seconds to a minute from my
activating TaxoPress. The problem began when I started the process of
TaxoPress updating all previous posts on the site (approximately 50,000 at
the time). I've never been able to turn off that process.

**Comment by ojopaul** [comment]
@danielwebster-pongo which TaxoPress screen are you refering to ? Like, where did you enable this function to update previous posts ?

**Comment by danielwebster-pongo** [comment]
ADD AUTO TERMS TO EXISTING CONTENT

TaxoPress can add Auto Terms to existing content. This allows you to
automatically add terms to content that may not have any current terms.

   - Go to TaxoPress > Auto Terms.
   - Either edit an existing setup or create a new Auto Terms setup.
   - Choose the options you need and click “Save Auto Terms”.
   - Click “Add Auto Terms to all existing content”.


   -

**Comment by ojopaul** [comment]
That's strange @danielwebster-pongo as "Add Auto Terms to all existing content" doesn't run in background. In short, closing the tab will immediately terminate the process not to talk of it still causing issue after deactivating and reactivating the plugin.

**Comment by ojopaul** [comment]
@olatechpro can you check this out incase i'm missing something ?

**Comment by stevejburge** [comment]
@ojopaul That's correct. There's no background process.

Let's allow @danielwebster-pongo to try the TaxoPress' "Settings" area

**Comment by danielwebster-pongo** [comment]
I'm sorry I don't know the intricate details of your programming. It was
this function that is causing the problem. We first cured the problem with
a new key. The problem stopped. I thought maybe I could try it again. The
problem started again after I started that process again. Since that time
several thousand posts were accidentally deleted. When I switched to a
different server, it became disastrous, because the process of TaxoPress
Pro was affecting all the other sites on the server.

**Comment by danielwebster-pongo** [comment]
I have turned off (unchecked) ALL boxes in the TaxoPress Pro Settings
Features section. No error showing up so far.

**Comment by danielwebster-pongo** [comment]
I turned each box back on (checked box) in the Settings Features
individually and checked if it tripped an error.

RELATED POSTS box is the one to trip the 429 error. The plugin seems to be
stable otherwise. I will try using it without Related Posts -- I don't need
that feature, as have it from different plugin -- and see if I have a
problem.

**Comment by danielwebster-pongo** [comment]
Bless you. Thank you. I've never been so happy to see categories added to
my posts. YES! Very cool. My beloved TaxoPress is back. Ya know, your
plugin is crucial to everything else I want my site to do. Back to work . .
. Thank you, again.

**Comment by stevejburge** [comment]
That's great to hear, thanks @danielwebster-pongo
