### ISSUE TITLE
TaxoPress doesn’t add new terms into the “Product tags” area.

### ISSUE THREAD

**Issue by annabogovalova** [TaxoPress/TaxoPress#1192]
**Full description:**
Expected result:
When I create a new product in WooCommerce product, TaxoPress adds new terms into the “Product tags” area.
**Actual Result:**
When I create a new product in WooCommerce product, TaxoPress doesn’t add new terms into the “Product tags” area.
Step to reproduce:
1.	Instal and activate WooCommerce plugin
2.	In WordPress admin menu go to Products – click Tags – create new Product tags “coin” – click “Add new tag”
3.	In WordPress admin menu go to Products – click “Add new” – add a new product with Product name “Coin T-shirt” and Product Short Description as “Coin T-shirt”.
4.	TaxoPress didn’t add a new term into the “Product tags” area.
5.	Click “Publish” – click “Preview”
6.	Tag “Coin” didn’t show up on the product page.

OS: Windows 10
Browser: Google Chrome 
WordPress v.5.8.2
TaxoPress build# 3.4.3
![image](https://user-images.githubusercontent.com/86177962/150201177-cd8ba10f-62fe-4db7-98c9-e94a726aa9b8.png)
![image](https://user-images.githubusercontent.com/86177962/150201194-f3f79005-eff9-4180-a7ac-aade98782fde.png)
![image](https://user-images.githubusercontent.com/86177962/150201213-e5ab13a7-426c-4764-9a02-db5e9a44af90.png)

**Comment by stevejburge** [comment]
@annabogovalova Thanks. What "Sources" are you using for "Auto Terms"?

**Comment by annabogovalova** [comment]
Hi Steve,
My bad. I started posting this issue but when I was doing the description I figured out why tags didn't show up. I thought I cancelled this issue but it showed up.
Please close and ignore it.
Anna
