### ISSUE TITLE
New designs for Tag Cloud

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1193]
Currently our "Cloud" option in "Terms Display" is very plain:

![Screenshot 2024-09-02 at 9 48 02 AM](https://github.com/user-attachments/assets/c2accc0a-a656-4eb6-abc1-ed10970b2b7d)

Let's offer an updated design called "Border Cloud"

https://wptavern.com/gutenberg-12-4-includes-accessibility-improvements-categories-reminder-and-a-tag-cloud-outline-style

<img width="1284" alt="Screen Shot 2022-01-20 at 4 14 04 PM" src="https://user-images.githubusercontent.com/3868028/150423122-8945a738-3a34-46c2-9703-d84fc7a362be.png">

**Comment by ojopaul** [comment]
@stevejburge which of the TaxoPress screen is this refering to and also, per the attached screenshot are link, are you asking to update the design to match the above style in editor area or frontend area or both ?

**Comment by stevejburge** [comment]
One more request here, very similar to the first:
![Wish for Display Tags](https://user-images.githubusercontent.com/3868028/161430493-f5376c87-0f5d-45d1-8aea-3cd45e38b533.png)

**Comment by stevejburge** [comment]
To be specific, let's try to mimic the "Outline" option in the "Tag Cloud" block
![Screenshot 2024-09-03 at 7 34 34 AM](https://github.com/user-attachments/assets/38a09682-65fd-4862-b642-a81853e9fd4b)
