### ISSUE TITLE
Can we create a consistent style for Pro boxes

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1199]
@htmgarcia Any ideas on how we create a consistent "Pro" look for these promos?

![Screen Shot 2022-01-25 at 4 07 58 PM](https://user-images.githubusercontent.com/3868028/151060293-6235221e-1755-4c57-aa6d-c6a5d10805ae.png)

**Comment by htmgarcia** [comment]
@stevejburge starter proposal:
![Screen Shot 2022-01-25 at 15 55 32](https://user-images.githubusercontent.com/4999794/151066348-c550ecfe-98b2-4770-af49-f4340d9bcf0d.png)

**Comment by stevejburge** [comment]
@htmgarcia Thanks. That helps. Could we try a background color too?

**Comment by htmgarcia** [comment]
@stevejburge updated proposal:
![Screen Shot 2022-01-26 at 10 14 05](https://user-images.githubusercontent.com/4999794/151201713-a67123f6-6151-4240-9c88-b3fbd24c765c.png)

**Comment by stevejburge** [comment]
Thanks @htmgarcia. Yes, please. I can hand over to @ojopaul from here

**Comment by ojopaul** [comment]
Yes, will update to the design.

**Comment by htmgarcia** [comment]
@ojopaul as reference, the box uses the design from sidebar boxes as base.

**Comment by ojopaul** [comment]
Thanks @htmgarcia
