### ISSUE TITLE
Dandelion seems to be returning tags based on WordPress's internal comments

### ISSUE THREAD

**Issue by nazgul** [TaxoPress/TaxoPress#120]
I'm getting very odd results from Dandelion (the new key version). Here's a recommended list of tags.

![image](https://user-images.githubusercontent.com/2261/61393318-940c8800-a875-11e9-94a7-79a7824efed4.png)

**Comment by robertandrews** [comment]
I can't even get to a list such as this. Where is this kind of list supposed to be displayed?

**Comment by dcweeks** [comment]
yes there is much repeating too 
![Screen Shot 2019-09-09 at 2 43 47 PM](https://user-images.githubusercontent.com/35581616/64568731-56c1f500-d310-11e9-8f9f-4301caf91abe.png)
