### ISSUE TITLE
Ways to process large numbers of posts in Auto Terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1200]
We have a customer with 100,000 posts and they are trying to use Auto Terms:

> I am having 100,000 posts and when i am trying to create tags, i am getting following error.
> [Tue Jan 25 15:47:12.659886 2022] [proxy_fcgi:error] [pid 10752:tid 140655204427520] [client 130.176.188.5:37618] AH01071: Got error 'PHP message: PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in apps/wordpress/htdocs/wp-includes/class-wp-term.php on line 198', referer: wp-admin/admin.php?page=st_manage&cpt=gd_udemy&taxo=gd_udemy_tags

Can we find a way to allow users to run the "Existing Terms" featurefor large Auto Terms processes?

Maybe we process them in batches? What happens if the Dandelion API key etc is insufficient?

**Comment by ojopaul** [comment]
If you're referring to 'Add Auto Terms to all existing content', we currently process auto terms in batch of 20 per response before sending another request till they're all done but if this is still not helping, do you want us to add a specific duration time wait before each batch and if so, what should be the wait duration between each batch? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Good question. Maybe the 20 seconds can be a setting? 

And perhaps we can add a pause between requests?

We definitely had time-outs on this test site with 100,000 posts

**Comment by ojopaul** [comment]
Will add them as settings
