### ISSUE TITLE
Layout issues with Pagination on "Manage Terms"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1208]
<img width="721" alt="Screen Shot 2022-01-27 at 5 15 48 PM" src="https://user-images.githubusercontent.com/3868028/151452746-2c22b1b3-2898-45b5-ab58-b3cc34425937.png">

**Comment by ojopaul** [comment]
Okay, fixing that now. On another note, partitioning that page to three side by side doesn't seems to be a good idea due to the page content

**Comment by stevejburge** [comment]
OK, thanks @ojopaul Do you think we should revert this change? Is this page too busy and crowded now?

**Comment by ojopaul** [comment]
Yes, it is due to the newly added right side bar to the already existing 2 column.

I believe we can make exception unless we decided to place the ads under one of the 2 existing column.

**Comment by ojopaul** [comment]
Maybe you can review further after receiving new updated plugin today

**Comment by stevejburge** [comment]
@ojopaul I think you are correct. Sorry about that. Yes - there is not enough room
