### ISSUE TITLE
Fix default term not working for taxonomy

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1216]
Instead of simply using "Uncategorized", we can allow users to choose the default term, or multiple defaults

**Comment by ojopaul** [comment]
@stevejburge Where do you think this will fit in?

**Comment by stevejburge** [comment]
Maybe this could be a new tab inside "Taxonomies"
<img width="463" alt="Screenshot 2023-03-22 at 3 46 52 PM" src="https://user-images.githubusercontent.com/3868028/227019545-f3285485-0020-4bac-b627-c74a5308c333.png">

We do have a setting for this now, but it's confusing:
<img width="916" alt="Screenshot 2023-03-22 at 3 47 10 PM" src="https://user-images.githubusercontent.com/3868028/227019599-8e7bbdf0-6a6b-4d68-9f1c-19102d66f297.png">

**Comment by stevejburge** [comment]
@ojopaul After a user question today, I don't think that "Default Term" box works at all right now

**Comment by stevejburge** [comment]
via @ojopaul we’re only auto adding them to post after saving for the first time
