### ISSUE TITLE
Tags not saving for attachments (media) after update

### ISSUE THREAD

**Issue by orkwood** [TaxoPress/taxopress#124]
Hi,

I am working on an existing website where if you enter a tag, select a pre-existing tag, and then click 'Update' for the attachment (media) the tag disappears when the attachment saves and reloads.

Any ideas?

**Comment by orkwood** [comment]
Some further info...

Disabling the plugin, with tags still available for media, I am able to add and update tags successfully.

Enable the plugin again (with the previous tags saved), the existing tags show up, but when I either add or remove tags and save the media item the changes do not remain. 

This suggests an issue with the plugin.

**Comment by herewithme** [comment]
@orkwood  How did you add the tags to the media? via which plugin?
