### ISSUE TITLE
Safeguards for large sites with 10,000 posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1249]
@ojopaul The Auto Terms feature definitely has an issue with large sites with 1,000's of posts.

I wonder how we make Auto Terms more reliable for large sites.

For example, should the "Schedule" feature only cover new and updated posts? If a site has 100,000 posts, the Schedule feature should not run on every post every hour.

Here's an example problem - this site has 22,000 existing products. It times out when running Auto Terms:
<img width="660" alt="Screen Shot 2022-02-16 at 4 34 14 PM" src="https://user-images.githubusercontent.com/3868028/154360953-7580bda3-0e1a-45ec-8f31-1741797887c5.png">

**Comment by ojopaul** [comment]
Like you suggested, we can add option to enter days that'll be consider for auto terms.

For example, entry 7 means only post in last 7 days will be consider and this settings can be added under existing content tab and applied to both existing content and schedules.

This way, large site will be safeguard and it won't run on all posts. @stevejburge

**Comment by stevejburge** [comment]
That's a very good idea @ojopaul
