### ISSUE TITLE
Font color in Term Display doesn't work

### ISSUE THREAD

**Issue by LudMila72** [TaxoPress/TaxoPress#1254]
Go to TaxoPress--> Click Term Display --> Edit --> Manage Terms Display --> Select Font color minimum and Font color maximum-->Click 'Save Term Display' 
Display color doesn't change

**Comment by stevejburge** [comment]
Hi @LudMila72 

Could you share a screenshot of your settings and result, please?

**Comment by LudMila72** [comment]
![Screenshot 2022-02-21 143946](https://user-images.githubusercontent.com/94811924/155017686-7747912d-b294-4381-bfb6-1c54591bd4ea.jpg)
![Screenshot 2022-02-21 144953](https://user-images.githubusercontent.com/94811924/155018241-c3637707-269d-461a-87d4-94b83dbfc744.jpg)
Hi Steve, 
There are screenshots , whish you would like to see

**Comment by stevejburge** [comment]
@LudMila72 Thanks. Is this TaxoPress version 3.4.5?

**Comment by LudMila72** [comment]
Yes, it is

**Comment by stevejburge** [comment]
@LudMila72 Thanks. Sorry, I'm not seeing this in my testing. Are you using a shortcode to add the terms?

**Comment by LudMila72** [comment]
Yes, I sent you screenshot of shortcode
![Screenshot 2022-02-22 105113](https://user-images.githubusercontent.com/94811924/155169388-8f572155-c68c-41c2-94f4-d0671cdf2918.jpg)

**Comment by stevejburge** [comment]
Thanks @LudMila72. Sorry, I'm not able to confirm this in testing

The odd thing is that your admin screenshots really are out-of-date
