### ISSUE TITLE
Should we add new settings for "Schedule" also?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1256]
Should these be available for for "Schedule" also?
<img width="755" alt="Screen Shot 2022-02-21 at 11 13 17 AM" src="https://user-images.githubusercontent.com/3868028/154992004-263084cc-bd49-4792-b576-e3ee80715e52.png">

They could be very useful here:

<img width="612" alt="Screen Shot 2022-02-21 at 11 15 25 AM" src="https://user-images.githubusercontent.com/3868028/154992359-1dcdc9fb-7896-4ecf-b5ee-2da9cd77313a.png">

**Comment by ojopaul** [comment]
The current settings applied to both  Existing Content and  Schedule @stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul 

Would it be OK to do this separately? People may want different settings for each

**Comment by ojopaul** [comment]
This issue is fixed in pro https://github.com/TaxoPress/TaxoPress-Pro/pull/79
