### ISSUE TITLE
New "Terms" Screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1260]
I think we should add a new "Terms" screen that is going to be similar to "Taxonomies".

- It will be the 2nd link in the Admin Menu after "Taxonomies"
- The main screen will have a table of all the terms on your site with Advanced features
- Click on a term and you'll be able to edit that term.

Maybe we can remove the table from the "Manage Terms" screen and have a more complete version on this new "Terms" screen? "Manage Terms" is trying to have a mini version of this "Terms" screen and also a set of tools.

<img width="1457" alt="Screen Shot 2022-02-25 at 11 36 23 AM" src="https://user-images.githubusercontent.com/3868028/155752458-6f42089a-fd7f-4410-bf4a-d7b6c2ccba26.png">

**Comment by ojopaul** [comment]
@stevejburge 

![terms](https://user-images.githubusercontent.com/92122385/160369834-9d683ab1-9b71-446f-a30f-5a40ac671d3a.jpg)


1.) Please check this screenshot if i understand the request clearly considering the fact you mentioned removing table whereas the table is what display the terms. 

2.) Also, when they click edit to edit a term, we redirect to the term edit page or do you need us to have a custom page to edit the term instead?

3.) The advanced features you mentioned, what are they or it'll be after this implementation?
