### ISSUE TITLE
Replace "Status" with "Settings"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1268]
I think the "Status" column is redundant because we have "Status message"

Instead, can we have a link to the Settings area that added these terms? For example, the link goes to:
admin.php?page=st_autoterms&add=new_item&action=edit&taxopress_autoterms=1

This could be the final column on the right side

![Screen Shot 2022-02-22 at 9 02 27 AM](https://user-images.githubusercontent.com/3868028/155147888-4245b298-e53a-4e39-ac7b-18dd1ac3302b.png)

**Comment by ojopaul** [comment]
- In addition, the auto terms settings title is used as the text link. Also, we didn't save the settings option in log meta before until now, so previous logs before this update may not have settings link.
