### ISSUE TITLE
Add the ability to disable logs

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1281]
From a customer:

> 
I have a lot of posts and my Auto Tags tags run hourly (switched to daily because of my issue). I have 40,000+ logs now because of the new log feature from TaxoPress. Is there a way to disable this? I don't want the database filled up. 

Can we add a new tab called "Logs" here:
<img width="249" alt="Screen Shot 2022-03-01 at 4 07 18 PM" src="https://user-images.githubusercontent.com/3868028/156249020-acd19080-791a-474e-bb08-e2b4ecc7acfe.png">

The options will be:
- Disable logs
- Limit the number of logs

**Comment by ojopaul** [comment]
@stevejburge if we're adding this tab, does that mean the disable and limit only applies per settings basis which shows if user has two auto terms setup with each limit to 1000 each, that shows total limit for all will be 2000 and also, the user can disable log for one settings while leaving it for another settings ?

**Comment by stevejburge** [comment]
@ojopaul Yes, that was my thinking. 

Otherwise, we would need a new settings area that applied to multiple "Auto Terms" setups

**Comment by ojopaul** [comment]
Well, since we don't have a settings for auto terms, we can go with your option then or perhaps, since it's just 2 options "Disable Logs" and logs limit, maybe we can add it on top of the log table filter same way we have delete?

**Comment by ojopaul** [comment]
Yes, will add it there too.
