### ISSUE TITLE
French and Spanish Readme file translation

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1306]
[french.zip](https://github.com/TaxoPress/TaxoPress/files/8215188/french.zip)
[spanish.zip](https://github.com/TaxoPress/TaxoPress/files/8215191/spanish.zip)

**Comment by ojopaul** [comment]
@stevejburge what do we need the "Readme file translation" for or it's same as main translation and i only need to rename them to real translation name(e.g "simple-tags-fr_FR.mo" and "simple-tags-fr_FR.po") and replace them.

For example, the names currently read "wp-plugins-simple-tags-stable-readme-fr.mo" and "wp-plugins-simple-tags-stable-readme-fr.po"

**Comment by stevejburge** [comment]
@ojopaul Sorry, if it's already included in the last release, there is no update

I just accidentally posted twice

**Comment by ojopaul** [comment]
I'll be closing this issue too to know what's left
