### ISSUE TITLE
French translation files

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1307]
[Attachments.zip](https://github.com/TaxoPress/TaxoPress/files/8215196/Attachments.zip)

**Comment by ojopaul** [comment]
I'm closing this issue since french translation is also added here https://github.com/TaxoPress/TaxoPress/issues/1306

**Comment by ojopaul** [comment]
@stevejburge is this french translation same as the one here https://github.com/TaxoPress/TaxoPress/issues/1307 ?

**Comment by stevejburge** [comment]
@ojopaul Yes, sorry about that
