### ISSUE TITLE
Option to limit auto terms schedule action to once per posts 

### ISSUE THREAD

**Issue by ojopaul** [TaxoPress/TaxoPress#1314]
We should introduce another feature that only limit auto terms to once per posts unless user is updating the posts manually

For example,  a post will only be run through schedule just once.
So, I next schedule check, post that has been previously checked will be excluded
That'll limit the chance of running all posts every hour for example

**Comment by stevejburge** [comment]
@ojopaul One suggestion from a customer: Only check posts that have been updated recently. We can check the posts update time in the database.

**Comment by ojopaul** [comment]
@stevejburge i'm wondering if this is much difference to the time limit we just introduce since wordpress update post updated time to same thing as published time for all posts on published.

**Comment by ojopaul** [comment]
@stevejburge i'm wondering if this is much difference to the time limit we just introduce since wordpress update post updated time to same thing as published time for all posts on published.

If this was as a result of the https://github.com/TaxoPress/TaxoPress/issues/1322 issue, i already know how to tackle that.

In short words, adding updated time to publish time may not make any difference since same date will apply to both published and update time.

Limit schedule check to once in lifetime should be enough. If the post is updated after, auto terms will be applied when it's updated or using auto terms old content button but for schedule, limiting it to once per post will limit the traffic hike of checking same set of posts frequentyl.

**Comment by stevejburge** [comment]
Understood, thanks @ojopaul
