### ISSUE TITLE
some providers are dead

### ISSUE THREAD

**Issue by x0rzkov** [TaxoPress/taxopress#133]
Hi guys,

Hope you are all well !

Some providers links are dead:
- http://www.alchemyapi.com/
- http://developer.zemanta.com/
- https://www.mashape.com/proxem/ontology-based-topic-detection

Shall we cleanup them ?

Cheers,
X

**Comment by stevejburge** [comment]
Closing in favor of https://github.com/TaxoPress/taxopress/issues/187
