### ISSUE TITLE
Issue with get_taxonomies

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1352]
> just ran into an issue. I want to display all custom taxonomies on my site. Normally I do this with $taxonomies = get_object_taxonomies( 'post' ); or get_taxonomies
> 
> Both only display the wordpress taxonomies but not the ones added by taxopress. Any idea of what I need to do

I see a similar issue happened with Toolset before:
https://toolset.com/forums/topic/get_taxonomies-does-not-return-taxonomies-with-multiple-post-type-assigned/

**Comment by ojopaul** [comment]
@stevejburge 
Here's another usage example:

This will display all taxonomies:
`get_taxonomies([], 'object', 'or');
`
This will display all taxonomies with show_ui
`get_taxonomies(['show_ui' => true], 'object', 'or')
`
This will display all taxonomies with show ui attributes and public
`get_taxonomies(['public' => true, 'show_ui' => true], 'object', 'or')
`
Let me know if the customer need help with anything else.

**Comment by ojopaul** [comment]
@stevejburge in relation to `get_object_taxonomies( 'post' );`

I tested it and the code
`$taxonomies = get_object_taxonomies( 'post' );` output all taxonomies attached to the post type 
post.

**Comment by stevejburge** [comment]
Thanks @ojopaul. I'll reopen if the customer has any issues with this
