### ISSUE TITLE
Auto Links feature is hiding the product description

### ISSUE THREAD

**Issue by califanet** [TaxoPress/TaxoPress#1353]
If there are html codes like `&trade;` & product tags in the description, the auto-link feature is hiding the description.

**Comment by stevejburge** [comment]
@califanet Thanks for using TaxoPress.

Sorry, one line this isn't enough for a Github issue.

When posting here, please post full details so that developer can follow all your steps and re-create the issue.

**Comment by califanet** [comment]
Include `&trade;` in a description and try to load the page. There is no more description I can include here.

**Comment by stevejburge** [comment]
@califanet Sorry, that's not enough. What is a "description"? SEO description? WooCommerce product description? Where does it appear? I can't ask our developers to guess.

How about posting with the detailed screenshots?

**Comment by califanet** [comment]
I just investigated further. Here is the full detail of the issue:

If there is a product tag like "waterproof" on the website and we have the following woocommerce product desction, if the Auto Link is enabled, the description is not showing. So it's the combination of the html codes and tags that don't work properly together:

`&trade;` waterproof


I tried using other html codes like `&#44;` and the same issue exists.

Please advise if you need more details.

**Comment by stevejburge** [comment]
@califanet Yes, that's very helpful, thanks. We'll test this and fix if we can confirm the problem
