### ISSUE TITLE
Change Taxonomies "Count" link to go to "Terms" screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1366]
When we have the new filters from https://github.com/TaxoPress/TaxoPress/issues/1358 let's change the "Count" link to go to the "Terms" screen with the correct taxonomy filter active

![new-terms-screen](https://user-images.githubusercontent.com/3868028/161093056-3f256c0e-02d0-4077-aba4-77df051f7e20.png)

**Comment by ojopaul** [comment]
@stevejburge this part is not clear `let's change the "Count" link to go to the "Terms" screen with the correct taxonomy filter active`

If we're linking to Taxonomy screen, it doesn't have/need any correct active filter.

Example of Taxonomy screen is `/wp-admin/edit-tags.php?taxonomy=product_cat`. 

I'm wondering if you're referring to something else and not taxonomy screen?

**Comment by stevejburge** [comment]
@ojopaul Good point. Can we add that filter?
https://github.com/TaxoPress/TaxoPress/issues/1384

**Comment by ojopaul** [comment]
Are you refering to '/wp-admin/edit-tags.php?taxonomy=media_tag&post_type=attachment'?

For example, we currently have the count link to, `'/wp-admin/edit-tags.php?taxonomy=media_tag'` with no post type. 
So, are you asking to add post type for example `'/wp-admin/edit-tags.php?taxonomy=media_tag&post_type=attachment'` linking to selected filter post type screen? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul My thought is that the "Count" link could go here: /wp-admin/admin.php?page=st_terms

**Comment by ojopaul** [comment]
Isn't that same as reloading the page? The /wp-admin/admin.php?page=st_terms linked back to TaxoPress Terms screen where the count is.

**Comment by ojopaul** [comment]
Wait, are you referring to something like /wp-admin/admin.php?page=st_terms&taxonomy=post_tag.

So, when it's clicked, the post_tag will be selected as active filter? @stevejburge

**Comment by ojopaul** [comment]
The idea do make sense but the you think count is appropriate column to link? Expectation of clicking count will be to view all posts in the tags? @stevejburge

**Comment by stevejburge** [comment]
Not all the posts, but all the terms.

If we link to /wp-admin/admin.php?page=st_terms&taxonomy=post_tag then users will view all the terms, right?

**Comment by ojopaul** [comment]
Yes, it'll link the terms with post_tag taxonomy but that's not what the count represent, the count just like the count on original tags page '/wp-admin/edit-tags.php?taxonomy=post_tag' represent total number of posts for the term.

But if you want it this way, i'll implement it then @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Ah, you're right. Sorry, these are old issues and I misunderstood this one also.

My intention was to change the "Count" on the "Taxonomies" screen:
![Screen Shot 2022-04-28 at 8 52 49 AM](https://user-images.githubusercontent.com/3868028/165756466-5561556b-f93d-4e22-bd04-a3ec04e61e51.png)

**Comment by ojopaul** [comment]
Now, it make sense. Understood. @stevejburge

**Comment by stevejburge** [comment]
Sorry, it's my fault. Looking back, I posted the wrong screenshot in the original post
