### ISSUE TITLE
View in frontend

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1369]
Can we change this button?

It should be "View in frontend" and go to the taxonomy archive on the front of the site:
![Screen Shot 2022-03-31 at 11 47 52 AM](https://user-images.githubusercontent.com/3868028/161096982-b3aad95e-8ed9-4734-a4b5-a5bc58a8d7c0.png)

**Comment by ojopaul** [comment]
@stevejburge i'm lost here. Does Taxonomy itself has an archive page?

**Comment by stevejburge** [comment]
@ojopaul I'm thinking we link to the archives like this?
https://taxopress.com/category/blog/releases/
https://taxopress.com/tag/media-tags/

**Comment by ojopaul** [comment]
For category(https://taxopress.com/category/blog/releases/), where does the `blog/releases` come from? @stevejburge

**Comment by ojopaul** [comment]
I believe you may be viewing it in Terms context which is not show.

The screen you linked is Taxonomy edit screen. @stevejburge

**Comment by stevejburge** [comment]
Sorry, I should have had more coffee this morning.
