### ISSUE TITLE
Update "Automatically fill colors between maximum and minimum" to reflect right label

### ISSUE THREAD

**Issue by AlesyaBreenkova** [TaxoPress/TaxoPress#1371]
The "Automatically fill colors between maximum and minimum" checkbox doesn't seem to be working, as I got the same results (the same color codes) with the checkbox selected and unselected.  Settings used: Font color minimum  - #999999 , Font color maximum  - #000000

Please see the attached screenshot
![Screen Shot 2022-03-31 at 9 40 25 PM](https://user-images.githubusercontent.com/31319775/161279688-249c8e1c-781e-4d57-a88c-c6c3dd642407.png)

**Comment by ojopaul** [comment]
@stevejburge I don't know what this feature is supposed to do. The reason it produces same result is because the default is set to true, so when not set, it's still always true.

However, by changing the default to false and checking the current implementation, it removes %tag_color% from tags thereby making all tags colorless. Is that really it work?

**Comment by stevejburge** [comment]
@ojopaul Maybe this needs more explanation for users too.

Maximum = the color of the most popular term
Minimum = the color of the least popular term

All the terms in the middle get a mix of those colors

**Comment by ojopaul** [comment]
@stevejburge I've traced the code and just like i explained above, i believe the label for "Automatically fill colors between maximum and minimum" is wrong.

After fixing the issue, this is how it works:
- When the checkbox is checked, the tags are colored.
- When the box is uncheck, the tags are not colored.
So, i believe the label is not right and should have been something like, Enable maximum and minimum terms color but if you don't see the need to change the label, then i'll update the fix but that's how it work which is to enable / disable term color and not some other way

**Comment by stevejburge** [comment]
@ojopaul I think you're right. There should be a setting "Enable colors for terms".

If you check that box, these 3 will then appear underneath:

![Uploading Screen Shot 2022-08-22 at 10.31.15 AM.png…]()

**Comment by ojopaul** [comment]
You're still not getting me, there's no control for mixing color. 

What the "Automatically fill colors between maximum and minimum" control does is determining whether to enable or disable color.

I'll just make the update maybe that'll make you understand better.

@stevejburge
