### ISSUE TITLE
When "Maximum Character Length for an Auto Link" under "Control" tab in "Manage Auto Links" is set to "0", auto links still appear in the post   

### ISSUE THREAD

**Issue by AlesyaBreenkova** [TaxoPress/TaxoPress#1379]
When the user sets to "0"  "Maximum Character Length for an Auto Link" under "Control" tab in "Manage Auto Links"  and saves the settings, auto links are still being displayed, while "the correct" system behavior should probably be to show no auto links at all. 

Anyway, this settings seems to be producing inconsistent results (please see screenshots for Max character length set to 0 (Screenshot 1) and Max character length set to 10 (Screenshot 2))

![Maximum character length set to zero](https://user-images.githubusercontent.com/31319775/165555354-bb699a9c-1feb-46ec-ab1b-e88e330ef57a.PNG)

![Maximum character length set to ten](https://user-images.githubusercontent.com/31319775/165555315-c97c7a24-f70d-450b-a57e-816fb5d93795.PNG)

**Comment by ojopaul** [comment]
@stevejburge @AlesyaBreenkova  

1. The field is not required. Setting it as 0 is same thing as not setting it or is this supposed to work in a specific way?
2. From the attach screenshot, none of the linked terms character exceed 10 and that's the function to make sure linked terms are not more than provided character if set.

**Comment by stevejburge** [comment]
@AlesyaBreenkova I've moved this off the milestone to help us with a quick release. I'll test this out carefully for the next milestone
