### ISSUE TITLE
Connect tags to specific category

### ISSUE THREAD

**Issue by manjo-me** [TaxoPress/taxopress#138]
Gents and gals,

I've been trying to figure out how to relate/lock tags to a specific category so when browsing a specific category on a site only the approved tags will show.

Is that considered a relevant feature request or has it already been discussed and iceboxed?

Take care!

**Comment by stevejburge** [comment]
Hi @manjo-me. You would probably need to build a relationship between them. Perhaps a plugin like this? https://metabox.io/plugins/mb-relationships/
