### ISSUE TITLE
Can we add a "Taxonomy" and "Post Types" filter to the "Terms" screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1384]
This would make this possible: https://github.com/TaxoPress/TaxoPress/issues/1366

The Filters can go up here next to Bulk Actions:
![161093056-3f256c0e-02d0-4077-aba4-77df051f7e20](https://user-images.githubusercontent.com/3868028/165745631-0b1c9fca-bdd0-4df1-8735-e9960fc81884.png)

**Comment by ojopaul** [comment]
Is this different from https://github.com/TaxoPress/TaxoPress/issues/1358 ?

**Comment by stevejburge** [comment]
No, sorry! It's the same. I should have searched for that first.
