### ISSUE TITLE
Terms dropdown should persist with current choice, not Categories

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1395]
On the Terms screen, a term will be in one taxonomy:
<img width="814" alt="Screen Shot 2022-05-04 at 2 57 03 PM" src="https://user-images.githubusercontent.com/3868028/166806548-43f83d5a-6294-4ba4-ba39-c450f07a0c6e.png">

If you open the dropdown, it defaults to Categories:

<img width="760" alt="Screen Shot 2022-05-04 at 2 57 09 PM" src="https://user-images.githubusercontent.com/3868028/166806629-ab05eb5a-3499-469e-bf8c-0b98604db361.png">

**Comment by ojopaul** [comment]
@stevejburge Can you retest this issue?

It seems to be working for me.

**Comment by stevejburge** [comment]
@ojopaul Yes, this does still happen for me. This is on TaxoPress.com
<img width="899" alt="Screenshot 2023-03-22 at 3 38 02 PM" src="https://user-images.githubusercontent.com/3868028/227017511-d1fe1e34-fa60-4417-ac75-1a69194c377b.png">
