### ISSUE TITLE
Tabs not working in WP 5.5

### ISSUE THREAD

**Issue by fingertrouble** [TaxoPress/taxopress#140]
The tabs are gone again in the latest version of WP, you cannot select a provider, you just get:

"Choose a provider to get suggested tags (local, yahoo or tag the net)."

The same in Safari 13.1.2, Brave Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit) and Chrome Version 84.0.4147.105 (Official Build) (64-bit) and FF Quantum 68.10.0esr (64-bit).

Can this be fixed? There isn't an alternative to Simple Tags, really.

**Comment by stevejburge** [comment]
Can't reproduce 5.6. Please reopen if problem still exists
