### ISSUE TITLE
Mass Merge Tags

### ISSUE THREAD

**Issue by MizMoffatt** [TaxoPress/taxopress#141]
Hi there,

I can't figure out how to merge tags with Simple Tags—it looks like I would have to edit individual tags across each post. Is there a way to do a bulk edit on tags that would allow me to merge a few tags under one term? Am I missing something here? 

![Merge Tags_Missing](https://user-images.githubusercontent.com/70243578/91781418-44e3fc80-ebc8-11ea-8968-a76ab3a08cdb.jpg)

**Comment by manuelrocha88** [comment]
@MizMoffatt instead of making use of "Mass edit terms" make instead use of "Manage Terms", which is the option right below "Mass edit terms".
