### ISSUE TITLE
Allow users to show a filter for on Posts screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1412]
This task involves two steps:

1) A new setting inside "Taxonomies"
2) A new filter inside the "Posts" screen

For step #1, let's add a new "Show filter" option here in the "Taxonomies" editing screen:
<img width="617" alt="Screen Shot 2022-05-23 at 11 14 31 AM" src="https://user-images.githubusercontent.com/3868028/169851609-20c17a98-eef7-426e-94bc-94afcf98e44e.png">

For step #2, here's an example of what users want as a filter inside the "Posts" screen for their taxonomies:
![TinyTake23-05-2022-09-09-42_637889082004435772](https://user-images.githubusercontent.com/3868028/169851715-421398d3-4b06-42ea-a6a1-82941f4de865.png)

**Comment by jonathanpaulbbaroma** [comment]
Hi @stevejburge, Jonathan Paul "JP" Baroma here.

I have already submitted a pull request for my coding results for this test.

**Comment by jonathanpaulbbaroma** [comment]
For step #2, may I know if you can provide more details for that one?

**Comment by jonathanpaulbbaroma** [comment]
For step #2, does it mean getting the taxonomies for posts, then adding them as filters on the Posts Screens?

**Comment by ojopaul** [comment]
@jonathanpaulbbaroma 
Step #1 leads to step 2.

For example, if in step 1, I edited a custom taxonomy and I enabled Show filter for the taxonomy(Step 1 completed).

When i visit the posts screen that are enabled for the taxonomy(This could be native Posts, Pages or Custom Post Types), I want to be able to see the taxonomy dropdown for filter.
