### ISSUE TITLE
Whole Words option for Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1413]
We have this in Auto Terms:

<img width="1073" alt="Screen Shot 2022-05-23 at 12 02 21 PM" src="https://user-images.githubusercontent.com/3868028/169860644-3cd2608b-de8f-4ea2-a96f-fc66892a5c13.png">

Let's add a similar feature for Auto Links. One user reports this:

> The AutoLink function is very interesting.
> 
> But it is applied to a part of word, corresponding to the tag, the ending of the word doesn't get into the link. 
> 
> Is there any setting or customization, which allows to use this function only for exact occurrences of the tag (full compliance with the lexeme's spelling)

**Comment by stevejburge** [comment]
One more request for an "exact match" option.

They have a term called "X". This causes problems with other terms such as "X-Men" and "X-Force".

**Comment by ojopaul** [comment]
@stevejburge Is this different from what's been discussed in https://github.com/TaxoPress/TaxoPress/issues/1973?

**Comment by stevejburge** [comment]
Yes, but perhaps simpler than that issue. 

I think the bigger issue is we should work towards unifying the Auto Terms and TaxoPress AI features. So let's leave this for now
