### ISSUE TITLE
Wrong  cyrillics translations. Feature request

### ISSUE THREAD

**Issue by Denend** [TaxoPress/TaxoPress#1418]
We are using your Taksopress plugin on a premium subscription. We have some troubles with its usage, we think the functional can perform better.

We are asking for the following functionalities to be added to the plugin:
1. Add processing of cyrillics. Its  currently working incorrectly with the words combinations and words with a hyphen.

Example:
I am looking for «лед»
It finds - founds nothing, however there are respective words in the articles

2. Please, finish the regular exp. word search, When using short words, finds not a complete word, but an entry into a longer word.

Example:
I'm looking for «Лед»
It finds (this is incorrect) «Гололед»

**Comment by stevejburge** [comment]
Hi @Denend 

Thanks for this. Can you send us in a support ticket, please? Github isn't the best place for feature requests

**Comment by Denend** [comment]
Hi, I didnt find the place to create a ticket on your site
Could you please send a page link
Regards
Daniel
