### ISSUE TITLE
Tags gets split when having an ‘&’ Ampersand in name

### ISSUE THREAD

**Issue by manuelrocha88** [TaxoPress/taxopress#143]
https://wordpress.org/support/topic/tags-gets-split-when-having-an-ampersand-in-name/

**Comment by stevejburge** [comment]
> We have some tags with an Ampersand ‘&’ in its name.
> 
> Example: “Pizza | Pasta & Risotto”
> 
> When clicking on this tag in Click-Tags, only “Pizza | Pasta” is added to the tags-list, and a new tag “Risotto” is created.
