### ISSUE TITLE
PHP 8 errors

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1474]
https://wordpress.org/support/topic/receiving-php-8-errors/

> With PHP 7.4 EOL approaching, we are preparing our WordPress sites to upgrade to PHP 8. We are receiving the following PHP 8 errors for this plugin.
> 
> FOUND 2 ERRORS AFFECTING 2 LINES ———————————————————————- 358 | ERROR | Using an unparenthesized expression containing a “.” | | before a “+” or “-” has been deprecated in PHP 7.4 and | | removed in PHP 8.0 424 | ERROR | Using an unparenthesized expression containing a “.” | | before a “+” or “-” has been deprecated in PHP 7.4 and | | removed in PHP 8.0

**Comment by stevejburge** [comment]
We probably need a general clean-up for 8.1

<img width="1374" alt="Screen Shot 2022-11-16 at 9 09 25 AM" src="https://user-images.githubusercontent.com/3868028/202202772-910d5d2b-11cf-4d00-ac7a-caf6b6c13533.png">

**Comment by timnolte** [comment]
What is the plan for tackling this? I am looking for a plugin like this for a client but we have already moved all of our client sites to PHP 8.0 and will be starting moves to PHP 8.1 soon. With PHP 7.4 already EOL for months it seems like this should be a priority.

**Comment by stevejburge** [comment]
Hi @timnolte. Thanks for using TaxoPress. This is attached to the milestone for 3.6.6, the next release.

**Comment by ojopaul** [comment]
Fixed in https://github.com/TaxoPress/TaxoPress/pull/1559

**Comment by davejenx** [comment]
I'm getting a similar error from a phpcs scan but in a different vendor directory...

```
FILE: .../wp-content/plugins/simple-tags/vendor/sabre/vobject/lib/Recur/RRuleIterator.php
----------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------------------------------------------------------------------------------
 358 | ERROR | Using an unparenthesized expression containing a "." before a "+" or "-" has been deprecated in PHP 7.4 and removed in PHP 8.0
 424 | ERROR | Using an unparenthesized expression containing a "." before a "+" or "-" has been deprecated in PHP 7.4 and removed in PHP 8.0
----------------------------------------------------------------------------------------------------------------------------------------------
```
Shall I open a separate issue?

**Comment by stevejburge** [comment]
@davejenx Yes, please. This issue is years old

**Comment by davejenx** [comment]
Done: #2533 .
