### ISSUE TITLE
Media Tags are not working

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1475]
It's not currently possible to usefully add Media Tags to images

It is possible to add them here:
<img width="351" alt="Screen Shot 2022-10-28 at 2 50 07 PM" src="https://user-images.githubusercontent.com/3868028/198710611-2b472a77-1a3a-4355-a14a-0267b00ae713.png">

But there's no frontend view possible, even if they are successfully tagged:
<img width="784" alt="Screen Shot 2022-10-28 at 2 57 22 PM" src="https://user-images.githubusercontent.com/3868028/198711980-e76a60b2-22ed-45c3-8d8f-aa81941d7d54.png">

The View link goes to "Nothing here"

**Comment by ojopaul** [comment]
@stevejburge This is related to https://github.com/TaxoPress/TaxoPress/issues/1477

The link goes to "Nothing here"(404) because media has status of inherit which are not been displayed in frontend.

If the media tags is added to other post type that has published status, it'll display in frontend.
