### ISSUE TITLE
Not possible to switch "Public Taxonomies" to "Private Taxonomies"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1482]
Is it missing a button to make this filter work?
![Screen Shot 2022-12-01 at 11 47 04 AM](https://user-images.githubusercontent.com/3868028/205111206-7b3dfe41-82fc-42eb-9685-ffca7f2338ee.png)

**Comment by ojopaul** [comment]
@stevejburge What's the issue, when you select new option, the page didn't reload?

Can you retest to re-confirm as it's working in my test.

**Comment by stevejburge** [comment]
@ojopaul Sorry, maybe a false report here
