### ISSUE TITLE
Remove manage terms table

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1592]
Deprecated: Automatic conversion of false to array is deprecated in /home/cokagohogu5435/web/d-porpoise-sofo.instawp.xyz/public_html/wp-content/plugins/simple-tags/inc/class.client.tagcloud.php on line 487

![Screenshot 2023-03-31 at 12 26 19 PM](https://user-images.githubusercontent.com/3868028/229177006-7f7b5499-d50f-4484-9ea7-2bad2631991c.png)

**Comment by stevejburge** [comment]
@ojopaul Maybe it would help if we just remove this box? It's a worse version of what we have on the "Terms" screen
<img width="518" alt="Screenshot 2023-03-31 at 2 16 08 PM" src="https://user-images.githubusercontent.com/3868028/229198662-20df81a0-2510-49d9-a601-abe5cd77a941.png">

**Comment by ojopaul** [comment]
@stevejburge 
1. What were you trying to do when you got the error on the screen?
2. Do you mean the search box should be removed or what box are you referring to?

**Comment by stevejburge** [comment]
@ojopaul I think it would be better to remove the whole table. It's the same thing as we have on the "Terms" screen
