### ISSUE TITLE
various errors with class.client.autolinks.php

### ISSUE THREAD

**Issue by jcvignoli** [TaxoPress/TaxoPress#1615]
I use taxopress 3.7.1 with wordpress 6.2

I guess this bug appeared with 3.7.1 upgrade. Various errors fill my apache log, such as:
```
PHP Warning: Undefined variable $rel in wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 839
PHP Warning: Undefined variable $case in wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 839
```
But it may have started with 3.7 release, both where updated in a short timeframe on my wordpress install.

**Comment by ojopaul** [comment]
Fixed in https://github.com/TaxoPress/TaxoPress/issues/1610
