### ISSUE TITLE
"Whole words" setting for Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1621]
Can we add a "Whole words" setting for Auto Links to help solve this issue: https://github.com/TaxoPress/TaxoPress/issues/1620
<img width="1061" alt="Screenshot 2023-04-14 at 10 33 33 AM" src="https://user-images.githubusercontent.com/3868028/232074228-9b7ec600-9b40-4f4c-8dd4-33b40af04639.png">

**Comment by ojopaul** [comment]
@stevejburge This settings doesn't make sense for Auto link. I think we should rather fix the problem rather than introducing another one due to uneccesary feature.

**Comment by ojopaul** [comment]
@stevejburge The linked issue is fixed and I'm still on the point of the feature not making sense and will rather cause more issues since by default, autolink only link whole word and introducing linking words that are not whole word may lead to another series of bugs to fix.
