### ISSUE TITLE
Auto Links has problems with attribute

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1637]
Link with screenshots https://secure.helpscout.net/conversation/2222945258/181350?folderId=4410095

**Comment by ojopaul** [comment]
Update:

Further testing reveal this issue is not actually with < > character but instead attribute.

For example, if content contains **< a href="mailto:ojopaul.dev@gmail.com" target="_blank" aria-label="Email" >** and there's tags with **href**, it'll break autolink
