### ISSUE TITLE
Post Type Filter for Related Posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1649]
Can we have a post type filter for Related Posts? 

For example, only show Posts or WooCommerce Products?

**Comment by ojopaul** [comment]
@stevejburge Don't we already do? 
Related post comes from selected post types in the settings as shown in the screenshot below

![rel](https://github.com/TaxoPress/TaxoPress/assets/92122385/a9bf68aa-7769-40d7-8b42-a5a764500f99)
