### ISSUE TITLE
Synonyms option for Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1656]
Could we add an option tab for Auto Links?

- Add links to synonyms

We can add these two options also and clarify them. Can they be combined into one choice?

<img width="887" alt="Screenshot 2023-06-12 at 10 07 38 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/9aa3c7d7-75cc-4ee1-b237-86c14d43162d">

**Comment by ojopaul** [comment]
Second part https://github.com/TaxoPress/TaxoPress/issues/1623

These two boxes are confusing:
<img width="1058" alt="Screenshot 2023-04-14 at 11 31 56 AM" src="https://user-images.githubusercontent.com/3868028/232089344-f487868c-e9af-4f7d-b225-570bdf40253a.png">

Can we provide one box?
- Default: Only add Auto Links for terms that are attached to the post.
- Other option: Only add Auto Links for terms that are not attached to the post.
- Other option: Add Auto Links for all terms.

**Comment by ojopaul** [comment]
@stevejburge On the second part, I think there's some misunderstanding or wrong label as those two options are not same thing going by the source code.

1. **Add links for unattached terms:** _By default, TaxoPress will only add Auto Links for terms that are attached to the post. If this box is checked, TaxoPress will add links for all terms._
So, this only determine the source of auto links terms
- If the option is enabled, autolink terms will be from all the selected taxonomy terms
- If the option is disabled, autolink terms will be from current post

2. **Don't add links for attached terms:** _Don't add Auto Links if the term is already attached to the post._
- If the option is enabled, autolink will not be added for linked that are already added to the post as terms
- If the option is disabled, autolink will be added even if term is added/assigned to the post

I tried to explain based on the source code but the thing is, both option are not same, neither are they word and opposite as they're used in different action.

**Comment by ojopaul** [comment]
I moved second part to the original issue to avoid blockage here https://github.com/TaxoPress/TaxoPress/issues/1623
