### ISSUE TITLE
Remove "Tracking" feature

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#166]
This setting is under the "Features" tab. We definitely don't need it:
<img width="1014" alt="Screen Shot 2021-02-20 at 11 52 08 AM" src="https://user-images.githubusercontent.com/3868028/108602804-17575f00-7372-11eb-87d7-8ad5c94cccc6.png">

The code is in these 7 files: 
https://github.com/TaxoPress/taxopress/search?q=tracking

**Comment by olatechpro** [comment]
This featured already removed before
