### ISSUE TITLE
Maximum and Minimum number of terms per post

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1677]
Related to this: https://github.com/TaxoPress/TaxoPress/issues/1676

We could add a setting for the maximum and Minimum number of terms per post

**Comment by ojopaul** [comment]
@stevejburge Where are we putting this settings and also note, this will require lot of thinking, trial and error work since there's no custom way of doing it especially in showing the error message on the screen and Block editor integration.
