### ISSUE TITLE
"Count" column is wrong if the taxonomy is attached to multiple post types

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1685]
It's easy to break this "Count" column.

If a term is attached to 2 posts and 2 pages, the Count will show 2. Plus the link will be only to Posts.

<img width="1270" alt="Screenshot 2023-06-30 at 4 44 33 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/8758215e-a078-4c27-aadc-904b87a0c91e">

**Comment by ojopaul** [comment]
@stevejburge This is wordpress issue and not really tag groups.

Each term contain `$term->count` which we're outputting on that page. I don't think we should be running expensive post count query for this issue as long as WordPress doesn't fix it from their end or did you get a different count checking it on wordpress count page?

**Comment by stevejburge** [comment]
Thanks @ojopaul

Is there a way to accurately count across post types? If not, perhaps we remove this "Count" or have a different column for each post type

**Comment by stevejburge** [comment]
@ojopaul Still not working correctly in 3.9. Should we perhaps remove the link from the count?

**Comment by ojopaul** [comment]
Removed
