### ISSUE TITLE
TAXOPRESS PRO language discrepancy

### ISSUE THREAD

**Issue by wocmultimedia** [TaxoPress/TaxoPress#1690]
Hi,
I updated the Taxopress PRO to 3.8.0 and within the languages folder the dependencies from simple-tags are not updated to latest translations I supplied you that instead are correctly added to Taxopress Free.
Do I make the changes and when I finish to translate the ones related to Taxopress only I will make a complete zipfile and sent it to you. So you just gave to open and paste in the plugin folder?

**Comment by ojopaul** [comment]
@wocmultimedia Translate free in free version, they'll be added to pro on release

**Comment by wocmultimedia** [comment]
@ojopaul ,
Taxopress free is already translated and updated. Here's the files of the free version again 
[ES-FR-IT_TaxoFree_Translation_toBeAdded_inPRO_folder.zip](https://github.com/TaxoPress/TaxoPress/files/11968001/ES-FR-IT_TaxoFree_Translation_toBeAdded_inPRO_folder.zip)

LATER I send you the bunch of strings related to Pro only

**Comment by wocmultimedia** [comment]
@stevejburge @ojopaul ,
Here's the ES-FR-IT updates for TaxoPress PRO. These are the strings for Pro only.
[TAXOPRESS-PRO_ES-FR-IT_translation_Updates_July2023.zip](https://github.com/TaxoPress/TaxoPress/files/11969784/TAXOPRESS-PRO_ES-FR-IT_translation_Updates_July2023.zip)

Thanks,
Angelo
