### ISSUE TITLE
Tag created successfully when description has more than 50000 characters

### ISSUE THREAD

**Issue by kryana1357** [TaxoPress/TaxoPress#1707]
Tag is created successfully after inserting over 50000 characters in Description text field.

Posts --> Tags
Fill in the text fields in "Add New Tag" section
Create a long description (over 50000 characters) in "Description" text field
Click "Add New Tag" button

![Screenshot 2023-07-18 163147](https://github.com/TaxoPress/TaxoPress/assets/137800627/e3b1cd74-887b-4bbd-9687-1fe5a5ef3c48)
![Screenshot 2023-07-18 163740](https://github.com/TaxoPress/TaxoPress/assets/137800627/55c759a2-44b7-43dc-a9e2-7bf93f4c5e05)

**Comment by stevejburge** [comment]
@kryana1357 Sorry, this a WordPress core issue. It's nor related to TaxoPress
