### ISSUE TITLE
Include Synonyms and Linked Terms on the Dashboard

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1713]
Let's allow users to enable or disable these. <img width="1011" alt="Screenshot 2023-07-19 at 10 19 20 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/81145b2f-13a7-4ed8-b3d6-d2c3056fffae">

**Comment by ojopaul** [comment]
@stevejburge Can you add dashboard description for the two?
