### ISSUE TITLE
Small error message updated

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1735]
Related to this: https://github.com/TaxoPress/TaxoPress/issues/1730

New: This synonym can't be added because at least one of "Red Delicious", "Golden Delicious, "Granny Smith" is a term on this site.

<img width="857" alt="Screenshot 2023-07-25 at 3 48 48 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/9fa33fc5-073c-4830-854d-a4f3ac3a95c8">

**Comment by ojopaul** [comment]
@stevejburge Do you see this in latest update?

**Comment by stevejburge** [comment]
@stevejburge yes, this was in 3.9.0 I believe

**Comment by ojopaul** [comment]
@stevejburge I can't find that message in any of my test

**Comment by stevejburge** [comment]
<img width="911" alt="taxopress" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/aef462ee-84fc-4656-8798-834f4c897358">

**Comment by stevejburge** [comment]
This is slightly a different issue from this message:

<img width="866" alt="Screenshot 2023-07-27 at 9 25 38 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/ac85971a-671f-4015-a8ed-c1e0890c42ff">

**Comment by ojopaul** [comment]
Now i see what the issue is, https://github.com/TaxoPress/TaxoPress/issues/1730 was opened after the last really and is end up been a duplicate cos https://github.com/TaxoPress/TaxoPress/issues/1730 fixed the issue
