### ISSUE TITLE
Auto Terms Limit not obeyed

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1738]
The Auto Terms Limit setting is not followed if you click "Add Terms to Existing Content"

Link: https://secure.helpscout.net/conversation/2314019207/206012?folderId=4410095

<img width="1035" alt="Screenshot 2023-07-27 at 7 56 45 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/c765488d-4814-4873-9f2f-6454dd276c05">
<img width="981" alt="Screenshot 2023-07-27 at 7 58 28 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/22276022-99a3-4935-91d7-69b2ddd84cc6">

**Comment by ojopaul** [comment]
closing this for https://github.com/TaxoPress/TaxoPress/issues/1746
