### ISSUE TITLE
Synonyms: Ability to use multiple names for one tag

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#174]
> I have users with name differently like Steve Burge and Burge Steve (hungarian names are in different order, but in english text differ from hungarian text) but means the same person. I would like to handle it right and NOT change replace all over the texts.
https://wordpress.org/support/topic/synonyms-needed/#post-14090685

Solution: There is one tag, but it can use different names

**Comment by Vidyut** [comment]
Much needed. I'm not much of a coder, but am happy to help with any testing.

**Comment by stevejburge** [comment]
There's a follow-up from a user relying on the Auto Tags:

> Ideally, if any of these words are found in a post it should e.g. generate an ‘oranges’ tag, rather than three separate tags:
> 
> orange
> oranges
> clementines

I presume this could be done automatically for a lot of plurals, but something like oranges / clementines would need a manual option.

**Comment by zee3h** [comment]
Hi there - can I just check that this is a feature that's definitely coming? I'm trying to lock down the tagging approach for my forum migration and knowing that this feature is coming would help (not to mention make me very excited and happy!)

**Comment by stevejburge** [comment]
@zee3h It's highly likely, yes. To be as honest as possible, I'll give two caveats:

- We've not started building it yet, so not ETA
- It may be part of a Pro version of the plugin

**Comment by zee3h** [comment]
Makes sense.

- Do you have any pricing info/thoughts on how Pro would look like? 
- Also, any chance we get in on a complimentary Pro version by helping with testing and bug reporting?

**Comment by stevejburge** [comment]
@zee3h 

- Probably around the $60 per year mark initially. We're still listening to customers as to what features they need and what's missing from TaxoPress
- Sure thing, happy to do that

**Comment by zee3h** [comment]
Great! Let me know if there's a mailing list to join in case you need feedback or testing, and how to report bugs (couldn't find anything within Taxopress)

**Comment by stevejburge** [comment]
Thanks @zee3h. Bug reports are best posted here on Github, please

**Comment by stevejburge** [comment]
One more:

> 
I'm trying to find a way to display terms that are essentially the same for my purposes (eg in Australia we use the terms indigenous, Aboriginal and First Nations to mean pretty much the same thing). It would be fantastic to connect these together so that the tag archive page for "indigenous" would also show the tags "Aboriginal" and "First Nations", and posts tagged with any of the three. I tried extending the tag taxonomy by adding a custom field but can't get it to work.

**Comment by stevejburge** [comment]
From a user:

> My idea would be that you create a custom repeater field for taxonomies that you also check against words within the content.

**Comment by goncalosilva** [comment]
Hi, I'm also interested in this feature. 
Let me share two different uses for auto tag terms with synonyms:
- Women tag, could store women (plural), woman (singular)
- Concert tag, could store in different languages e.g. concerts, live band, musique en live, concerto
Take a look to [Automatic Post Tagger plugin](https://wordpress.org/plugins/automatic-post-tagger/#screenshots) they solve this by using a field called related keywords

**Comment by stevejburge** [comment]
Released in 3.8.0
