### ISSUE TITLE
Prevent "Merge Terms" from automatically adding Default Category

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1741]
I can confirm this bug report: "Merge Terms" does add the Default Category
https://wordpress.org/support/topic/caused-even-more-work/

**Comment by ojopaul** [comment]
@stevejburge Is this talking about merge terms in the Manage Terms > Merge Terms?
![merge](https://github.com/TaxoPress/TaxoPress/assets/92122385/9429269a-0a2a-48d4-94d2-9b7d02855f59)

I can't seems to recreate this issue. Can you probably describe the steps to recreate the issue as linked issue is not helpful either

**Comment by stevejburge** [comment]
@ojopaul It doesn't happen with Tags because there's no default. That's probably why we missed it.

It does happen when merging Categories or any taxonomy with a default term.

When I merge 2 Categories, the posts with those terms now also have the "Uncategorized" category.

**Comment by stevejburge** [comment]
Report from a user that this isn't solved in 3.10

I can confirm in my testing

**Comment by ojopaul** [comment]
@stevejburge Can you send the staging site where you were able to replicate the issue after the fixes?

**Comment by stevejburge** [comment]
@ojopaul OK, I can't recreate it now. Will leave in case there's more reports
