### ISSUE TITLE
Add "Count" column on the "Terms" page

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1757]
Now we have the "Posts" screen, can we bring back the "Count" column on the "Terms" page?

**Comment by ojopaul** [comment]
Having the Posts screen doesn't solve the incorrect counts issue since that's why you asked it to be removed @stevejburge

**Comment by stevejburge** [comment]
@ojopaul I think this should make the "Count" much better as we can show posts from all post types?

**Comment by ojopaul** [comment]
I'm only reminding you it doesn't solve the count issue.

So, we can add it and link to our Posts screen if that's what you mean.

@stevejburge

**Comment by stevejburge** [comment]
Thanks @ojopaul. We can live with problems from fake data.

Let's give this a try and see how accurate the data is.

**Comment by ojopaul** [comment]
@stevejburge I'm not in support of making query to count posts for every time, It'll be problematic in the long run and website performance in general.

If we can deal with inaccurate data which could be the reason for your initial reported problem, then we should go with WordPress Count that's optimized for every new posts added and not making count query to database for everytime the term load.

**Comment by stevejburge** [comment]
@ojopaul Yes, we can live with slightly inaccurate data.

The reason we can live with this is that we now have the "Posts" screen which will show the accurate result.

Previously the "Count" link did not go to a helpful result.

**Comment by ojopaul** [comment]
I didn't object that, I'm only clarifying we're returning what was removed without any addition that guarantee the count issue. 

So, will add it back @stevejburge
