### ISSUE TITLE
Fix Private/Public Taxonomies issue between Taxonomies and Posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1771]
Settings

<img width="589" alt="Screenshot 2023-08-07 at 12 40 14 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/423a944a-b85f-460c-9e7f-a63d0ae3255f">

The Authors taxonomy is showing:
<img width="689" alt="Screenshot 2023-08-07 at 12 41 08 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/64a9f5b5-f3d4-44d2-be50-ee1511d6b36a">

**Comment by ojopaul** [comment]
Is Author Taxonomy not a public Taxonomy?

Public Taxonomies are taxonomy you can access via `/wp-admin/edit-tags.php?taxonomy=taxonomy_name `or what's your expectation?

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul looking at this more, maybe it is "Authors" that is odd

On the "Taxonomies" screen it shows as Private

**Comment by ojopaul** [comment]
@stevejburge  My initial assumption was wrong. Public and Private Taxonomies settings is not same as Show in menu which determine if a Taxonomy show up in menu.

So, I've made a fix for this as truly, Authors is private Taxonomy.
