### ISSUE TITLE
Suggest Terms / Dandelion not adding new terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1787]
At the moment, you can use the "Suggest Term" box to create new term ideas with Dandelion

However, they are not added to the post when you click on them:

<img width="1414" alt="Screenshot 2023-08-15 at 10 51 01 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/20a9df94-ef89-4d54-b54f-f3cbfe57f723">

**Comment by ojopaul** [comment]
@stevejburge I just tested this and everything works fine. Can you help with a staging site that has this issue?

**Comment by stevejburge** [comment]
@ojopaul Also something I can't recreate any longer. I'll close this for now
