### ISSUE TITLE
Allow users to have more than one taxonomy for "Suggest Terms"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1788]
We had some UI issues with users around "Suggest Terms"

Can we allow them to select multiple taxonomies?
<img width="861" alt="Screenshot 2023-08-15 at 10 58 26 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/f8c757b2-d569-4830-ac9c-d00e3fb8c0f9">

We could provide filters like for the metabox. 
<img width="403" alt="Screenshot 2023-08-15 at 10 59 46 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/eaecd9f5-dbf7-484a-89ff-5bb3f2899d2f">

**Comment by stevejburge** [comment]
This selection isn't working in my testing. Whatever is selected in the admin area, these 3 always appear:
![Uploading Screenshot 2023-09-21 at 12.18.37 PM.png…]()

**Comment by ojopaul** [comment]
@stevejburge The taxonomy doesn't apply to Click Term but Suggest Term or you didn't see the filter in Suggest Term?

Fron On set, that Click Term give options to search and select Taxonomy while Suggest Term Load term from local (default to selected terms which is now multiple from single option)

**Comment by stevejburge** [comment]
My mistake. I'm closing this
