### ISSUE TITLE
Possible different way for Suggest Terms to behave

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1798]
From a customer: they would like to disable the way that TaxoPress auto-scrolls up to the metabox.

The second item in the video is covered in this issue: https://github.com/TaxoPress/TaxoPress/issues/1796

https://drive.google.com/file/d/12NQRtLPfF7F_s_xcXJGE7jmhUwaMLGbZ/view?usp=drive_link

**Comment by ojopaul** [comment]
@stevejburge That's exactly what i warned against in https://github.com/TaxoPress/TaxoPress/issues/1654#issuecomment-1658058629

We end up adding problem for users while trying to fix issue that doesn't exist
