### ISSUE TITLE
Add a Pro upgrade message for exceptions in Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1807]
Related to https://github.com/TaxoPress/TaxoPress/issues/1806

Let's add a Pro upgrade message:
![Screenshot 2023-09-08 at 10 27 48 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/f6add46f-817c-4767-b556-dafd7bc522f0)

**Comment by ojopaul** [comment]
@stevejburge what should be the upgrade message?

**Comment by stevejburge** [comment]
We can make it like this box:
<img width="1016" alt="Screenshot 2023-09-18 at 10 10 14 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/f07af60e-5762-4825-bac3-8bebb021defd">

The message:
"TaxoPress Pro allows you complete control over where Auto Links are added. You can choose to skip any elements or characters that appear in your content."
