### ISSUE TITLE
Adding AI to the TaxoPress plugin

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1810]
Here's my current thinking about AI. I've gone back-and-forth a few times on this (do we need a separate plugin?) and am still not 100% sure. This is tricky and will require some careful thought as we see the other changes that will come from this first change.

I think we should start with new link called "TaxoPress AI" to control AI integrations. It could look like this:

![ai](https://github.com/TaxoPress/TaxoPress/assets/3868028/7361416e-c77f-49da-9b16-17237b9a13a4)

**Comment by stevejburge** [comment]
Then we add OpenAI and IBM Watson here:
<img width="879" alt="Screenshot 2023-09-25 at 12 07 39 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/c658095f-c09d-4204-b36d-46b6de65cfd4">
<img width="750" alt="Screenshot 2023-09-25 at 12 06 58 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/37dfb955-3d08-4b7f-a957-78c87c5fe5bd">

**Comment by stevejburge** [comment]
This screen will be for Pro users. For Free users, we can do this:
<img width="1429" alt="Screenshot 2023-09-25 at 12 19 59 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/163c9eb5-fdad-43df-bd37-8ee5955f3227">

**Comment by ojopaul** [comment]
@stevejburge TaxoPress AI screen will be Pro only?

**Comment by stevejburge** [comment]
Yes, please. Pro only with a promo screen for Free
