### ISSUE TITLE
Suggest Terms box is open

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1833]
Current version:
<img width="747" alt="Screenshot 2023-09-21 at 12 20 00 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/ddd43b6d-0a51-495a-a7bd-ca06caaebd8c">

New beta:
<img width="967" alt="Screenshot 2023-09-21 at 12 19 14 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/d6be1ce0-567b-4be4-bdea-9fa6aa1076d0">

**Comment by ojopaul** [comment]
@stevejburge I can't replicate this. Can you send the testing site on slack? Another javascript error could be causing code execution failure
