### ISSUE TITLE
Text change for welcome

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1838]
If we're going to show this screen just once, let's say:

"Welcome to TaxoPress, the WordPress taxonomy plugin"

<img width="1218" alt="Screenshot 2023-09-22 at 8 37 56 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/ff721288-1772-4523-b89c-7014759e02b8">

**Comment by ojopaul** [comment]
@stevejburge We can always have the text on the screen if that's the requirement.

I think I misread it due to the way the issue was created linking it to redirecting user on first install

**Comment by stevejburge** [comment]
No problem. I think a one-time welcome message is a good idea
