### ISSUE TITLE
Make Suggest Terms metaboxes matche

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1839]
Can we do a quick UI update to make the two Suggest Terms metaboxes match

For example, update text:

<img width="1136" alt="Screenshot 2023-09-22 at 8 57 10 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/d2c54051-7301-4145-9f97-d50d83b0002a">

Drop the italics and use same font style and text as the bottom metabox:

<img width="440" alt="Screenshot 2023-09-22 at 9 01 01 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/386366db-cbb6-423d-a1ee-4f5d1ea2018e">

<img width="166" alt="Screenshot 2023-09-22 at 9 01 47 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/1663fea8-a53c-44b9-b8f3-c215ea1ecbdb">

Use the same border and text: "Click terms to add them to this post"
<img width="484" alt="Screenshot 2023-09-22 at 9 03 28 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/8ddf52de-81a0-4398-8cee-a32fd05af833">

**Comment by ojopaul** [comment]
> For the records, suggest term metabox title is coming from the suggest term title itself which serves as a means to identify where the metabox is coming from especially when user has manu suggest terms
> 
> ![source](https://github.com/TaxoPress/TaxoPress/assets/92122385/f5a21081-eb90-4195-a9c3-a7588f449134)
>

**Comment by stevejburge** [comment]
Let's revisit this when we make the AI changes
