### ISSUE TITLE
Terms not displayed when using DESC ordering with numerical terms

### ISSUE THREAD

**Issue by onkstudio** [TaxoPress/TaxoPress#1859]
https://github.com/TaxoPress/TaxoPress/blob/6f8fbd358845bd8c0c761f539448da599d16374b/inc/class.client.tagcloud.php#L233C36-L233C36

When using numerical terms for a taxonomy (for example years : 2021, 2022, 2023...), if you choose to display them in DESCENDING order (so 2023, 2022, 2021...), the terms are not displayed on front office.

To solve this, you have to add a boolean TRUE as second parameter of the array_reverse function in file /inc/class.client.tagcloud.php on line 233 :

if ( $order == 'desc' && $orderby != 'random' ) {
    $counts = array_reverse( $counts, TRUE);
}

This keeps numerical keys of the array.

**Comment by stevejburge** [comment]
Thanks for this @onkstudio. We'll take a close look
