### ISSUE TITLE
Consider a name change for "Suggest Terms" and "Auto Terms"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1864]
"Suggest Terms" and "Auto Terms" are closely related to the new "TaxoPress AI" feature

I think it may be worth considering a name change to reflect that. One customer we've tested with did not see the relation at all.

Here's an idea for a new approach to the menus:

Suggest Terms = AI Suggestions
Auto Terms = Bulk AI (this name could be better)

This screenshot also adds lines to divide the features into four parts ... Admin / Frontend / AI / Settings

![Screenshot 2023-10-12 at 9 00 14 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/8188d575-3b52-4382-9602-43156b06577f)

**Comment by reekes** [comment]
I use auto terms, but I have not and have no plan to use the AI Suggested terms.

**Comment by stevejburge** [comment]
Thanks @reekes 

In the last launch of TaxoPress we changed "Suggested Terms" to the new "Suggest Existing Features" in the metabox.

The name change will probably be to "Auto Terms". We'll improve that feature focusing on the scheduling and the "Existing Content" feature https://github.com/TaxoPress/TaxoPress/issues/1909
