### ISSUE TITLE
Remove unused APIs and fix links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#187]
- OpenCalais: new link https://developers.refinitiv.com/en/api-catalog/open-perm-id/intelligent-tagging-restful-api/documentation
- AlchemyAPI: closed
- Zemanta: closed
- Dandelion - Entity Extraction API - ID (deprecated): we can remove
- Dandelion - Entity Extraction API - Key (deprecated): we can remove
- Proxem: we can remove

<img width="613" alt="Screen Shot 2021-02-23 at 1 53 20 PM" src="https://user-images.githubusercontent.com/3868028/108892975-8802b380-75de-11eb-8c57-f0972b15dac1.png">

**Comment by Vidyut** [comment]
Maybe replace with new entity APIs available? Google? Watson? TextRazor? Others?

**Comment by stevejburge** [comment]
Yes, after removing what doesn't work, we'll need to research some new options
