### ISSUE TITLE
User access

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1880]
If I'm logged in as an Author, I get this in the metabox.

Which user roles can use the metabox?

<img width="1386" alt="Screenshot 2023-10-18 at 9 22 11 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/4ad861a7-6262-411a-b2b4-432e5b3e22eb">

**Comment by ojopaul** [comment]
User that has the capability to manage TaxoPress. @stevejburge

**Comment by ojopaul** [comment]
I'll update the metabox to reflect that

**Comment by stevejburge** [comment]
@ojopaul Thanks. 

Do we need two different levels of access here?

1. Use the metabox
2. Manage TaxoPress
