### ISSUE TITLE
Add "Select All" and "Deselect All Toggle to TaxoPress AI tags

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1906]
I think would be useful to offer a "Add All Terms" and also a "Remove All Terms" button on these screens.

If there 100+ suggested terms, it would take some time to click each one

![Screenshot 2023-10-23 at 1 43 08 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/3302c9ac-7829-4774-b29e-27be7351e96d)

**Comment by ojopaul** [comment]
So, we should add 2 more buttons to that screen, right?

I'm still wondering if this won't lead to the possibility of mistakenly Adding or Remove all Post terms while trying to save selected changes.

Won't it be better to simply add "Select All" and "Deselect All" above the tags that are not in the same place as the Update Tags button?

Also, are we adding them to the Metabox area too? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul You're right ... "Select All" and "Deselect All" is a better idea
