### ISSUE TITLE
Return Mass Edit Terms from legacy to dashboard

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1920]
I wonder if it might be best to bring this back? People have been asking about it.

And we could use it for people to quickly add synonyms and more

<img width="329" alt="Screenshot 2023-10-25 at 3 50 16 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/a288e24c-18a4-4b34-a9e7-768a74bbcb5b">

**Comment by ojopaul** [comment]
> And we could use it for people to quickly add synonyms and more

Can you elaborate on this? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul So there is a bug with the menu in the latest release.

Perhaps we should add it back. 

We disabled it as a test, and already 2 people have asked for it to be added back. I think there may be useful improvements we can make, such as allowing users to add synonyms quickly via this screen
