### ISSUE TITLE
Only scanning the title in WooCommerce products

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1922]
If you use TaxoPress AI in WooCommerce, it only seems to scan the title

<img width="1177" alt="Screenshot 2023-10-26 at 11 05 01 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/53eac052-88ef-42f4-ac5c-0cd7ae11dae6">

**Comment by ojopaul** [comment]
@stevejburge TaxoPress by default scan Post Title and Content. Do you want us to add specific fields or so?

**Comment by ojopaul** [comment]
@stevejburge Isn't Description the same as Post Content?

**Comment by stevejburge** [comment]
@ojopaul Sorry, bad screenshot. Here's a couple of better ones showing the issue:
![Screenshot 2023-10-30 at 11 25 19 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/6039cd21-5a4c-4aa9-b8ce-916dca4d95a5)
![Screenshot 2023-10-30 at 11 25 27 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/76d9e930-9a46-418a-8e22-c311211ad588)

**Comment by ojopaul** [comment]
@stevejburge How did you confirm those suggestions are from the Title and not the content?

**Comment by stevejburge** [comment]
@ojopaul OK, let's close this for now and circle back if we get any user reports
