### ISSUE TITLE
Allow metabox to default to a taxonomy, or taxonomies

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1923]
Could we allow users to choose a taxonomy to display automatically?

Maybe in Settings > TaxoPress AI they can choose which taxonomies appear in the filter

Feedback here: https://secure.helpscout.net/conversation/2403305376/212103?folderId=4410092
![Screenshot 2023-10-27 at 3 23 13 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/77382e8d-a970-463b-9160-420b48112377)

**Comment by stevejburge** [comment]
WooCommerce is a good example of why we should allow users to disable taxonomies. Perhaps we only show "public" taxonomies by default?
![Screenshot 2023-10-30 at 11 27 02 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/754e1f6c-f79f-4c4d-865e-aecc0c50da77)

**Comment by stevejburge** [comment]
@ojopaul Sorry, two parts of the question:

1. Choose a default taxonomy
2. Choose taxonomies that show in the filter

**Comment by ojopaul** [comment]
I think we're overcomplicating development for ourselves with all these over-exhaustive settings over a single control that depends on one another.

I don't see the use for the Taxonomies Filter.

**Comment by stevejburge** [comment]
@ojopaul OK, I'm trying to interpret customer feedback here. Can we start with just a default option?
