### ISSUE TITLE
Cannot bulk edit

### ISSUE THREAD

**Issue by reekes** [TaxoPress/TaxoPress#1925]
## Expected Behavior

Attempting to bulk edit fails with warning messages from PHP, version 7.4.33

## Current Behavior

These errors are written to the admin page.

Warning: preg_match(): Unknown modifier 'R' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

Warning: preg_match(): Unknown modifier 'I' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

Warning: preg_match(): Unknown modifier 'R' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

Warning: preg_match(): Unknown modifier 'I' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

Warning: Cannot modify header information - headers already sent by (output started at /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php:567) in /home/customer/www/my.domain/public_html/wp-includes/pluggable.php on line 1435

## Possible Solution

None, bulk edit is broken

## Steps to Reproduce (for bugs)

1. Select a few custom posts. Not sure if CPT is required, but it's the only posts I have.
2. Select Bulk Edit
3. Attempt to change author or the category 

## Context

Loss of an important feature for managing thousands of posts

## Your Environment

* Version used: latest of everything

**Comment by stevejburge** [comment]
@reekes I don't see that in our testing on 7.4.

Could you share a screenshot?

**Comment by reekes** [comment]
I select a few posts.

![image](https://github.com/TaxoPress/TaxoPress/assets/18753948/da198526-1de1-43d6-89a8-e5cf1ae6e138)

Then click Buld Edit and apply.

![image](https://github.com/TaxoPress/TaxoPress/assets/18753948/c4826bfe-1c5a-4549-b3a5-8449e5ece749)

That produces this. It wipes everything on the WordPress page, completely replacing the entire contents of the browser page with these PHP errors.

![image](https://github.com/TaxoPress/TaxoPress/assets/18753948/70ac094d-7a54-419c-be59-619ea8c5a41e)

**Comment by stevejburge** [comment]
Thanks @reekes. You mention CPTs. Is this "Posts" screen being modified by something like the Admin Columns plugin?

**Comment by reekes** [comment]
I do use Admin Columns. I've paid for it, and have used it for years.
Even if I deactivate it, I still get the error.
I also tried to deactivate several other plugins that might potentially create a problem. Nothing yet has stopped these errors.
It looks like PHP bugs/errors to me.

**Comment by stevejburge** [comment]
@reekes Some of these issues might be best off handled via our support ticket system. We've not had this reported by any other users. This may be a situation where we need to check your specific site

**Comment by reekes** [comment]
we can close this, I found the problem, I'm going to open a new issue regarding the PHP errors
