### ISSUE TITLE
Default choices for TaxoPress AI Preview

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1930]
When I installed TaxoPress on a new site and went to "TaxoPress AI", it took me here:
<img width="1322" alt="Screenshot 2023-10-30 at 7 58 12 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/8b6250c8-cc08-4b5d-ab9d-954ce02d2ba2">

Is there a way we can show users something like this for their first impression?
<img width="1227" alt="Screenshot 2023-10-30 at 7 59 17 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/81bdb248-98e0-4c31-990f-232529c0963c">

**Comment by ojopaul** [comment]
@stevejburge Do you mean we should pre-select the first post and show the tags?

**Comment by stevejburge** [comment]
@ojopaul Yes, if possible. Pre-select "Manage Post Terms" and the first post with Tags

**Comment by ojopaul** [comment]
Make sense @stevejburge
