### ISSUE TITLE
Add maximum and minimum controls to OpenAI settings

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1948]
Is it possible to add a settings to make OpenAI add more terms. We could consider controls for IBM also

Here's a default example with OpenAI and Spanish
<img width="989" alt="Screenshot 2023-11-13 at 12 36 52 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/8666f6d3-e8fb-4248-9af7-0fc45781bb92">

And here's IBM:
<img width="1185" alt="Screenshot 2023-11-13 at 12 45 13 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/9155d909-4053-459e-b869-63561d8d4727">

**Comment by ojopaul** [comment]
@stevejburge What type of control do you think this will be for AI that works with prompt? Telling it to generate minimum of let say 50 tags?

Do you think that's efficient for every content? 

Here's our current prompt: `Extract tags from the following content: '{content}. Tags:'.` Do you think it'll be efficient to add let say minimum of 50 tags?

Won't that produce inefficient or inaccurate results where tags doesn't even match content for short content?

If we want a settings, we could improve the prompt to something like `Extract minimum of 50 tags from the following content: '{content}'. Tags:` but I'm not 100% sure of the efficiency as I tried different prompts and tests before getting result that works.

**Comment by stevejburge** [comment]
Thanks @ojopaul. Yes, it seems like OpenAI can be unreliable. Let's do some practical testing
