### ISSUE TITLE
Better support for punctuation

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1955]
In TaxoPress, users are having problems with a variety of punctuation

Here's one example, where the period and dashes are causing issues.

> Engine Capacity: 1.4i, 1.4CRDi, 3.0TDi 
> Year ranges: 2010-, 2004-2010, 08-12, 99-
https://secure.helpscout.net/conversation/2376357425/210741?folderId=4410099

**Comment by stevejburge** [comment]
One having issues with hyphens
https://secure.helpscout.net/conversation/2432079833/213497/

**Comment by ojopaul** [comment]
@stevejburge Do you mind setting up a staging website with this issue for me?

**Comment by stevejburge** [comment]
Sure, I'll do that and come up with a more detailed proposal

**Comment by ojopaul** [comment]
@stevejburge To be sincere, the initial issue lacks details and if not for the new info after my comments, I was thinking it's autolinks issue.

**Comment by ojopaul** [comment]
@stevejburge Now from your screenshot, if you have a term 1.4i and it's not in the content, how do you want Suggest Existing Terms to suggest the synonyms when the parent term is not in the content? Same goes for Synonyms

**Comment by ojopaul** [comment]
This suggestion will solve this problem https://github.com/TaxoPress/TaxoPress/issues/1736
