### ISSUE TITLE
Add role visibility settings for metabox

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1957]
We've had quite a few request like tis:

> It's possible to avoid users to create new tags from gutenberg editor? I like only admin users to be able to create new tags. Other users only could use existing tags

Here's one way to solve this:

- Can we remove the default metaboxes for taxonomies?
- Can we look into ways that users can create terms in our metabox?

.

**Comment by stevejburge** [comment]
One more customer request for this. They want to avoid using the normal "Tags" and "Categories" boxes in the sidebar.

**Comment by stevejburge** [comment]
One more:

"We do not want to allow these users to change or edit categories (so that the structure of site content categories is not accidently broken) but we do want to enable use of the Taxopress AI box for these editors."

**Comment by ojopaul** [comment]
@stevejburge To sum it all, we should add a custom capability for TaxoPress AI metabox so it only show up for users with the capability?

**Comment by stevejburge** [comment]
@ojopaul Yes, please. The problem comes with creating new tags. If you give a user "manage_categories", then they can add new tags.

**Comment by ojopaul** [comment]
@stevejburge Where should I put this settings?

![settings](https://github.com/user-attachments/assets/cc46bc98-8088-4f6f-83c9-728641c312c1)

**Comment by stevejburge** [comment]
Maybe a new “Capabilities” tab?

**Comment by ojopaul** [comment]
Sorry, I wanted to make that comment on https://github.com/TaxoPress/TaxoPress/issues/2044 as Capabilities doesn't require settings.

**Comment by stevejburge** [comment]
@ojopaul I am thinking that we should have setting for this, but it requires another change so let's postpone until the next milestone

**Comment by stevejburge** [comment]
Let's put this under a new "Metaboxes" tab
