### ISSUE TITLE
Possible improvements for when TaxoPress posts are saved

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1958]
Details here:
https://wordpress.org/support/topic/problem-with-wonderpush-plugin/

> the post is briefly published upon saving it as draft. As proof, here’s the code that sends the notification:
> 
>     if (!empty($post)      && $new_status === "publish"      && get_post_status($post->ID) === "publish"      && $post->post_type !== 'page') {      self::send_notification_on_post($new_status, $old_status, $post);    }
> 
> It is called by the transition_post_status hook and demonstrates that the post indeed reaches the published status.

**Comment by ojopaul** [comment]
@stevejburge I've reviewed the plugin and can't find any function that publish post when save as draft or other status.

If you search for `post_status` or `wp_update_post` or `wp_insert_post` in TaxoPress codebase, you'll see none of the usage is related to publishing a post or changing post status.
- https://github.com/search?q=repo%3ATaxoPress%2FTaxoPress%20post_status&type=code
- https://github.com/search?q=repo%3ATaxoPress%2FTaxoPress+wp_update_post&type=code
- https://github.com/search?q=repo%3ATaxoPress%2FTaxoPress%20wp_insert_post&type=code

Also, the code mentioned in the support is not helpful for us as it's not TaxoPress code but only demonstrating how they're sending notification.

**Comment by stevejburge** [comment]
OK, thanks @ojopaul. The user can follow up if this remains an issue for them
