### ISSUE TITLE
Remove linked tags relationship after the tag is deleted

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1959]
> I just stumbled upon sth that needs fixing: If a term is added somewhere in "Linked Terms" and the tag is deleted globally, Taxopress creates the tag again. I have added a "Linked Term" somewhere by accident and tried to fix this by deleting its tag to later recreate it. Unfortunately this is not possible.

https://secure.helpscout.net/conversation/2409725433/212562?folderId=4410099

**Comment by ojopaul** [comment]
@stevejburge Linked terms doesn't have any feature that's create tags. Not sure there's away the described bug could be from Linked terms.

Did you confirm this issue?

**Comment by stevejburge** [comment]
Yes, here's how it works

![Screenshot 2024-01-30 at 11 34 53 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/928a1485-2ae3-4cf1-827b-515b60b2bac4)

**Comment by ojopaul** [comment]
Then I think it's wrong to say deleted term is been created or you mean it's been added back when you edit Banana and remove the Apple? @stevejburge

**Comment by stevejburge** [comment]
yes, the title of this issue is incorrect

The problem is that "Linked Terms" retains information about deleted terms
