### ISSUE TITLE
Update the error message when adding tags that are already a synonym

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1964]
This comes from a customer. I've added "ABC" as a synonym:
![Screenshot 2024-01-17 at 10 02 56 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/afb0289c-3325-4e2b-bfb9-c3afb7a1eb92)

If I try to add "ABC" as a Tag, this message isn't clear:
![Screenshot 2024-01-17 at 10 03 23 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/ed861cbf-5c1d-4e0a-838e-957a93671e98)

**Comment by ojopaul** [comment]
@stevejburge What should the new message be?

**Comment by stevejburge** [comment]
"ABC can't be added as a tag because ABC is already used as a synonym."
