### ISSUE TITLE
Add the "Whole Words" feature to TaxoPress AI

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1971]
From a customer: 
"For example, if my pst it has the words 'healthcare' and 'Yeovil' somewhere in the description, then it will not assign it to a category titled 'healthcare jobs in Yeovil' ?"

Could we fix this for the customer by adding he "Whole Words" feature to TaxoPress AI?

**Comment by ojopaul** [comment]
@stevejburge Where do you think this fit in TaxoPress AI? TaxoPress AI doesn't add terms automatically or you mean something else?

**Comment by stevejburge** [comment]
@ojopaul I think this user was using "Suggest Existing Terms"

**Comment by ojopaul** [comment]
@stevejburge So, how will this work with TaxoPress AI. I don't really understand that part

**Comment by stevejburge** [comment]
Could it be an additional setting in the "Suggest Existing Terms" area?
![Screenshot 2024-01-30 at 12 19 00 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/2685074a-7a92-4d0e-8b0f-508813f26da4)

I guess we need to think this through more? There are other settings we could bring over from Auto Terms
![Screenshot 2024-01-30 at 12 19 37 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/6f2417c1-4644-4acf-8fad-662170489f53)

**Comment by ojopaul** [comment]
I really don't understand how this is supposed to work yet.

Suggest Existing Terms of TaxoPress AI suggest terms from content and not add them to th content.

In this case, what do you think the settings will work? By not suggesting terms if it's not found as an whole word in the content? @stevejburge

**Comment by stevejburge** [comment]
With Suggest Terms, the user is hoping that is it will suggest "healthcare jobs in Yeovil" if the words "healthcare" or "Yeovil" are in the content. So he wants a partial match.

**Comment by ojopaul** [comment]
@stevejburge The description says below and the point is, TaxoPress AI doesn't assign tags.

"For example, if my post it has the words 'healthcare' and 'Yeovil' somewhere in the description, then it will not assign it to a category titled 'healthcare jobs in Yeovil' ?"

So, I'm wondering if you're misreading the customer need?

**Comment by stevejburge** [comment]
Sorry, not assign but suggest

**Comment by ojopaul** [comment]
@stevejburge is this correct?
Add new whole word settings to Suggest term of TaxoPress AI that when checked, only suggest terms that are whole word as that's how whole Word feature works.

For example, if you have "healthcare" in your content, "healthcare jobs in Yeovil"  tag will not be suggested @stevejburge
