### ISSUE TITLE
Add button to fill in Linked Terms for existing posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1988]
Can we add a button that allows admins to use Linked Terms on existing posts.

1. Create the Linked Terms
2. Click the button and the extra terms are added to existing posts

**Comment by ojopaul** [comment]
I really don't understand, where will this be and what are the button doing? @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Good question. Maybe it's one the tags editing screen?
![Screenshot 2024-03-12 at 10 28 07 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/e2c0fb0d-7e11-42d5-8de3-85f966d6afdb)

**Comment by ojopaul** [comment]
@stevejburge What'll the button do? and can you address both buttons in your response?
- Create the Linked Terms
- Click the button and the extra terms are added to existing posts
Also, will the 2 buttons fit in that place?

**Comment by stevejburge** [comment]
@ojopaul 

No, it won't create Linked Terms. That will still be done with the "Save" button.

Perhaps this option will only appear after the Linked Terms are created?

For example, a site has 100 posts. A user then decides to start using TaxoPress. They can connect "Apple" as the main term and "Banana" as the linked term. This button will scan the 100 old posts and add "Banana" whenever it finds "Apple".

**Comment by ojopaul** [comment]
That make sense, I get it now @stevejburge
