### ISSUE TITLE
Move Existing Content to new menu?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2022]
Should we break this out into a new screen? It gets lost inside the main Auto Terms screen:

![Screenshot 2024-04-16 at 1 53 03 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/d4d8f361-d542-4d7e-9851-add73db672ad)

We can also improve the design of this area which is very limited:
![Screenshot 2024-04-15 at 10 22 31 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/75de355d-0c7a-4059-9dd2-db8e5eed6b6e)

**Comment by ojopaul** [comment]
@stevejburge Does this really worth us adding additional new menu with all the menus we currently have?

**Comment by stevejburge** [comment]
OK, let's skip the new menu link and focus on improving the design

**Comment by ojopaul** [comment]
Sorry @stevejburge I'm really out of ideas on how to improve this. Do you have a suggestion?

**Comment by stevejburge** [comment]
@ojopaul Can we start just by moving this out of Auto Terms and into its own screen?

**Comment by ojopaul** [comment]
Okay, I think we can go with that @stevejburge

**Comment by stevejburge** [comment]
Thanks. From there we can make changes. Basically this feature deserves a lot more room (and information for users)
