### ISSUE TITLE
Disable Media Tags by default

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2036]
I think this feature is more trouble than it's worth, because it's so limited.

Let's allow people to enable Media Tags, but disable them by default

**Comment by ojopaul** [comment]
@stevejburge Where should I add this settings?
![se](https://github.com/user-attachments/assets/e5cda981-34a0-45f3-84ae-1c4f3a8ca98e)

**Comment by stevejburge** [comment]
@ojopaul Maybe we keep it in the Taxonomies list, but disabled by default?

**Comment by ojopaul** [comment]
Oh, didn't know that's what you mean. Got it now @stevejburge

**Comment by ojopaul** [comment]
@stevejburge Should this be for all or new installation?

**Comment by stevejburge** [comment]
Just new installs please
