### ISSUE TITLE
Auto Links exclusions not working on <p> elements

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2040]
https://secure.helpscout.net/conversation/2585988378/222248?folderId=4410099

**Comment by stevejburge** [comment]
One more report of this bug
![Screenshot 2024-06-19 at 11 58 23 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/71c76f85-e8c9-4185-b7d5-89cbc7acd427)

**Comment by ojopaul** [comment]
@stevejburge I'm not able to grab the conversation flow, do you mind updating the real issue here?

**Comment by stevejburge** [comment]
@ojopaul Basically this option is not working: "Prevent Auto Links inside classes or IDs"

**Comment by ojopaul** [comment]
@stevejburge Do you have a testing site? If it's in that thread, can you copy it to the top and tag me as it's working in my test
