### ISSUE TITLE
Update Linked Terms description

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2047]
One customer is requesting the ability to make Linked Terms either 1-way or 2-way

1-way: When "All Counties" is added, the other terms are added
2-way: When any of these terms is added, the other terms are added

![Screenshot 2024-06-17 at 12 35 06 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/ffc26e72-aaa8-499a-962f-d3860c7d56df)

**Comment by ojopaul** [comment]
@stevejburge I think we should simply decide if it's one or or not directly, it'll be complicated making it a settings.

**Comment by stevejburge** [comment]
OK, thanks. Let's leave it as it is. 

We can just update the text description to make this clearer:

"When the main term or any Linked Term is added to a post, all the other terms will be added also."
