### ISSUE TITLE
Design change for existing content message

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2092]
Should we use the dashed design we use elsewhere?
![Screenshot 2024-08-01 at 11 36 37 AM](https://github.com/user-attachments/assets/b052997f-40de-4968-b1d6-44c21060ade2)

Here's that dashed design. If we don't use the dashes, maybe use the same padding / spacing?
![Screenshot 2024-08-01 at 11 36 28 AM](https://github.com/user-attachments/assets/64eea07d-265a-4671-977c-a97e172b0e80)

**Comment by ojopaul** [comment]
@stevejburge Maybe we only display posts that are auto termed only instead of all posts that are scanned?

**Comment by stevejburge** [comment]
@ojopaul Or perhaps a negative message: "No terms added."?

**Comment by ojopaul** [comment]
Okay, that'll work... @stevejburge
