### ISSUE TITLE
Make Linked Terms 1-way or 2-way

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2099]
We've had several customers raise this with us and it's becoming a key request. Customers requesting the ability to make Linked Terms either 1-way or 2-way

1-way: When "All Counties" is added, the other terms are added
2-way: When any of these terms is added, the other terms are added

![Screenshot 2024-06-17 at 12 35 06 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/ffc26e72-aaa8-499a-962f-d3860c7d56df)

Could we leave it as 2-way by default, but allow users to make it 1-way as an option? Possible options:
- 2-way relationship (the current default)
- Add the primary term, get the secondary term
- Add the secondary term, get the primary term

**Comment by KlausReichert** [comment]
love to see this as it will expand the use of the current implementation bigly

**Comment by stevejburge** [comment]
Thanks. We've had enough user feedback on this to know it's an important improvement
