### ISSUE TITLE
Issue with < > in a paragraph

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2118]
Try writing this into a paragraph block:

<ul><li>nothing here</li></ul>

![Screenshot 2024-08-08 at 12 32 12 PM](https://github.com/user-attachments/assets/27764cb4-b371-4a89-9890-1596783d0c07)

If you edit this visually, Gutenberg will do this:
![Screenshot 2024-08-08 at 12 32 37 PM](https://github.com/user-attachments/assets/f4a2f021-85e2-452e-9cfa-068676c1b161)

If Auto Links are disabled, it will show like this:
![Screenshot 2024-08-08 at 12 35 24 PM](https://github.com/user-attachments/assets/baf37075-ddea-4a62-9245-eff8b906bed1)

If Auto Links are enabled and a link is before the code, it will show like this. The link works but the paragraph block disappears
![Screenshot 2024-08-08 at 12 35 51 PM](https://github.com/user-attachments/assets/5d0e4333-8992-4893-b046-83b34cdf566f)

**Comment by reekes** [comment]
FYI - when I did this with Auto Links enabled I got the paragraph, but the intended

![image](https://github.com/user-attachments/assets/adfa581d-7a1b-43f3-9734-62de0170021a)

tuned into...

![image](https://github.com/user-attachments/assets/698ad761-7d6b-4e95-b1d5-ab67bc7adedc)
