### ISSUE TITLE
Auto Links issues with Preformatted code

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2120]
Take this code:

<pre class="wp-block-preformatted"><code>&lt;table@{variables('styles').tableStyle}&gt;</code><br><code>&lt;thead&gt;</code><br><code>&lt;th@{variables('styles').headerStyle}&gt;Application ID&lt;/th</code><br><code>&lt;th@{variables('styles').headerStyle}&gt;Display Name&lt;/th</code><br><code>&lt;th@{variables('styles').headerStyle}&gt;Days until Expiration&lt;/th&gt;&lt;th@{variables('styles').headerStyle}&gt;Type&lt;/th&gt;&lt;th@{variables('styles').headerStyle}&gt;Expiration Date&lt;/th&gt;</code><br><code>&lt;/thead&gt;</code><br><code>&lt;tbody&gt;</code></pre>

Add it to a pre-formatted block:
![Screenshot 2024-08-08 at 12 49 08 PM](https://github.com/user-attachments/assets/48ff9b03-d79d-4e33-86f7-c7333db29517)

Here's what it looks like visually:
![Screenshot 2024-08-08 at 12 49 26 PM](https://github.com/user-attachments/assets/9c72b376-3b56-4d1c-99aa-f6b652666f7a)

And here's what it looks like on the frontend:
![Screenshot 2024-08-08 at 12 49 58 PM](https://github.com/user-attachments/assets/19587675-8b60-48d7-86c1-bf7101312190)

Now enable Auto Links and it looks like this:

![Screenshot 2024-08-08 at 12 50 33 PM](https://github.com/user-attachments/assets/4d7fdf3a-00d1-426a-b9ca-1570c2515edf)

Here's the new code:

```
<pre class="wp-block-preformatted"><code><table@{variables('styles').tableStyle}></code><br><code><thead></code><br><code><th@{variables('styles').headerStyle}>Application ID</th</code><br><code><th@{variables('styles').headerStyle}>Display Name</th</code><br><code><th@{variables('styles').headerStyle}>Days until Expiration</th><th@{variables('styles').headerStyle}>Type</th><th@{variables('styles').headerStyle}>Expiration Date</th></code><br><code></thead></code><br><code><tbody></code></pre>
</div>
```

**Comment by reekes** [comment]
This bug has been hard to narrow down and explain. Basically, I've got `<pre>` and `<code>` set to be ignored by Auto Linking. Yet, it's the contents within those tags gets corrupted.

I found this because my site has sample code for building web sites. The example text should appear as plain text on the front end, but it's getting parsed and then portions of the text are getting replaced by Auto Link. This then corrupts the final HTML at the front end, causing the page to be rendered incorrectly.

I can't tell if it's just one bug, or a combination of a few.

It may be related to https://github.com/TaxoPress/TaxoPress/issues/2118

**Comment by stevejburge** [comment]
Thanks @reekes. We really appreciate your help on this.

Yes, it's been tricky for us too. We've been trying to solve this issue-by-issue, but our thinking at the moment has changed. We're going to modify the processing order so that Auto Links runs much earlier. That should be available later week this in a dedicated release focused on Auto Links.

**Comment by ojopaul** [comment]
Thanks for the additional information, I've added a PR related to https://github.com/TaxoPress/TaxoPress/issues/2118 that fixes this issue and will send package for testing when milestone is completed

**Comment by reekes** [comment]
Not sure the other fix also fixes this one. I didn't see a merge to address this issue. I think they are related, just not sure it's the same problem.

How about sending me a build I can test? I can verify what has been fixed, and test if there's an open issues.

cc @stevejburge @ojopaul
