### ISSUE TITLE
Add "Save Settings" button to "Existing Content" page

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2137]
Can we add a "Save" button for these settings?
![books](https://github.com/user-attachments/assets/7ccbe4c4-f91d-4ab2-a875-587208c9d849)

**Comment by ojopaul** [comment]
@stevejburge Changes to the settings actually saved when you run Auto Term for content. The reason I didn't add extra save button is because it may seems useless since when you save, you'll want to run to test during the process which actually saves the settings again.

**Comment by stevejburge** [comment]
Thanks. Can we add a "Save" button just for UI purposes, please. People will be able to save when they want.
