### ISSUE TITLE
Remove Upgrade boxes from the "Exisiting Content" screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2138]
![Screenshot 2024-08-13 at 12 20 05 PM](https://github.com/user-attachments/assets/c6990b6c-5900-49c9-8a0d-8d18d2ac367d)

**Comment by stevejburge** [comment]
@ojopaul We can just remove them from this screen, please

**Comment by ojopaul** [comment]
Okay
