### ISSUE TITLE
Allow users to skip blocks in Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2148]
Can we provide a block setting and/or a shortcode to allow users to skip some content in Auto Links? This can be a Pro feature?

The shortcode could look like [skip_autolinks][/skip_autolinks]

The block setting could be a checkbox that appears under the "Advanced" tab
![Screenshot 2024-08-19 at 4 21 14 PM](https://github.com/user-attachments/assets/cb355088-7adf-40f0-bc28-c2c4d89f4862)

**Comment by ojopaul** [comment]
@stevejburge Is the current skip shortcode and block settings in Pro not working?

I'm not if it's even possible to add settings to third party blocks which I doubt is realistic.

I added settings to select Blocks and shortcode in Autolink exclusion which does exactly this, Is that not working?

**Comment by stevejburge** [comment]
Doh, sorry. We already have this coming in our 3.25 release
![Screenshot 2024-08-20 at 9 52 35 AM](https://github.com/user-attachments/assets/8688894d-c3fe-4234-ac70-3c4a4f01d4f3)
