### ISSUE TITLE
Add a new tab "When to Use", and move applicable settings to each subtabs

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2200]
I think people are unsure if Auto Terms is working when they edit content.

Can we add a new tab?

Label: When to Use
Choices: 
- When a Post is Saved or Updated
- Schedule
- Existing Content
- Metaboxes

Related: https://github.com/TaxoPress/TaxoPress/issues/2144

**Comment by ojopaul** [comment]
So @stevejburge , if in the settings, neither  Existing Content or Metaboxes is selected, that shows the metabox or existing content is useless?

Are we not ending up with many screens that depend on another and so on. Creating features that can't stand alone just like we did with TaxoPress AI not been able to be disabled then cos of Auto Term and Auto Link?
