### ISSUE TITLE
AI terms: Choose the case

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2201]
One user request: for AI-generated terms, can we force the terms to be:
- CapitalCase
- UpperCase
- LowerCase
- Left unchanged

They were finding lots of terms created as "tshirts" rather "TShirts", for example.

One more customer feedback on this:

> I've noticed on the auto-tagging that if the tag source is capitalised (e.g. at the start of a sentence or title), the tag is capitalised. Might be better if the tag was automatically put in lower case, unless it's a name (AI should be able to work that out…)

**Comment by ojopaul** [comment]
@stevejburge here's what I can guarantee from our end:
Capital: Tshirts
Upper: TSHIRTS
Lower: tshirts
Left unchanged: Well, this is whatever case we got.

So, I can guarantee the above from our end if we add settings for them but in case of **TShirts**, no way for us to really know the terms that'll need **PascalCase** without AI. The best option would be adding this to AI prompt **"return tags in PascalCase where applicable"** but the results is solely depends on the AI ability to understand and process prompt and we can't guarantee it 100% success for all generated tags.

So, in this case, is it not better to test and suggest prompt?
PascalCase: **"...return tags in PascalCase where applicable"** : This should return **TShirts**
camelCase: **"...return tags in camelCase where applicable"** : This should return **tShirts**
kebab-case : **"...return tags in kebab-case  where applicable"** : This should return **T-shirts**
Capital: **"...return tags in Tshirts where applicable"** : This should return **TShirts**
Upper: **"...return tags in Uppercase where applicable"** : This should return **TShirts**
Lower: **"...return tags in lowercase where applicable"** : This should return **TShirts**

**Comment by stevejburge** [comment]
OK, thanks. Perhaps we call this a documentation issue then?
