### ISSUE TITLE
Expand the "Exceptions" area to include new terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2205]
Request from a customer: can we add an option to block keywords from becoming *new* terms in Auto Terms

![Screenshot 2024-09-12 at 10 51 51 AM](https://github.com/user-attachments/assets/2880ca4f-b53a-4385-a8cf-75f087bc04a2)

**Comment by ojopaul** [comment]
@stevejburge This should already be working as that's an input you can entered keyword aside from selecting suggested terms

**Comment by stevejburge** [comment]
OK, thanks
