### ISSUE TITLE
New logo and banner for WordPress.org

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#221]
![banner-1544x500](https://user-images.githubusercontent.com/3868028/109203180-d6948700-7771-11eb-9b06-d6985e796780.png)

![icon-128x128](https://user-images.githubusercontent.com/3868028/109204795-c9789780-7773-11eb-8bcb-a980f50e6ab6.png)
![icon-256x256](https://user-images.githubusercontent.com/3868028/109204796-ca112e00-7773-11eb-8243-bb1fc8f8f58f.png)

**Comment by olatechpro** [comment]
@stevejburge , please provide replacement in this variations and attach as zip file.
[banners.zip](https://github.com/TaxoPress/taxopress/files/6045954/banners.zip)

**Comment by htmgarcia** [comment]
Hi @olatechpro,
I attach the files. We can skip svg and the rtl versions for now.
[banners.zip](https://github.com/TaxoPress/taxopress/files/6051614/banners.zip)

**Comment by olatechpro** [comment]
Added to assets for new release
