### ISSUE TITLE
Add support for more statuses in Auto Terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2246]
Currently Auto Terms doesn't support posts in the "Scheduled" status.

Can we add support for "Scheduled" and perhaps Draft and Pending Review?

![Screenshot 2024-10-08 at 1 24 35 PM](https://github.com/user-attachments/assets/defc9905-cb51-40cc-94fa-6804b912eaed)

**Comment by ojopaul** [comment]
@stevejburge Should we automatically include these in the "Add terms for unpublished content" or we should add a status dropdown to select statuses?
