### ISSUE TITLE
OpenAI producing sentence instead of individual terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2258]
I regularly see this type of results from OpenAI. Can we force them to produce separate terms?
![Screenshot 2024-10-11 at 3 15 42 PM](https://github.com/user-attachments/assets/2edba597-46d5-46e3-8851-f6b8ca3b116a)
![Screenshot 2024-10-11 at 3 15 53 PM](https://github.com/user-attachments/assets/b99f9798-cd86-4acf-96c2-55eeb0ff608c)
![1](https://github.com/user-attachments/assets/6b6367d5-3582-42d5-a8f4-9035cf5d8939)

**Comment by ojopaul** [comment]
This is actually a problem with OpenAI not been consistent but I think we can improve how we parse the response when it come in a single term like samples above and keep improving for every other reported issues till we have a perfect outcome.

@stevejburge Is this happening on the default prompt or you're using a custom prompt

**Comment by stevejburge** [comment]
@ojopaul Thanks. This was a custom prompt, but I believe I've also seen it with the default prompt

**Comment by stevejburge** [comment]
After testing more today, I think the problem happens more consistently with the gpt-40-mini model

**Comment by stevejburge** [comment]
One customer confirms this is fixed by choosing a new model
