### ISSUE TITLE
Figure out what to do with "Autocompletion with old input"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#229]
This feature is old and clunky:
![Screen Shot 2021-02-26 at 4 31 44 PM](https://user-images.githubusercontent.com/3868028/109357396-28134380-7850-11eb-8121-b00aca3ec826.png)
It produces this old dropdown:
![Screen Shot 2021-02-26 at 4 32 17 PM](https://user-images.githubusercontent.com/3868028/109357453-3bbeaa00-7850-11eb-8642-743fccd78b37.png)

But the "Click Tags" feature doesn't work with the new WordPress input:
![Screen Shot 2021-02-26 at 4 31 04 PM](https://user-images.githubusercontent.com/3868028/109357525-55f88800-7850-11eb-95a5-1d28ebcfbec9.png)

Maybe we do this:
- Fix "Click Tags" for the new input
- Move the old setting to the bottom of the Settings area, and disable it for new sites
- Hide it away with this settings:
![Screen Shot 2021-02-26 at 4 36 40 PM](https://user-images.githubusercontent.com/3868028/109357835-dd45fb80-7850-11eb-9f80-82b4361b8c7a.png)

**Comment by olatechpro** [comment]
Hi @stevejburge 
Just to be clear:

> But the "Click Tags" feature doesn't work with the new WordPress input:
You mean it doesn't work in gutenberg editor like classic editor

> Move the old setting to the bottom of the Settings area, and disable it for new sites
- By disable it for new sites, do you mean site with editor as gutenberg ?
- By disable, you mean it's still there but not selectable or clickable as option ?
- By move to Bottom of the Settings area, you mean as the last item in Settings > Features tab ?

> Hide it away with this settings
Can you explain this better ? Hide what away with type of input options (textarea, input) that's in Settings > Administration tab ?

**Comment by stevejburge** [comment]
Yes, that's correct. If you use the new "Tags" box, you can not use the "Click Tags" feature.

I think that's a good first step. Let's just make sure that we can use the new "Tags" metabox
