### ISSUE TITLE
Can "Manage Post Terms" load automatically

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2290]
Can the "Manage Post Terms" and "Show All Existing Terms" boxes automatically load the default selection (normally "Tags)?

![Screenshot 2024-10-28 at 1 22 27 PM](https://github.com/user-attachments/assets/2d3d9dd9-8be6-4eff-bb15-8bb3270ea07d)
![Screenshot 2024-10-28 at 3 09 51 PM](https://github.com/user-attachments/assets/d9ced6ec-2ebd-45ae-8532-91abb25ba80f)

**Comment by ojopaul** [comment]
Both "Manage Post Terms" and "Show All Existing Terms" are already loading tags on page load.

The only reason "Manage Post Terms" may be empty is if the post doesn't have any terms which happen mostly when creating new post @stevejburge
