### ISSUE TITLE
Missing translation strings in TaxoPress Pro

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2296]
![Shot1_TermsDisplay](https://github.com/user-attachments/assets/00e78d5d-c7e4-4c13-9a81-1ebfca6a6344)
![Shot2_CurrentPost](https://github.com/user-attachments/assets/f25d2361-3574-477d-bafa-df6b43d32a97)
![Shot3_RelatedPosts](https://github.com/user-attachments/assets/9adedc90-55cf-490e-b800-92c07b5200e1)
![Shot4-AutoLink](https://github.com/user-attachments/assets/e7559922-f6a3-4404-bdf1-c952dd1904c8)
![Shot5-AutoTerms](https://github.com/user-attachments/assets/609c2260-d9d2-484b-8f0a-635c0e06a79e)
![Shot6-Options-MetaboxLogin](https://github.com/user-attachments/assets/e5323664-4b0f-44d9-912d-5e5cf779feb1)
![Shot7-LinkedTerms](https://github.com/user-attachments/assets/cd1045fe-420e-449e-a978-704589620dcd)
![Shot8-Options-Licence](https://github.com/user-attachments/assets/6f37078d-ec13-45ac-96c0-150c4ebfbc05)

**Comment by ojopaul** [comment]
Will reflect from next translation
