### ISSUE TITLE
Media Tags are not appearing in the output of get_taxonomies()

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2298]
Media Tags are not appearing in the output of get_taxonomies() and that's causing error messages with some other plugins:
https://wordpress.org/support/topic/media_tag-taxonomy-not-defined-properly/

**Comment by ojopaul** [comment]
@stevejburge Have you confirm media tag is not disabled?

There's no reason for it not to appear if enabled as it's registered the normal way.

**Comment by stevejburge** [comment]
Yes, the user reports that it's active

**Comment by ojopaul** [comment]
Okay @stevejburge 

@Deji98 Let me know on slack if you're not able to debug this but you can give it a try first
