### ISSUE TITLE
Small wrapping issue for custom fields

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2322]
This is after adding edd_price and some other fields

![Screenshot 2024-11-05 at 9 57 28 AM](https://github.com/user-attachments/assets/c5c961c9-bfef-4124-8612-341d664232f9)

**Comment by ojopaul** [comment]
@stevejburge What browser is this?

**Comment by stevejburge** [comment]
Firefox on a Mac

**Comment by ojopaul** [comment]
Okay
