### ISSUE TITLE
Error message goes off the screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2334]
I'm testing the {post_terms} but OpenAI couldn't find any tags so reported this error
![Screenshot 2024-11-06 at 12 56 40 PM](https://github.com/user-attachments/assets/ec6c7a92-524e-46a4-a897-df9b0e9c5281)

**Comment by stevejburge** [comment]
One more
![Screenshot 2024-11-06 at 1 15 15 PM](https://github.com/user-attachments/assets/351e4179-93b2-4c8f-89d4-40be2d392617)

**Comment by ojopaul** [comment]
I'll fix the error but will like to say this happen because post doesn't have any tags and the prompt is probably asking to chose from lists of tags @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Sure. Can we just wrap the message?
