### ISSUE TITLE
Add OpenAI settings to exclude terms not in {post_terms} if used in custom prompt

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2335]
{post_terms} works sometimes but consistently produces new terms. I'll post back here with some detailed testing

**Comment by ojopaul** [comment]
@stevejburge Even though there's nothing I can do on this since it depends on command but when reporting issues related to OpenAI, always include the command you're using as different command produce different result.

**Comment by stevejburge** [comment]
Here's an example. 

I used this article: https://www.bbc.com/news/articles/c4gzd62g1r3o

I used this prompt
![Screenshot 2024-11-07 at 12 15 17 PM](https://github.com/user-attachments/assets/96cc92da-302e-4d3f-86cc-44ccd2f05238)

This was the result. The first 5 results are perfect, but it also suggested new terms
![Screenshot 2024-11-07 at 12 15 11 PM](https://github.com/user-attachments/assets/a9ca86e2-b569-47fe-9d62-1f7891c65450)

**Comment by stevejburge** [comment]
A 2nd example

I used this article: https://www.theguardian.com/science/2024/nov/07/cornish-monument-king-arthurs-hall-4000-years-older-without-parallel

I used this prompt
![Screenshot 2024-11-07 at 12 30 14 PM](https://github.com/user-attachments/assets/dcbb7317-3140-4706-9dc8-972592570f5b)

This was the result. The first 5 results are perfect, but it also suggested new terms

**Comment by stevejburge** [comment]
Thanks @ojopaul. Could it be a setting to remove tags not in the {post_terms} lists?

**Comment by ojopaul** [comment]
Okay @stevejburge. In another note, maybe this is another reason why we should not remove the BETA in OpenAI prompt because we really can't guarantee OpenAI will produce accurate result especially when using custom prompt https://github.com/TaxoPress/TaxoPress/issues/2332

**Comment by stevejburge** [comment]
Sure thing. I postponed that issue.
