### ISSUE TITLE
Equal width for Linked Terms columns

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2344]
Can we use an equal width for Linked Terms columns.

The primary term is taking up too much space
![linked-terms-screen](https://github.com/user-attachments/assets/88640e2b-680e-4745-ae00-4638e4729987)

**Comment by ojopaul** [comment]
I already approve the pull request but I'm dropping this note here.

The reason that take more space is to make the quick action button readable as when inside small space, everything squeeze together
