### ISSUE TITLE
Missing strings in TaxoPress Pro

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2349]
![AutoTerm_1](https://github.com/user-attachments/assets/23ec27b7-71d1-4526-8175-1e4555352b59)
![AutoTerm_2](https://github.com/user-attachments/assets/c8493653-692c-4ce5-b0ce-aedb898bd10e)
![AutoTerm_Advanced](https://github.com/user-attachments/assets/c1b9e174-4286-460c-80a3-1fb9a8a0e46e)
![AutoTerm_Sources](https://github.com/user-attachments/assets/4941110f-23b3-4db2-97c7-ac2f7e2dbbb7)
![LinkedTerms](https://github.com/user-attachments/assets/0989557e-7ea4-4f2e-ba4f-c99e3c2450af)
![ManageTerms_RemoveTerms](https://github.com/user-attachments/assets/e6fc8b84-84cd-4097-a58c-d8d4da79f0f5)
![Options_License](https://github.com/user-attachments/assets/11d86dd5-3728-4ac5-a2d5-4fddf6d69009)
![RelatedPosts_1](https://github.com/user-attachments/assets/9cbb4b42-a6f3-4174-a7c3-0eb051907299)
![TermsDisplay_1](https://github.com/user-attachments/assets/c2328e6a-1da8-423a-883e-450b6fb4e2c7)
![TermsDisplay_2](https://github.com/user-attachments/assets/c8b99f53-c25f-4a6d-9c74-c23936b1261d)

**Comment by ojopaul** [comment]
Fixed
