### ISSUE TITLE
Translation warning from 6.7

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2356]
![Screenshot 2024-11-13 at 11 05 17 AM](https://github.com/user-attachments/assets/2618f1d2-b7b6-4a1e-891b-50b40f462fa6)

"If you're using load_plugin_textdomain in your plugin then you need to change where it runs for 6.7. The documentation states to call it in the plugins_loaded hook. It now has to be called no sooner than the init hook. If you are loading it before that, WordPress throws a deprecated message. WooCommerce is affected by this.
https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/ "

**Comment by ojopaul** [comment]
@stevejburge I'm wondering why you're getting the error?
We're actually loading the translation in `init` https://github.com/TaxoPress/TaxoPress/blob/development/inc/class.client.php#L11

How can I see this notice?

**Comment by ojopaul** [comment]
@stevejburge I see the error now after changing my language

**Comment by ojopaul** [comment]
@stevejburge I've investigated and can confirm the translation is called in only one place which is in `init` https://github.com/TaxoPress/TaxoPress/blob/development/inc/class.client.php#L11

Not really sure why the error is still showing but will leave it for last so as not to stay stuck on this.
