### ISSUE TITLE
Suggestion: Feature to untag all posts with specific tag

### ISSUE THREAD

**Issue by Vidyut** [TaxoPress/taxopress#246]
A feature to remove a tag from all posts (without deleting the tag itself) would be useful. The autotagging has gone ahead and added tags to posts inappropriately, but I don't want to delete the tags, as they are legit tags for more specific content than the carpet bombing the automation has done and I have put effort into filling in descriptions, images, custom fields and so on, so simply deleting and recreating is not a solution. If I can untag all the posts, retagging only the relevant ones should be simple.

**Comment by stevejburge** [comment]
Could possibly be included with https://github.com/TaxoPress/taxopress/issues/248
