### ISSUE TITLE
Clean up the Auto Terms screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#249]
Two small changes, please:

1. Move the "Keywords list" area up
2. Move the "Options header down above the "Target" field

![Screen Shot 2021-03-03 at 2 22 57 PM](https://user-images.githubusercontent.com/3868028/109860385-1523b900-7c2c-11eb-9bf1-9b11aacf77f1.png)

**Comment by olatechpro** [comment]
@stevejburge , i just notice you made changes to this an hour ago after i just completed changing it to repeated field

**Comment by olatechpro** [comment]
Should i go ahead with the PR or revert the changes ?
