### ISSUE TITLE
Dandelion API was working

### ISSUE THREAD

**Issue by Vidyut** [TaxoPress/taxopress#250]
Dandelion API was the only one among the old ones that was working. I read in the changelog that it was removed. Was not necessary to remove this one. Dandelion API works.

I think the confusion was that there was an old depreciated API ID and key and a new API Access token. The Dandelion API works with the access token.
![screenshot-aamjanata com-2021 03 04-02_34_26 (1)](https://user-images.githubusercontent.com/697822/109872420-69618400-7c92-11eb-94e4-4702180110f2.png)

**Comment by olatechpro** [comment]
We were supposed to remove the deprecated Dandelion but seems we removed the 3. So, will be restored in the next release

**Comment by Vidyut** [comment]
Ah lol. I did all the screenshot and explanation unnecessarily.
