### ISSUE TITLE
Possible fix for Alchmeny / IBM Cloud

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#252]
> It is now part of IBM Cloud under "Natural Language Understanding" but I am sure the API interface in SimpleTags must be updated to get it to work

@olatechpro I've managed to get an API key and a URL. It might be possible to get this working

There's an integration guide: https://cloud.ibm.com/services/natural-language-understanding/crn%3Av1%3Abluemix%3Apublic%3Anatural-language-understanding%3Aus-south%3Aa%2Fe3114d8d39884e3fa0c3c16a92ff17a3%3A780d801d-b463-4428-b455-5c0c3863506e%3A%3A?paneId=manage&new=true

**Comment by olatechpro** [comment]
Hi @stevejburge , the link you posted is probably account based link as it resulted in 404 clicking from this end.

**Comment by stevejburge** [comment]
OK, let's consider this integration dead
