### ISSUE TITLE
Put 3rd Dandelion API box back

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#255]
This API does work. Let's put it back. The name can be "dataTXT by Dandelion"

**Comment by olatechpro** [comment]
Hi, steve, which of these are you talking about ?

The "Dandelion - Entity Extraction API - Access token(New!)" ?
<img width="613" alt="Screen Shot 2021-02-23 at 1 53 20 PM" src="https://user-images.githubusercontent.com/3868028/108892975-8802b380-75de-11eb-8c57-f0972b15dac1.png">

**Comment by stevejburge** [comment]
@olatechpro Yes, please. That is the box that works.

**Comment by olatechpro** [comment]
I fixed it under #250 3 days ago
