### ISSUE TITLE
Plugin workd really bad with a blog with many tags

### ISSUE THREAD

**Issue by Martinrox** [TaxoPress/taxopress#26]
When creating a post, where i need to fill out all the tags, gets really slow and gets tons of time out when having 8.000+ tags on wordpress, this makes basically the entire feature worthless since as soon as i write a word, i need to wait 30sec+ for the plugin to "search" for a matching tag and 99% of all the times it start to search it gets a timeout and i have to write it all over again...
Is there a way to fix this?

Screenshot: http://i.imgur.com/i7Th9eB.jpg

**Comment by herewithme** [comment]
Interestingly, I will create a similar environment to test performance.
