### ISSUE TITLE
Remove or fix Opencalais?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#279]
Unfortunately, despite this fix https://github.com/TaxoPress/taxopress/issues/137, OpenCalais still isn't working with a fresh API key

@olatechpro This has been broken for a long time. Probably best to remove it?

**Comment by olatechpro** [comment]
I just tested this and it works. Please note, there's need for content to be in the editor to retrieve suggested tags

**Comment by olatechpro** [comment]
You can check this loom video https://www.loom.com/share/842d8dc7e71c43a5bcf0f80b1024a687
