### ISSUE TITLE
New Taxonomy: Media Tags

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#283]
We should provide a new taxonomy users: "Media Tags" for the Media Library

It could be enabled on a screen like this: https://github.com/TaxoPress/taxopress/issues/227

**Comment by olatechpro** [comment]
Hi @stevejburge , can you elaborate this feature more most especially the term "taxonomy users" ?

Based on my understanding, you mean we should add a new taxonomy named "Media Tags" which will be for media use and available under  "Media Library" menu and upload ?

Further more, the media tag page will be a standard taxonomy for example like "tag" page and clicking on the count will lead to a page that display all media related to the media tag name ?

**Comment by stevejburge** [comment]
@olatechpro Sorry for not being clear here:

<img width="147" alt="Screen Shot 2021-03-24 at 9 20 04 AM" src="https://user-images.githubusercontent.com/3868028/112317229-36535480-8c82-11eb-9e49-ac3a59704cff.png">


![Uploading Screen Shot 2021-03-24 at 9.20.16 AM.png…]()
