### ISSUE TITLE
2 Extra columns on "Taxonomies" screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#335]
- Can we add a column indicating where the taxonomy comes from?
- Can we add a column showing the number of items in that taxonomy?

![Screen Shot 2021-04-09 at 7 45 41 AM](https://user-images.githubusercontent.com/3868028/114175381-fa69f180-9907-11eb-996e-25a343cf769f.png)

**Comment by olatechpro** [comment]
Thinking about the fact user can rename any taxonomy for example "Category", i think it'll be good to add a column, primary name or slug(since this is not changeable for an external taxonomy) so they can always relate to what was the main name before update or what do you think ?

**Comment by stevejburge** [comment]
@olatechpro Yes. Maybe inside on main screen for each taxonomy?

**Comment by olatechpro** [comment]
> @olatechpro Yes. Maybe inside on main screen for each taxonomy?

Can you help with a visual of the main screen you're referring to?

**Comment by stevejburge** [comment]
<img width="1370" alt="Screen Shot 2021-04-09 at 8 04 55 AM" src="https://user-images.githubusercontent.com/3868028/114177341-49b12180-990a-11eb-91bc-458be2122e45.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , Unfortunately, no way to know the plugin that registered a taxonomy. The best i think we can do is adding original taxonomy registration key for example 'post_tag' for tags which doesn't change even if they edit the taxonomy label for identification

**Comment by stevejburge** [comment]
@olatechpro Sounds like a good option. That column could be enable or disable via "Screen Options". We could also show into on the editing screen.
