### ISSUE TITLE
Normal tags box for Media

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#344]
The Tags box for Media works differently from Tags on the Post screen:
<img width="514" alt="Screen Shot 2021-04-14 at 9 12 36 AM" src="https://user-images.githubusercontent.com/3868028/114715969-99745c00-9d01-11eb-8673-ac8b7e3be905.png">

Can we use this approach?
<img width="300" alt="Screen Shot 2021-04-14 at 9 13 53 AM" src="https://user-images.githubusercontent.com/3868028/114716143-c32d8300-9d01-11eb-991f-3c1f5728a923.png">

**Comment by olatechpro** [comment]
That screenshot is gutenberg editor screen. Media uses normal classic editor meta box. You can add new taxonomy to media to check.

**Comment by stevejburge** [comment]
Ok, let’s skip this then
