### ISSUE TITLE
Small text change on Taxonomies screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#346]
![Screen Shot 2021-04-14 at 9 23 52 AM](https://user-images.githubusercontent.com/3868028/114717870-7d71ba00-9d03-11eb-96f1-6ffdc746c87b.png)

**Comment by olatechpro** [comment]
Should we add TaxoPress to all taxonomy created with TaxoPress as well... If so, what happen to when they have descriptions?

**Comment by stevejburge** [comment]
Yes, good idea. Maybe remove "TaxoPress" if there is a description
