### ISSUE TITLE
New "Permalinks" tab

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#353]
These should be in their own tab:

<img width="744" alt="Screen Shot 2021-04-14 at 9 51 32 AM" src="https://user-images.githubusercontent.com/3868028/114721568-0a6a4280-9d07-11eb-98e3-6f8b4a3ddcd9.png">

**Comment by olatechpro** [comment]
Do you mean we should move slug from general to permalink tab after creation?

Note that slug is always visible to taxonomy created with TaxoPress when edit but not visible for external taxonomy.
