### ISSUE TITLE
Auto-populate labels ... run automatically?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#354]
Can we run this automatically when someone adds a new taxonomy? 

<img width="591" alt="Screen Shot 2021-04-14 at 9 56 47 AM" src="https://user-images.githubusercontent.com/3868028/114722480-d7747e80-9d07-11eb-8dab-eae9a5e60d10.png">

**Comment by olatechpro** [comment]
To be sure, we should auto update when creating new taxonomy and no action when editing existing taxonomy even if singular and plural name change?

**Comment by stevejburge** [comment]
@olatechpro Yes, good idea
