### ISSUE TITLE
Remove "Deactivate" and "Delete" 

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#356]
These don't need to be easily visible of clickable 

Maybe there is a new "Deactivate or Delete" tab

<img width="306" alt="Screen Shot 2021-04-14 at 10 04 57 AM" src="https://user-images.githubusercontent.com/3868028/114723946-1820c780-9d09-11eb-9a1f-628cc9a403d0.png">
<img width="234" alt="Screen Shot 2021-04-14 at 10 05 31 AM" src="https://user-images.githubusercontent.com/3868028/114723949-18b95e00-9d09-11eb-8d34-c89ca8162363.png">

**Comment by olatechpro** [comment]
Can you explain better. I can't understand what you mean with the comment in relation to the screenshot

**Comment by stevejburge** [comment]
It is very easy to click the wrong button here. Let's make it more difficult to click these buttons

We can add a new "Deactivate or Delete" tab for these buttons

**Comment by olatechpro** [comment]
Okay. Deactivate or delete goes to a new tab in edit screen.

What of the second screenshot of main taxonomy screen?

**Comment by stevejburge** [comment]
There should be no "Delete" or "Deactivate" links outside of that tab

**Comment by stevejburge** [comment]
This can also go:
<img width="208" alt="Screen Shot 2021-04-14 at 10 54 42 AM" src="https://user-images.githubusercontent.com/3868028/114731600-e101e480-9d0f-11eb-8ad8-6b5af644e5c8.png">
