### ISSUE TITLE
Media Tags error

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#383]
Yes, TaxoPress does create it :)

<img width="1318" alt="Screen Shot 2021-04-15 at 11 41 55 AM" src="https://user-images.githubusercontent.com/3868028/114897834-9d76ab80-9ddf-11eb-8c37-81bcf89f42fe.png">

<img width="650" alt="Screen Shot 2021-04-15 at 11 42 43 AM" src="https://user-images.githubusercontent.com/3868028/114897935-b41d0280-9ddf-11eb-8323-b889610a9204.png">

**Comment by olatechpro** [comment]
So, you want them to be able to delete media tags?

**Comment by olatechpro** [comment]
Btwn, the create terms refers to terms that they created using taxonomies UI

**Comment by stevejburge** [comment]
We should say that this taxonomy was created with TaxoPress.

Yes, they can delete it
