### ISSUE TITLE
Create a Pro version of TaxoPress

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#403]
This will be a single add-on for TaxoPress.

It can work the same way as Yoast with the Free and Pro installed together:
<img width="472" alt="Screen Shot 2021-04-22 at 10 44 25 AM" src="https://user-images.githubusercontent.com/3868028/115734529-c6ef8400-a357-11eb-8000-bd422390eef4.png">

For now, it only needs one feature: a new "License" menu link with the ability to add a license key from TaxoPress.com:
https://docs.easydigitaldownloads.com/article/380-activating-checking-deactivating-license-keys-in-wp-plugins

<img width="619" alt="Screen Shot 2021-04-22 at 10 49 32 AM" src="https://user-images.githubusercontent.com/3868028/115735380-6f9de380-a358-11eb-939c-6cba60ba4c6b.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , on this:
> "License" menu link with the ability to add a license key from TaxoPress.com:

I need to be updated on the licence source so i can successfully validate the licence status when user enter new licence for validation

**Comment by stevejburge** [comment]
@olatechpro I shared some examples in Slack
