### ISSUE TITLE
Two ads in the Free version of TaxoPress

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#404]
Let's add one menu link and one banner to the Free version.

- These will only shown to Administrators
- These will be disabled if the Pro version is installed

![Screen Shot 2021-04-22 at 10 48 11 AM](https://user-images.githubusercontent.com/3868028/115735668-a83dbd00-a358-11eb-8ace-6818a3b7e5f7.png)

**Comment by olatechpro** [comment]
Hello @stevejburge ,
1.) Where does this upgrade to pro menu link leads to ?

2.) ...considering the fact you commented.... 

> These will be disabled if the Pro version is installed

Does that mean pro features will be available once pro version is installed even if it's not activated ?

**Comment by stevejburge** [comment]
1. https://taxopress.com/pro

2. Sorry, I should have been clearer. These will be disabled if the Pro version is activated.
