### ISSUE TITLE
Wrong redirection after creating new taxonomy

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#406]
After creating a new taxonomy, you are sent to another "New" screen.

The best option would be to stay editing the new taxonomy
<img width="904" alt="Screen Shot 2021-04-28 at 10 17 21 AM" src="https://user-images.githubusercontent.com/3868028/116419502-20016100-a80b-11eb-98d5-b6503d6cc734.png">

**Comment by stevejburge** [comment]
this issue has re-appeared

**Comment by olatechpro** [comment]
@stevejburge , the original issue was to redirect user back to editing screen after creating taxonomy and i just tested that now. Maybe you can share more information on circumstances that made it work otherwise so i'll be able to recreate the issue.

**Comment by stevejburge** [comment]
@olatechpro I'm getting this on test sites. 

Not sure if this related:
<img width="1345" alt="Screen Shot 2021-07-05 at 6 53 16 PM" src="https://user-images.githubusercontent.com/3868028/124522754-55ee3300-ddc2-11eb-9fab-12f4f0713f77.png">

**Comment by olatechpro** [comment]
Okay, I get it now

**Comment by olatechpro** [comment]
Hi @stevejburge , is this error from the other issue #617 or this is another one when you try to create a new taxonomy ?

**Comment by stevejburge** [comment]
@olatechpro This is the same.  I think we can focus on #617 for now
