### ISSUE TITLE
Remove "Rewrite" field for Tags and Categories

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#419]
This is for taxonomies not created with TaxoPress:

- We can remove "WordPress can use a custom permalink for this taxonomy. It does not have to match the slug." for Tags and Categories. The option does not work. 
- New label" Custom Permalink"
- New text: "Use this option to change the permalink for this taxonomy"

<img width="1253" alt="Screen Shot 2021-04-28 at 4 50 44 PM" src="https://user-images.githubusercontent.com/3868028/116470827-eb5ccc00-a841-11eb-8306-ac9f302c96fc.png">

**Comment by olatechpro** [comment]
HI @stevejburge , can you explain this issue better  ?
1.) You said 

> "This is for taxonomies not created with TaxoPress:"

 and then in the following line, you mentioned categories and tags. So, i don't know if it should be remove for all external taxonomies or categories and tags alone.

2.) You mean we should replace 
- "Rewrite" label with "Custom Permalink" and
- text with "Use this option to change the permalink for this taxonomy"

3.) After changing the text, the 'Rewrite' checkbox should not be available for Tags and categories alone while it'll be availble for all others include external taxonomies ?

**Comment by stevejburge** [comment]
@olatechpro Sorry, ignore this for now
