### ISSUE TITLE
Malware False Positive in WordPress.org Release

### ISSUE THREAD

**Issue by VR51** [TaxoPress/TaxoPress#430]
Hi there. My web host's automated malware scanner has flagged malware in the following file:

``https://plugins.trac.wordpress.org/browser/simple-tags/trunk/vendor/publishpress/wordpress-version-notices/tests/bootstrap.php``

This file was flagged in the latest plugin release 3.0.4.2.

I can't find this file in the GitHub repo. I can't post this note in the wordpress.org support forum because the mods and I don't get along and my posts always get held in moderation.

The message from my host includes:

``'ClamAV detected virus = [{HEX}php.exe.globals.413.UNOFFICIAL]':    /home/hotshots2/public_html/wp-content/plugins/simple-tags/vendor/publishpress/wordpress-version-notices/tests/bootstrap.php``

Lee

**Comment by stevejburge** [comment]
Thanks for reporting that @VR51

**Comment by olatechpro** [comment]
This has been fixed in 3.0.4.3
