### ISSUE TITLE
Notices in 3.0.4.3

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#431]
> When a user is defined as an Editor
> 
> Notice: Undefined variable: taxopress_settings_key in /home/..../simple-tags/inc/functions.inc.php on line 62
> 
> Notice: Undefined variable: taxopress_settings in /home/..../simple-tags/inc/functions.inc.php on line 63
> 
> Notice: Trying to access array offset on value of type null in /home/..../wp-admin/includes/plugin.php on line 1920
> 
> Notice: Trying to access array offset on value of type null in /home/.../wp-admin/includes/plugin.php on line 1923
> 
> In Dashboard (Left Menu Area)
> 
> Notice: Trying to access array offset on value of type null in /home/.../wp-admin/menu-header/header.php on line 201

https://wordpress.org/support/topic/problems-after-updating-to-3-0-4-3/

**Comment by olatechpro** [comment]
I couldn't recreate this due to the fact it could be a conflict with a plugin that modify menu but i provided a possible fix by adding a check.

So, user can check in new release and re-open issue if still exist after the fix
