### ISSUE TITLE
Not picking up all taxonomies on Taxonomies screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#432]
WooCommerce uses taxonomies for product attributes

![Screen Shot 2021-05-04 at 11 35 24 AM](https://user-images.githubusercontent.com/3868028/117030845-0742f080-acce-11eb-9a12-cea12c91b9ab.png)

We show them in some parts of TaxoPress, such as "Mass Edit":

<img width="590" alt="Screen Shot 2021-05-04 at 11 44 20 AM" src="https://user-images.githubusercontent.com/3868028/117030945-1fb30b00-acce-11eb-9870-97e01e3d082d.png">

But not in others such as the "Taxonomies" screen

**Comment by olatechpro** [comment]
Hi @stevejburge ,

This is not a bug as only public taxonomies are currently enabled to be editable unless you want us to enable Private taxonomies as well ?

Although by implication, the page may be filled with taxonomies that user won't even know where they came from as plugins use private taxonomies mostly to prevent them from showing up in menu or hide user by user and privately used in the plugin.

**Comment by stevejburge** [comment]
@olatechpro Good point. In the future, let's come back and add it as a configurable setting

**Comment by stevejburge** [comment]
@olatechpro This is related to some issues our users have been having:
https://github.com/TaxoPress/TaxoPress/issues/620
https://github.com/TaxoPress/TaxoPress/issues/617

I think this should be a setting. We are offering the private settings under "Advanced" but if they uncheck the box, that taxonomy disappears. That's not a good experience

**Comment by olatechpro** [comment]
@stevejburge, I thought we added option to taxonomy screen to display private taxonomy as well or these are still missing there in the last release ?

**Comment by stevejburge** [comment]
@olatechpro No, no setting yet

**Comment by olatechpro** [comment]
@stevejburge , i just checked taxonomy screen on Version 3.0.7.2 and it's there. So, i'm lost on the request then unless it's something else

**Comment by stevejburge** [comment]
@olatechpro sorry I missed it. Where do I look?

**Comment by olatechpro** [comment]
Taxonomy screen

<img width="1440" alt="Screenshot 2021-07-05 at 11 39 55 PM" src="https://user-images.githubusercontent.com/46832636/124522240-729e6100-ddea-11eb-8aca-47d0b3c083b6.png">

**Comment by stevejburge** [comment]
Doh, I'm an idiot
