### ISSUE TITLE
Category Pages don't get queried

### ISSUE THREAD

**Issue by pi43r** [TaxoPress/TaxoPress#435]
When I assign pages to a certain category and open `mysite.com/category-name`  the pages don't show up on that query.
Am I doing something wrong or is this not a feature in TaxoPress?

TaxoPress v. 3.0.4.3

Edit: Other plugins work automatically

**Comment by stevejburge** [comment]
Hi @pi43r 

This is a limitation in the WordPress core. We plan to ship a workaround in an upcoming release.

**Comment by pi43r** [comment]
Ok, thank you.
I guess I can close this issue then, or do you want to keep it open until the workaround gets released?

**Comment by stevejburge** [comment]
No worries, this issue works. We'll post our discussions here

**Comment by stevejburge** [comment]
@pi43r do you want to try this version (with a possible fix) before we release?
https://app.box.com/s/vpvbzuzmms8yf5b9idl355co0n3h4afe

**Comment by stevejburge** [comment]
@olatechpro Can we add support for Media items too

**Comment by stevejburge** [comment]
@olatechpro I think we need to make this into a setting that is "Off" by default
