### ISSUE TITLE
New setting: automatically run "Add terms to existing content"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#440]
One request:

> hello, i have some posts that are automatically imported - i can tag them by using the autotag old posts, is there anyway to put that feature on a cron so it can run automatically?--

More details:

> I am importing posts via API and the auto tagging is not processing on those posts. Anyway to set this up, maybe via CRON or some other method?
> As of now the only way to get the tags onto those posts is to go on the admin dashboard and click “auto-terms old content”

Related request:

> it is not working when I insert the product in woocommerce through the WC API,

This can be a new feature for Pro users. For Free users, we can include a promotional area.

**Comment by stevejburge** [comment]
This could build on the "Previous Content" feature.

I think this should be a Pro feature

**Comment by ojopaul** [comment]
@stevejburge , can you put me though or screenshot the process where the post is been imported or plugin in use if it's a plugin ?

**Comment by stevejburge** [comment]
@ojopaul Researching this, I think the best approach is to solve this with this issue: https://github.com/TaxoPress/TaxoPress/issues/440

**Comment by stevejburge** [comment]
@ojopaul A plugin like this is a good test: https://wordpress.org/plugins/wpematico/

I grabbed some feeds from here: https://blog.feedspot.com/bbc_rss_feeds/

<img width="1238" alt="Screen Shot 2021-11-18 at 8 47 08 AM" src="https://user-images.githubusercontent.com/3868028/142427224-c52d73c4-c9f1-4b5d-b1e6-f451e444c8f4.png">

In researching this more, I think adding a Cron option is the best approach. This can be a Pro feature. Users can choose to this process on a schedule:


<img width="903" alt="Screen Shot 2021-11-18 at 8 52 03 AM" src="https://user-images.githubusercontent.com/3868028/142428086-0e47d26f-d72e-4d4d-810c-7055bbdeb49d.png">

**Comment by ojopaul** [comment]
Got it now @stevejburge

**Comment by ojopaul** [comment]
@stevejburge , should this be a dropdown  added to 'Existing content' tab that that label read,
- Schedule previous content
and drop down options been. 'once daily', 'hourly' ?

I really don't have a visual of the UI

**Comment by stevejburge** [comment]
@ojopaul Good questions.

Yes, I think those two would be good options to start with. It could be a radio box choice "Daily" or "Hourly"

**Comment by ojopaul** [comment]
@stevejburge, To test cron feature,
You can install this plugin https://wordpress.org/plugins/advanced-cron-manager/.

Then create new tag that's part of an existing post.

Go to cron manager settings and search for 

- taxopress_cron_autoterms_hourly
or 
- taxopress_cron_autoterms_daily
depending on which you setup in autoterms settings

and click execute now.

The post will be auto tag with new terms added
