### ISSUE TITLE
What to do with the "Tag Cloud" setting box

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#456]
I wonder what the best way to retire this field is?

Can we do an import for old sites? If they have any settings here, they are automatically transferred to the "Tag Clouds" screen? 

Or should we just minimize it under a "Legacy" area? That might be safest. We are going to do something very similar for "Tags for Current Post" and "Related Posts". We could add some "Legacy" area inside "Settings"

<img width="538" alt="Screen Shot 2021-05-25 at 7 52 43 AM" src="https://user-images.githubusercontent.com/3868028/119509921-4ba23900-bd2e-11eb-8a3b-c5d9fdddee59.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , just to be sure, we'll add a tab "Legacy" in settings where these will be moved and "Tag cloud tab removed ?

**Comment by stevejburge** [comment]
Yes, let's take that approach for now.

We can have a "Legacy" tab with "Tag cloud" underneath. This can have the message: 
"These settings are no longer being updated. Please use the "Tag Clouds" screen instead."

In future release, we will also move "Tags for Current Post" and "Related Posts" here.
