### ISSUE TITLE
Did we lose the Advanced Usage box

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#480]
This is in the legacy option:

<img width="1042" alt="Screen Shot 2021-05-26 at 7 58 58 AM" src="https://user-images.githubusercontent.com/3868028/119673193-68a33e80-bdf8-11eb-8afe-eb5474360a40.png">

**Comment by olatechpro** [comment]
I didn't really know it application. So, that's why I didn't add it since I'm the one implementing new tag cloud option and has nothing to do with previous options

**Comment by stevejburge** [comment]
It allows you to generate PHP code for adding the Tag Cloud directly into your theme

**Comment by olatechpro** [comment]
Generate php code ?

That tag is the same for all and no option to generate code in the widget neither does It get populate with options after creating/adding the widget as it was there before

**Comment by stevejburge** [comment]
OK, let's leave it in legacy for now
