### ISSUE TITLE
Hide license key from non-Administrators

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#514]
Only administrators need to see this "License" link
<img width="330" alt="Screen Shot 2021-06-01 at 8 46 45 AM" src="https://user-images.githubusercontent.com/3868028/120334167-0ba2ff00-c2b6-11eb-8a7a-a5abf7488495.png">

**Comment by olatechpro** [comment]
close with https://github.com/TaxoPress/TaxoPress-Pro/pull/16
