### ISSUE TITLE
'Taxonomy slug' should not accept special characters as underscores.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#521]
1. In TaxoPress, select 'Add New' taxonomies
2. In 'Taxonomy Slug' enter some texts followed by special characters (test!@#)

Taxonomy slug should not accept special characters/ it should not accept special characters as underscores.

![taxonomy slug](https://user-images.githubusercontent.com/83974581/120540726-da9df980-c39d-11eb-903d-c0cc64e94778.JPG)

**Comment by olatechpro** [comment]
Hi @sathyapriya91, special characters are not allowed and if entered are replaced/removed instantly.

Isn't that how it currently work or you were able to create a taxonomy with special character as slug?

**Comment by olatechpro** [comment]
2.) Underscores is allowed in slug

**Comment by sathyapriya91** [comment]
@olatechpro If a special character is entered, it automatically converts that special character as an underscore and accepts it.

**Comment by olatechpro** [comment]
@sathyapriya91 
That's how it's designed to work and not a bug. 

There's a warning on the page of slugs only accepting alphanumeric, Latin characters and underscores. 

So, in situations of user entering a specific character either consciously or not, there's need to replace that special character and by doing so, they'll be aware something happen rather and nothing happening which may give the impression like the input not accepting further text or so.

**Comment by olatechpro** [comment]
Like I said, by design, underscore is a valid character in slug.

**Comment by sathyapriya91** [comment]
@olatechpro  OK, I thought that it would be nice if it displays a warning message while entering, instead of just replacing it with an underscore.
