### ISSUE TITLE
Change documentation link

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#537]
Here's the new documentation link https://taxopress.com/docs/format-terms-current-post/

Can we also make the box larger?
<img width="1042" alt="Screen Shot 2021-06-08 at 10 22 42 AM" src="https://user-images.githubusercontent.com/3868028/121203133-de20fd00-c843-11eb-8945-f34ef16013f7.png">

**Comment by olatechpro** [comment]
Hi @stevejburge , the box size issue may be a cache issue from your end, you can confirm if it still remain the same after this update and probably clearing cache:

<img width="729" alt="Untitled" src="https://user-images.githubusercontent.com/46832636/121871004-8418af80-ccfb-11eb-9ad7-a32e7e55ce58.png">
