### ISSUE TITLE
'Remove terms from posts' is shown even if it didn't remove the term.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#545]
1. Go to 'Manage Terms'
2. Select 'Posts', 'tags' -> Change selection
3. In Remove terms, type a term that is not available
4. Click 'Remove' button

'No term removed' should be displayed just like 'No term renamed', 'No term deleted'.

Though its not a big issue, it would be nice to have these to avoid confusion for the user using so many terms.

![remove term](https://user-images.githubusercontent.com/83974581/121741797-d7002600-cab3-11eb-86ea-d0c817655067.JPG)

**Comment by stevejburge** [comment]
thanks @sathyapriya91. Good find
