### ISSUE TITLE
New pagination not working on TaxoPress

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#553]
@olatechpro you can see this on our site at Taxopress.com. The pagination isn't working for 'Manage Terms'

![Screen Shot 2021-06-14 at 11 16 32 AM](https://user-images.githubusercontent.com/3868028/121916561-410e0a80-cd02-11eb-99ac-7bf19261a7f5.png)

**Comment by olatechpro** [comment]
@stevejburge Another plugin is generating error on that page that prevent code after to work.

Can you right click and check the console for the error and after, deactivate the easy pricing tables to see if it works after?

**Comment by olatechpro** [comment]
....
And just to be sure, you can't save right? I

Clicking "Apply" button doesn't do anything?

**Comment by stevejburge** [comment]
@olatechpro Yes, "apply" does nothing

Here's the console output:

![Screen Shot 2021-06-14 at 11 27 45 AM](https://user-images.githubusercontent.com/3868028/121917956-972f7d80-cd03-11eb-89b5-9c78123ebad9.png)

**Comment by olatechpro** [comment]
Can't properly debug the reason there. You can check error log too to find what's causing the conflict.

**Comment by stevejburge** [comment]
@olatechpro Found it. Try testing with this plugin installed https://wordpress.org/plugins/easy-pricing-tables/

**Comment by olatechpro** [comment]
@stevejburge  hover over the '(editor-script.js?ver=5.7.2:6)' in console and you'll see that's not our error but easy pricing table error and it's not affecting just our plugin page but every pages. Does deactivating the error fix the issue ?

<img width="390" alt="Untitled-2" src="https://user-images.githubusercontent.com/46832636/121919672-2aca7380-cd2f-11eb-823e-5fd2a8fc577c.png">
