### ISSUE TITLE
Increase width of Term Link boxes

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#562]
![Screen Shot 2021-06-14 at 3 46 00 PM](https://user-images.githubusercontent.com/3868028/121950490-b3ddac80-cd27-11eb-9b0c-e854cb77ed1b.png)
![Screen Shot 2021-06-14 at 3 46 10 PM](https://user-images.githubusercontent.com/3868028/121950491-b4764300-cd27-11eb-9bda-bba705ed497d.png)

**Comment by olatechpro** [comment]
What is the browser and resolution are you experiencing this as it has full width already and can't see the issue?

**Comment by stevejburge** [comment]
I see this working in Chrome

However, not working correctly in Firefox
