### ISSUE TITLE
Selected 'New Term(s) Name' is displayed in 'Terms to rename' box.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#572]
1. Go to 'Manage Terms'
2. Select 'Posts', 'tags' -> Change selection
3. Select Rename terms->Terms to rename, Choose a term from the list on the left 
4. Select New Terms Name and choose a term from the list on the left

Selected Term should be displayed in 'New Terms Name' box. But it is displayed in 'Terms to rename; box instead.

It works well when it is typed manually. Same happens in "Merge Terms".

![Renameterm](https://user-images.githubusercontent.com/83974581/122090232-69f2d600-cdbc-11eb-92b4-b67ab2bdbf4d.JPG)

**Comment by olatechpro** [comment]
Hi @sathyapriya91 and @stevejburge . Isn't it how it's supposed to work ?
- Rename terms simply implies to rename old term and give it new name.
- To do that, we need 2 boxes which are 'Term(s) to rename' and 'New term name(s)'
-  When they click from the tag list, the clicked tag is definitely the term we want to rename and as a result, it goes to the first box 'Term(s) to rename' while user is expected to type the new name in the box below it. ?
-  So, there's no reason the clicked tag should go to the new term name box or i'm i missing something ?

**Comment by stevejburge** [comment]
thanks @sathyapriya91 and @olatechpro 

Yes, I see the possible confusion here. I wouldn't call it a bug, but we probably can make the UI better.
