### ISSUE TITLE
 Couldn't add term that has special characters when "whole word" option is selected.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#586]
1. In Auto term-> Activate Auto tags for posts -> Tags/categories
2. Create a term with special character (#resort) in Keywords list
3. Select the "Whole word" check box  that adds the term only when it finds the same content
4. create a post with the term in it and observe the published post

The term should be added to the published post. But the term is not added because it has special character in it.

![tagwithcharacter](https://user-images.githubusercontent.com/83974581/122990283-a2645800-d358-11eb-8e2f-a400c76e7449.JPG)
![tagwithcharacter1](https://user-images.githubusercontent.com/83974581/122990286-a2fcee80-d358-11eb-812a-b456315d314d.JPG)

**Comment by olatechpro** [comment]
Thanks @sathyapriya91 , we're using regex to find terms in content and for security reason, we escape special character so that searches for the literal characters can be done but right now, we'll just make exception for # since hashtag is valid and safe.
