### ISSUE TITLE
Bug with "Whether a taxonomy is intended for use publicly either via the admin interface or by front-end users."

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#599]
If you uncheck this box, it hides some taxonomies, even from the "Taxonomies" screen in TaxoPress. This means people can't check the box again to show it

This box should not hide from the "Taxonomies" screen in TaxoPress
![Screen Shot 2021-06-24 at 2 12 28 PM](https://user-images.githubusercontent.com/3868028/123312457-5ea75500-d4f6-11eb-9a52-a9771357b378.png)

**Comment by olatechpro** [comment]
Hi @stevejburge, I think we should rather give a settings that allow users to select the taxonomy to display on taxonomies screen as we currently display public taxonomies exuding private taxonomies and no way to make exceptions.

**Comment by olatechpro** [comment]
Auto including all private taxonomies won't really be ideal as taxonomies screen will be full of plugins and themes hidden taxonomy that user doesn't even know exist

**Comment by stevejburge** [comment]
@olatechpro That's a good idea

In this situation, we surprised the user who lost access to his taxonomy
