### ISSUE TITLE
Term is not added when it has numbers followed by characters in Auto Terms.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#600]
1. In Auto terms-> Activate Auto tags for posts -> categories
2. Have a term that has only numbers (1221)
3. Check the 'Target'->Autotag only Posts without terms.
4. create a post that the term along with some numbers and texts(122145gilbert road)
5. Publish the post and observe the category

The term should be added in the post as it has the term in it. The term is not added even though the whole word option is not enabled in posts -> categories.

![numbersincategory](https://user-images.githubusercontent.com/83974581/123323529-77aa0900-d4ea-11eb-9dc0-de2adce795fc.JPG)
![postscategories](https://user-images.githubusercontent.com/83974581/123323531-78429f80-d4ea-11eb-8b54-24dbd2182524.JPG)

**Comment by olatechpro** [comment]
This is same as #611. So, closing this.
