### ISSUE TITLE
Post is not autotagged even when the content matches the exact term.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#607]
1. In Posts->Categories, Add a new category (gold)
2. In Auto Terms->Terms to use->Use this option if you don't want to use all the terms in your Categories taxonomy.
3. In Auto terms, add that term(gold) in the Keywords list
4. Create a post with that term in it
5. Publish the post and observe the result

The term should be added to the post but it is not added.

![category](https://user-images.githubusercontent.com/83974581/123688017-6ae92600-d806-11eb-9bf5-f4f47f0e74fe.JPG)
![keywordcategory](https://user-images.githubusercontent.com/83974581/123688019-6b81bc80-d806-11eb-8fb1-f5b0439cf523.JPG)
![postcategory](https://user-images.githubusercontent.com/83974581/123688022-6b81bc80-d806-11eb-8396-83028300d1ef.JPG)

**Comment by olatechpro** [comment]
I just tested this and it's work. Can you confirm too before closing this issue ? @stevejburge

**Comment by stevejburge** [comment]
Agree, this is working for me. We can re-open if there are reports
