### ISSUE TITLE
Found a spelling and grammar issue under Auto Terms

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#615]
![Support Hashtag spelling](https://user-images.githubusercontent.com/79052272/124500659-65975880-dd7d-11eb-8df2-e684defbf44f.PNG)

Under the "Support Hashtag Format" option at the end of the line description the word 'allow' should be 'allows' and the line should read 'This option allows this issue to be fixed.' for proper grammar.

**Comment by olatechpro** [comment]
Same as #708
