### ISSUE TITLE
The Auto Links feature does not automatically add links to all the content that matches the term.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#616]
1. In Taxonomy -> Settings -> Select "Auto links tags" check box
2. Create a post with already created tags in it
3. Publish the post and see the autolink

The post should add auto links to all the contents that matches the terms in the tag. 
But the repeated contents are not auto linked even if they matches the terms in tag.

![auto link](https://user-images.githubusercontent.com/83974581/124517470-e4e65580-dd98-11eb-9b64-8e6b88846a47.JPG)
![tags](https://user-images.githubusercontent.com/83974581/124517471-e57eec00-dd98-11eb-9d6e-273fb28db3d1.JPG)

**Comment by sathyapriya91** [comment]
After exploring the auto links settings I came to know that the issue I mentioned "The repeated contents are not auto linked" is not a bug. It works perfectly when we change "Maximum number of links for the same tag:" settings.
 
The only issue I see here now is that we cannot auto link the title of the post. Only the contents of the post is autolinked if it matches the term.

**Comment by anhredweb** [comment]
Hi @stevejburge as we see the comment earlier that `it works perfectly`:
![image](https://user-images.githubusercontent.com/6948022/126600590-9e8d82b6-bd03-48d8-98cc-baa35aae00dc.png)

We tested and confirm it. About autolinks for the title of post, it's a new feature and not a bug. How will it will be implemented in case you want to do that?

Thanks.

**Comment by stevejburge** [comment]
Thanks @anhredweb. Let's close in favor of https://github.com/TaxoPress/TaxoPress/issues/701
