### ISSUE TITLE
Broken feature: Whether a taxonomy is intended for use publicly either via the admin interface or by front-end users.

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#617]
![Screen Shot 2021-07-05 at 5 38 49 PM](https://user-images.githubusercontent.com/3868028/124519632-e115fb80-ddb7-11eb-9735-ab33fd81e6bf.png)

If you save a taxonomy with this enabled, TaxoPress does not save and produces this error:

![Screen Shot 2021-07-05 at 5 33 31 PM](https://user-images.githubusercontent.com/3868028/124519424-44ebf480-ddb7-11eb-90d8-af174e138b47.png)

**Comment by olatechpro** [comment]
Hi @stevejburge , unfortunately, i'm not able to reproduce this issue from my end and will need more information to be able to.

1.) Is this happening with every taxonomies or limited to specific taxonomies with some special attribute like 'external taxonomy or the ones created with TaxoPress', 'public, private or core taxonomy', a specific plugin taxonomy only or any other information that'll help me in producing this issue probably by testing the taxonomies of varieties to be sure which trigger the error so i can reproduce and find the source of problem from here

**Comment by stevejburge** [comment]
@olatechpro update, I can get this error consistently on my local server, even without changing the public settings

This might be a clue. The sidebar is getting cut off at "Advanced":

<img width="221" alt="Screen Shot 2021-07-06 at 8 18 36 AM" src="https://user-images.githubusercontent.com/3868028/124598630-d3518c00-de32-11eb-8d3b-64fcb2a8f89c.png">

**Comment by olatechpro** [comment]
I was able to recreate this issue after installing query monitor plugin.
