### ISSUE TITLE
"Auto links tags" works differently for numbers and characters.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#622]
1. In Taxonomy -> Settings -> Select "Auto links tags" check box
2. Have a term in Tags that has numbers (6043)
3. Create a post with that term and also with few more numbers(6043786965) in it

The term with few more numbers in it is auto linked here. Whereas it works differently for characters.

The term "resorts" is not auto linked because it mentioned as "resort" in Tags.

![character autolink](https://user-images.githubusercontent.com/83974581/124654166-13286b80-de53-11eb-9df4-dea9ff2b387b.JPG)
![numbers autolink](https://user-images.githubusercontent.com/83974581/124654169-13c10200-de53-11eb-950d-9b3c6c8e4825.JPG)
![tags](https://user-images.githubusercontent.com/83974581/124654172-13c10200-de53-11eb-95d9-6fa144fe6f1d.JPG)

**Comment by anhredweb** [comment]
The result of the commit above @stevejburge 
![image](https://user-images.githubusercontent.com/6948022/126737071-bc578382-b11d-49c2-865c-4805c0d77f03.png)

Thanks.

**Comment by stevejburge** [comment]
@anhredweb Thanks
