### ISSUE TITLE
Suggestion to add error message or change 'Slug' descriptor

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#626]
When creating a new 'Tag' or 'Media Tag' I replaced the hyphen '-' with the '@' symbol to see what would happen. The tag was created but the slug was automatically modified without an error message popping up stating why such a change occurred and that it was automatic.

Also, it is sometimes human nature NOT to read the full description and maybe pick out what you want out of a sentence. For example in the sentence "It is usually all lowercase and contains only letters, numbers, and hyphens.", one might read the word _**"usually"**_ and ignore _**"only"**_ as a suggestion and use something other than a character that is allowed. Keeping "It is usually all lowercase." but probably  adding "Note:" before "only use letters, numbers, and hyphens." would help.

![Slug description suggestion](https://user-images.githubusercontent.com/79052272/124798580-bf7c5780-df10-11eb-82d7-41965df9c4b2.PNG)

**Comment by olatechpro** [comment]
Media tags or any custom taxonomy added by taxopress or any other plugin and even the inbult taxonomy creation process and UI is handled by wordpress and not us. @stevejburge

**Comment by stevejburge** [comment]
@olatechpro True. Let's move on
