### ISSUE TITLE
Fields in "Auto link" tab accepts negative values.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#631]
1. In Taxonomy -> Settings -> Select "Auto links tags" check box
2. In "Auto link" tab enter negative values (-67) in the fields "Min usage for auto link tags",
"Maximum number of links per article" and "Maximum number of links for the same tag" 

Fields should not accept negative values.

Able to update the fields with negative values. Auto link tags are not added While creating a post with negative values in settings.

![negativevalues](https://user-images.githubusercontent.com/83974581/124976563-4d754280-dfe4-11eb-9069-9ab7a55b4565.JPG)
![postwith negativevalue](https://user-images.githubusercontent.com/83974581/124976564-4e0dd900-dfe4-11eb-9ad7-b69d717e3b9a.JPG)

**Comment by anhredweb** [comment]
Hi @stevejburge 
Please help for review the PR: https://github.com/TaxoPress/TaxoPress/pull/703, detail at description of the PR
Thanks.

**Comment by anhredweb** [comment]
Hi @stevejburge 
Thanks for your feedback. We share to you the reason at https://github.com/TaxoPress/TaxoPress/pull/703#discussion_r676391624.

Best regards.
