### ISSUE TITLE
Able to create new Post with existing Post name

### ISSUE THREAD

**Issue by Sankari44** [TaxoPress/TaxoPress#638]
In Post->Add new, can able to create a new post with existing post name. No error message pop-up by creating a new post with same name of already created post.
![Screenshot (497)_LI](https://user-images.githubusercontent.com/81978938/125179156-878b4380-e1a0-11eb-8527-6dcfd45c11ff.jpg)

**Comment by stevejburge** [comment]
Sorry, not a TaxoPress issue
