### ISSUE TITLE
Change color of promo banner

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#647]
Let's use #1F48AC
<img width="1095" alt="Screen Shot 2021-07-12 at 4 13 31 PM" src="https://user-images.githubusercontent.com/3868028/125349967-27290d00-e32c-11eb-9272-f9442e8cba2a.png">

Also #1F48AC here.
The red on yellow is hard to read. We can #1F48AC for the font and H2 for the heading

<img width="944" alt="Screen Shot 2021-07-12 at 4 14 08 PM" src="https://user-images.githubusercontent.com/3868028/125350099-4b84e980-e32c-11eb-9197-ef490ba0d982.png">

**Comment by stevejburge** [comment]
@olatechpro  No big deal, but it's still purple for me

**Comment by olatechpro** [comment]
Wait... You mean we should change the purple background too?

**Comment by stevejburge** [comment]
Yes, sorry. The purple is from Publishpress
