### ISSUE TITLE
Taxonomy label not appearing in WooCommerce

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#648]
While testing the compatability of TaxoPress and WooCommerce. The taxonomy "Product Shipping Classes" does not appear under the 'Products' main menu.

1. Click 'TaxoPress' tab
2. Click on 'Taxonomies' sub tab
3. Observe taxonomy 'Product shipping classes' has "products' as a "Post Type" under said column
4. Then click on or hover cursor over 'Products' tab
5. Obeserve there is no label "Product shipping class" or "Shipping class"

Since "Product categories" and "Product tags" have the 'Products' post type and their labels appear under the "Products" tab, one might expect that the label for "Product shipping classes" would appear under the same tab since it meets the same criteria..

![Product Shipping classes missing](https://user-images.githubusercontent.com/79052272/125357873-70c22980-e325-11eb-91ab-40035999f136.png)

 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.114

**Comment by olatechpro** [comment]
@stevejburge, I don't understand what this issue is or how it's related to taxopress.

**Comment by Bachynski** [comment]
The taxonomy is created by taxopress

**Comment by Bachynski** [comment]
That's how I see it.

**Comment by stevejburge** [comment]
@Bachynski This does work if you enable "Show in admin menus'

<img width="768" alt="Screen Shot 2021-07-12 at 8 41 46 PM" src="https://user-images.githubusercontent.com/3868028/125372675-aed54280-e351-11eb-88f1-af23a12e40d3.png">

**Comment by Bachynski** [comment]
Fair enough.

**Comment by olatechpro** [comment]
Issue exist due to taxonomy settings
