### ISSUE TITLE
Taxonomy missing - WooCommerce

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#650]
While testing the compatibility of TaxoPress and WooCommerce. When you go to 'Manage Terms' and choose "products" as post type and click the "Change Selection" button, you are redirected to the "Product Type" taxonomy, however, when you click on the 'Taxonomies' tab to bring up the taxonomies list "Product Type" is not listed.

1. Click 'TaxoPress' tab
2. Click on 'Manage Terms' sub tab
3. Click on the drop down menu that says 'Posts' and replace it with "products
4. Click the 'Change Selection' button and observe the brown message "You currently use the custom post type :Products" and the taxonomy "Product Type"
5. Click 'TaxoPress' Tab
6. Click "Taxonomies' sub tab and observe no Taxonomy with the name "Product type".

One would expect that if another part of 'TaxoPress' says a taxonomy exists, it would appear under the "Taxonomies" list.

 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.114

**Comment by olatechpro** [comment]
same as #651 .

Taxonomy not listed due to taxonomy settings
