### ISSUE TITLE
"Maximum terms to display" in 'Terms for Current post' accepts negative value.

### ISSUE THREAD

**Issue by Sankari44** [TaxoPress/TaxoPress#654]
Taxopress->Terms for Current post->Maximum terms to display accepts negative values are accepted.
But negative values are not acceptable. Without popping any error message, the settings are updated successfully.
![Screenshot (511)_LI](https://user-images.githubusercontent.com/81978938/125397711-28296100-e363-11eb-80a6-85e636a3639a.jpg)
![Screenshot (512)](https://user-images.githubusercontent.com/81978938/125397717-2c557e80-e363-11eb-9f27-89b58fbe1b67.png)

**Comment by olatechpro** [comment]
This is same as #637 #634 #627
