### ISSUE TITLE
Couldn't open related posts from home page.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#671]
1. Select Taxopress -> Settings -> Related Posts  
2. Check the field "Automatically display related posts into feeds"
3. In 'Automatically display related posts into post content' -> homeonly

Create few related posts and check the homepage for the related posts.

Related posts in homepage is not displayed as a link. Couldn't open related posts from home page. Whereas related posts are shown in links under the posts.

![relatedpost in homepage](https://user-images.githubusercontent.com/83974581/125694776-1afe1d3d-d569-4880-8320-ca5270f7c1e1.JPG)

![setings](https://user-images.githubusercontent.com/83974581/125996898-2ab8d8d8-4643-49e7-82f2-2ae7a2f92b96.JPG)
![settings](https://user-images.githubusercontent.com/83974581/125996899-fe52f937-88ff-4434-bdf2-82b821bb2638.JPG)

**Comment by stevejburge** [comment]
@sathyapriya91 Thanks for this. Could you share a screenshot of your settings in "Related Posts"?

**Comment by sathyapriya91** [comment]
please check the uploaded screenshots.

**Comment by stevejburge** [comment]
@sathyapriya91 sorry, nothing attached

**Comment by sathyapriya91** [comment]
![setings](https://user-images.githubusercontent.com/83974581/126003473-8dc3af8e-241e-484d-8841-b094eb352068.JPG)

![settings](https://user-images.githubusercontent.com/83974581/126003474-58e9a6a2-0925-4553-9565-7881ed75f521.JPG)

**Comment by stevejburge** [comment]
thanks. Please make sure you are updated to the latest version of Taxopress

**Comment by sathyapriya91** [comment]
Checked in the latest version 3.1.2. Still reproducing. Attaching the screenshots with this.
![rp one](https://user-images.githubusercontent.com/83974581/126226563-cd53e351-992a-4c1b-ae50-ba231bfbf839.JPG)
![settings](https://user-images.githubusercontent.com/83974581/126226567-3032fa41-f289-4114-9a79-13e0eb5a108c.JPG)
![settings1](https://user-images.githubusercontent.com/83974581/126226568-e4c63a73-0361-479a-9fbd-a121f6aabbe5.JPG)

**Comment by stevejburge** [comment]
@sathyapriya91 This is mysterious one.

- Can I ask where you're testing this? Is it localhost?
- Can you confirm on a 2nd website?
