### ISSUE TITLE
Creating a slug - is an underscore considered a dash?

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#674]
I've noticed that an underscore can be used  instead of a dash in creating slugs although the note on slug creation states that only numbers, letters and **dashes** can only be used. I can confirm any other symbol or punctuation cannot be used, so is an underscore considered a dash by TaxoPress?

**Comment by stevejburge** [comment]
@Bachynski Could you share a screenshot of where you see the dash mentioned?

I see this:
<img width="742" alt="Screen Shot 2021-07-16 at 1 27 35 PM" src="https://user-images.githubusercontent.com/3868028/125986325-b5773fcf-c307-41d4-86c6-773878d28de0.png">

**Comment by Bachynski** [comment]
I'll get you one by the end of the day. I'm tied up at work today

**Comment by Bachynski** [comment]
@stevejburge 

![Slug issue](https://user-images.githubusercontent.com/79052272/126015305-086b0532-facd-413e-8f1e-cb7d12571e11.PNG)

**Comment by stevejburge** [comment]
@Bachynski Good catch, thanks

**Comment by olatechpro** [comment]
@stevejburge , what's the issue here and your adjustment ?

**Comment by stevejburge** [comment]
@olatechpro let's copy the WordPress default text please:

Default is: "The “slug” is the URL-friendly version of the name. It is usually all lowercase and contains only letters, numbers, and hyphens."


![Screen Shot 2021-08-19 at 9 29 39 AM](https://user-images.githubusercontent.com/3868028/130077205-cab4e980-4626-466b-80a5-59bdcf0df0fd.png)
