### ISSUE TITLE
Display format are not in the selected List(UL/LI)

### ISSUE THREAD

**Issue by Sankari44** [TaxoPress/TaxoPress#677]
Taxopress->Terms Display->Display format-> while List(UL/LI) is selected, it shows in the Cloud format not in the List format.
![Screenshot (518)_LI](https://user-images.githubusercontent.com/81978938/125873869-58ae7ea2-df83-481d-9aba-e80825259ce3.jpg)
![Screenshot (517)](https://user-images.githubusercontent.com/81978938/125873880-11b3b62d-ffea-4f79-9148-6c74cc87026d.png)

**Comment by olatechpro** [comment]
I just tested this now and it works fine, please confirm what you're seeing is really the the result from the tag cloud created with terms display by enable option to show title in output to be sure.

@Sankari44 @stevejburge
