### ISSUE TITLE
"Tags" are not in the selected order

### ISSUE THREAD

**Issue by Sankari44** [TaxoPress/TaxoPress#678]
Taxopress->Settings->Administration->Click tags order-name(desc-inverse alphabetical) order is selected but it shows in the random order not in the reverse alphabetical order
![Screenshot (520)](https://user-images.githubusercontent.com/81978938/125895818-4b0c4c4a-1b76-4343-8be5-4a57639a5b83.png)
![Screenshot (521)](https://user-images.githubusercontent.com/81978938/125895826-5e8565c7-f441-4f68-bf5d-389581151ff7.png)

**Comment by stevejburge** [comment]
Sorry, this is mis-understanding. The order only applies to the admin area, underneath posts
