### ISSUE TITLE
Homepage displays "No related posts" along with the content of the post.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#686]
1. Select Taxopress -> Settings -> Related Posts
2. Check the field "Automatically display related posts into feeds"
3. In 'Automatically display related posts into post content' -> all
4. Create posts without any related contents in it and check the homepage for the related posts.

Homepage displays "No related posts" along with the content of the post. This may end up in confusion for the user.

Whereas it is displayed separately and looks perfect under the posts created. 

![rp homepage](https://user-images.githubusercontent.com/83974581/126002179-19885062-7ceb-4c3f-b357-4896b5efad5e.JPG)

![rp in posts](https://user-images.githubusercontent.com/83974581/126002182-46b2955f-ab8b-413f-b04b-3891638a969f.JPG)

![settings](https://user-images.githubusercontent.com/83974581/126002183-1e36c444-dddd-4ab7-9367-5fa9de98b3e0.JPG)

**Comment by stevejburge** [comment]
@sathyapriya91 Can you update your version of TaxoPress, please. Are you testing with 3.1.1?

https://wordpress.org/plugins/simple-tags/

**Comment by sathyapriya91** [comment]
I have the version 3.0.6 now. will update it to the latest version now.

**Comment by sathyapriya91** [comment]
Checked in the latest version 3.1.2. Still reproducing. Attaching the screenshots with this.
![no related](https://user-images.githubusercontent.com/83974581/126227096-636bbe9c-61d0-4e9f-847b-fdb990dc7be7.JPG)
![settings](https://user-images.githubusercontent.com/83974581/126226922-53470884-5574-4597-a4f0-83a55e583e88.JPG)
![settings1](https://user-images.githubusercontent.com/83974581/126226924-e87bfce5-5e9a-4c85-ad97-4041060e5052.JPG)

**Comment by stevejburge** [comment]
Thanks @sathyapriya91 

I'm still not able to see this in my testing. Do you have other posts with the "Uncategorized" category?

**Comment by olatechpro** [comment]
Hi @stevejburge, I think this is same as an issue you added as Enhancement but I don't know which milestone.

Giving user ability to hide message if no related post, or tag etc is found. 

That's what happen for example, in except which is displayed in homepage, line break are strip out and as a result, no related post message is showing with content thereby causing confusion. 

So, in sense, adding option for user to hide whole message if no post is found as planned is the way out.

**Comment by stevejburge** [comment]
Thanks @olatechpro. So the solution is probably this? https://github.com/TaxoPress/TaxoPress/issues/662

**Comment by olatechpro** [comment]
> Thanks @olatechpro. So the solution is probably this? #662

Correct. Yes, that's the solution.

**Comment by stevejburge** [comment]
Thanks. Closing in favor of that issue
