### ISSUE TITLE
"Auto terms" will not automatically add the keywords to the Tags box

### ISSUE THREAD

**Issue by Sankari44** [TaxoPress/TaxoPress#687]
Taxopress->Auto terms->Keywords list->Keywords are added for a new post.
While writing a new post including
![Screenshot (526)_LI](https://user-images.githubusercontent.com/81978938/126054650-7e9bebe4-1931-4feb-8744-dea2d03e5083.jpg)
![Screenshot (525)_LI](https://user-images.githubusercontent.com/81978938/126054654-88c8c2f6-7df4-45dc-8cfa-1297242b0356.jpg)
![Screenshot (523)](https://user-images.githubusercontent.com/81978938/126054657-0a314b77-e134-4ebb-b95a-0a37584d8b41.png)
 the given keywords, the Auto terms have not add the keywords to Tags box.

**Comment by olatechpro** [comment]
I just tested this feature and it works.

In the screenshot above, the feature has an 'add +' button which is for adding as many terms as possible seperately and not as shown in the screenshot attached where all words are put in the same box as that reads as a single term and of course, no match.

@stevejburge @Sankari44

**Comment by stevejburge** [comment]
@olatechpro Understood. I'll open a new ticket for improving the UI
