### ISSUE TITLE
Problem with Pro version

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#698]
> I just received the following error when updating the plug in:
> 
> The plugin MTYyNjM2NzUyOTpiNGJlZWRiMzEwMWU1OWQ3OThiODE3ZjhhOTRiOGZjYzo2MDg6NmNiMzM2NjFhOTI4NjBkYzE2ZGIyNzYwYjJiOTg1ZDk6aHR0cHNALy9kd2ViLm5ld3M6MA-NKnrPc/taxopress-pro.php has been deactivated due to an error: Plugin file does not exist.

I can confirm this has happened twice for me also

**Comment by olatechpro** [comment]
Does this happen during update or what? Trying to see what may have trigger it @stevejburge

**Comment by stevejburge** [comment]
Yes, I saw it earlier this week after moving to 3.1.2

The message appears at the top of the "Plugins" screen

**Comment by olatechpro** [comment]
I'm not really sure what could have been the reason as we didn't change the plugin file name and considering the fact the plugin file path is like this "MTYyNjM2NzUyOTpiNGJlZWRiMzEwMWU1OWQ3OThiODE3ZjhhOTRiOGZjYzo2MDg6NmNiMzM2NjFhOTI4NjBkYzE2ZGIyNzYwYjJiOTg1ZDk6aHR0cHNALy9kd2ViLm5ld3M6MA", it may be something else causing the issue. The reason plugin should deactivate after update is if plugin path/primary file name changed

**Comment by stevejburge** [comment]
@olatechpro Yes, in these cases the plugin does activate

Afterward, it can be safely re-enabled
