### ISSUE TITLE
Include or exclude post title in Auto-Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#701]
This could become part of this feature: https://github.com/TaxoPress/TaxoPress/issues/160

**Comment by anhredweb** [comment]
Hi @stevejburge 

We push MR: https://github.com/TaxoPress/TaxoPress/pull/705 for this issue.

Thanks.

**Comment by olatechpro** [comment]
Hi @stevejburge, is this request to give option to:

1.) Autolink tags found in post title ? (Post title will have tags link which shows tags found in title will have a link)
OR 
2.) Autolink post content based on tags found in post title ?

**Comment by stevejburge** [comment]
@olatechpro the original request was to avoid #1 

The user did not want autolinks in the title

**Comment by olatechpro** [comment]
We currently does not auto link post title. So, does that mean we're providing option for user to be able to auto link post title tags ?

Note, this is not same as the linked issue #160 which is to prevent auto link in certain html class like headers tags (h1, h2 etc) found in post content.

I just want to be sure as I don't see reasons behind linking post title tags.


@stevejburge

**Comment by stevejburge** [comment]
@olatechpro OK, if the code is written, let's call this a new feature. It does complement #160 so it can be next to it in the "Settings" area

**Comment by olatechpro** [comment]
All right @stevejburge
