### ISSUE TITLE
TaxoPress doesn't like repeat terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#722]
You can break Auto Links by using two examples of the same term next to each other:

![Screen Shot 2021-08-03 at 10 50 17 AM](https://user-images.githubusercontent.com/3868028/128036734-8f563657-e2ef-4a82-b258-d8bb4e14486d.png)

**Comment by olatechpro** [comment]
@stevejburge, can you explain this better? I'm not getting what the issue is

**Comment by stevejburge** [comment]
In the example above, I have "WordPress WordPress" in the text.

TaxoPress got confused and only acted on the second item

**Comment by olatechpro** [comment]
Just to be sure, both WordPress got linked but one didn't use correct case set in settings which is uppercase right. That's the issue?

@stevejburge

**Comment by stevejburge** [comment]
Yes, here's an example with 3 instances:

![Screen Shot 2021-08-03 at 11 44 53 AM](https://user-images.githubusercontent.com/3868028/128045638-bd783447-6b47-486c-bbe8-58cb8c079b77.png)

**Comment by olatechpro** [comment]
Hi @stevejburge. So, i did follow up on this issue and #724 when i noticed it still exist but just not consistent and later find out the conflict is with legacy auto link. 

<img width="1144" alt="legacy-conflict" src="https://user-images.githubusercontent.com/46832636/128317404-2e306b85-ccfc-4fd7-b55e-9204ed929a07.png">

For example, if the above section in screenshot attached is checked even auto link tags is disabled, it result in legacy auto link auto linking the content first before it reach the new UI hook( reason for the inconsistency as both hook are on same priority and whichever run first will determine the result).

So, i've fixed it by making sure legacy never run unless the user enable it on the auto link legacy page.

I'm putting it here in case we get future report from users of auto link not working as expected, the solution will be to uncheck 'Auto links tags' as shown in the screenshot below as they can't use both legacy and new auto link together as it means both will filter content. 

<img width="1138" alt="solution" src="https://user-images.githubusercontent.com/46832636/128318137-83643e9b-c8d1-4128-8ce8-1c03cc0c6c95.png">
