### ISSUE TITLE
Maximum number of links for the same tag *

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#723]
This isn't working for me: "Maximum number of links for the same tag *"
![Screen Shot 2021-08-03 at 10 52 13 AM](https://user-images.githubusercontent.com/3868028/128037016-adaaeca6-97fd-4c1c-b877-391626d72a67.png)

**Comment by olatechpro** [comment]
There's possibility this issue is as a result of #721 as everything works fine while testing now. You can reopen with more details if issue still exist after testing new update .
