### ISSUE TITLE
Exclude Auto Links not working

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#724]
I'm having no luck with these settings:

![Screen Shot 2021-08-03 at 10 53 47 AM](https://user-images.githubusercontent.com/3868028/128037294-842681ac-a8c3-4193-a685-eafb83012070.png)

**Comment by olatechpro** [comment]
Hi @stevejburge , do you mean tags inside <h1> tags still got linked after checking the option?

**Comment by stevejburge** [comment]
Correct, I tried to exclude H1 in this example:

![Screen Shot 2021-08-03 at 11 14 33 AM](https://user-images.githubusercontent.com/3868028/128040619-14674989-8c6a-4a55-93c2-1e561b66e2ed.png)

**Comment by olatechpro** [comment]
Okay, can you confirm if others works?
Just checked now and it seems it's only h1 that's not working from my end, I want to be sure I get all issue @stevejburge

**Comment by stevejburge** [comment]
It seems to be working correctly if I save the post

So I apply the H1 setting, then save and refresh the post
