### ISSUE TITLE
Script?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#725]
Let's make this clearer. What do we mean by "Script"?
![Screen Shot 2021-08-03 at 11 41 25 AM](https://user-images.githubusercontent.com/3868028/128045093-7f00566b-ca71-45c3-91ef-d04aea2f795d.png)

**Comment by olatechpro** [comment]
<script> will be self explanatory then but the reason I didn't put the tag is because it <script just like <h1 for example can have attributes and putting <script> straight away may leave the impression of it only working when it's a script without attributes for example, <script name="Test" ></script> etc

**Comment by stevejburge** [comment]
OK, so would it cover the code block in Gutenberg? Could it cover <pre> tags?

**Comment by olatechpro** [comment]
It fixes issues like this:
#130

@stevejburge

**Comment by olatechpro** [comment]
That make sense, so we can add as many options as we want for example <pre etc.

Can I see the raw code of the pre tag so I can test and add if necessary?
@stevejburge

**Comment by stevejburge** [comment]
Here's a "code" block in Gutenberg

<img width="680" alt="Screen Shot 2021-08-03 at 4 25 45 PM" src="https://user-images.githubusercontent.com/3868028/128081401-4a0d657c-6f85-4ef5-9c6d-89891ae89306.png">
<img width="700" alt="Screen Shot 2021-08-03 at 4 25 37 PM" src="https://user-images.githubusercontent.com/3868028/128081406-2e6c934f-1499-4578-a968-307b38919986.png">

**Comment by olatechpro** [comment]
Okay, will add "Pre" as well just incase anyone want to prevent tag inside.

So, what's your conclusion on script name now and should this new element be Pre by name as well or I should give them all their opening and closing tags including all headings?
@stevejburge

**Comment by stevejburge** [comment]
Maybe the label is this ...

 "script" and "pre" elements

This can go at the bottom of the screen. In a future release, we can allow more flexiblity

**Comment by olatechpro** [comment]
> Maybe the label is this ...
> 
> "script" and "pre" elements
> 
> This can go at the bottom of the screen. In a future release, we can allow more flexiblity

They have to be separate. 

Script is not same as pre and there may be people who will want to disable tag in script but not pre. 

So, under: script, we can have
- Pre
- Code which implied no tags inside < code> element.
-
When I asked for the new name, it's bavuse I think yh

**Comment by stevejburge** [comment]
OK, maybe these are separate checkboxes under H5 and H6?

script and pre?

**Comment by olatechpro** [comment]
Just to be clear, we gave that section to give opportunity to prevent auto links inside some html element which they are:

- H1  ==> < h1>content</ h1>
H2, h3, h4, h5, h6.

- Script ==> <script > </script>
So, we have script already in the option and it's right above the Heading checkboxes. 

Newly proposed:
- Pre => Prevent auto links of tags found inside <pre >content< / pre> if enable 

- Code => Prevent auto links of tags found in <code > content </ code>


So, that been said, I thought you opened this issue to propose changes to the name given to them? If not, can you explain better what the improvement is aside the newly proposed element to be added and are you asking me to move the script and the new options (pre and code) under h1 to h6 items ? 

@stevejburge

**Comment by stevejburge** [comment]
Yes, I think this new proposal is a good idea.

We could not have an option that just says "script". That would be confusing
