### ISSUE TITLE
Mandatory field "Maximum terms to display" in Terms display accepts numbers without any limits.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#727]
1. Select Taxopress -> Terms Display
2. Edit the available terms display
3. In mandatory field "Maximum terms to display" enter N number of numbers and save(670670670670670670670670670670670670)

There could be a limit in the mandatory field for better usage.

Same happens in other mandatory fields font size minimum and font size maximum.

![manda](https://user-images.githubusercontent.com/83974581/128071488-ee2f23d3-75d4-44e6-a079-a8669e221eef.JPG)
![mandatory](https://user-images.githubusercontent.com/83974581/128071491-a5d80a08-54e5-4136-9dc6-21132d36efcc.JPG)

**Comment by olatechpro** [comment]
@stevejburge, can you suggest a maximum limit for these issue and similar issues as I don't see how this is an issue considering the fact the use case is unrealistic?

**Comment by stevejburge** [comment]
Maybe set a limit of 10 characters?

**Comment by olatechpro** [comment]
> Maybe set a limit of 10 characters?

Number Input limit is not set by character length.

For example, minimum can be 1 while the maximum can be 10 which shows user can only enter between 1, 2,3,4,5,6,7,8,9,10 and not greater than @stevejburge

**Comment by stevejburge** [comment]
10 characters = 1,000,000,000
