### ISSUE TITLE
Creating Taxonomy - Taxonomy Slug. Should add a note that using lower case is normal to prevent confusion.

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#732]
https://user-images.githubusercontent.com/79052272/128204294-2ba2ffc3-daf7-4c19-b881-7509da4f0da0.mp4

When creating a new Taxonomy if one were to try and use capital letter to name a 'Taxonomy Slug', TaxoPress automatically converts to lower case. The problem is that this is not described in the descriptor below the editable field. Should add a note that using lower case is normal to prevent confusion.

**Comment by stevejburge** [comment]
Thanks. Yes, or automatically transform the characters to lowercase while typing

**Comment by olatechpro** [comment]
@stevejburge, what's the new description text?

**Comment by stevejburge** [comment]
@olatechpro Can we automatically transform to lowercase while typing?

**Comment by olatechpro** [comment]
> @olatechpro Can we automatically transform to lowercase while typing?

Isn't that how it currently work from your end?

**Comment by Bachynski** [comment]
@olatechpro it does work that way however I've noticed that not all the descriptors for slug creation aren't consistent. Some say that lower case is used and some don't, however both would have the auto conversion to lower case.

**Comment by Bachynski** [comment]
This wouldn't be the first time descriptions weren't consistent.

**Comment by stevejburge** [comment]
@olatechpro Yes, I think this works fine.

Description?
"Slugs can only use lowercase characters, numbers, and underscores."

**Comment by Bachynski** [comment]
@stevejburge That is the description I see in other places, however if you look at my video I included, it doesn't say that only lower case can be used.
