### ISSUE TITLE
Can't delete taxonomy

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#755]
I created a taxonomy by renaming an existing taxonomy using the "Slug" feature:
<img width="788" alt="Screen Shot 2021-08-09 at 3 26 36 PM" src="https://user-images.githubusercontent.com/3868028/128762867-0dd22554-5f22-4667-9dfd-44e110640295.png">

TaxoPress won't allow it to be removed and say it is an external taxonomy:
<img width="1122" alt="Screen Shot 2021-08-09 at 3 26 09 PM" src="https://user-images.githubusercontent.com/3868028/128762831-badf3f9c-d888-489c-adeb-44a8315fa4cb.png">

**Comment by olatechpro** [comment]
If this taxonomy wasn't originally created by TaxoPress. You can't delete as the original source code is inside the originating plugin. You can only deactivate @stevejburge

**Comment by olatechpro** [comment]
Unless you mean a new taxonomy is created entirely while the other still exist as a separate taxonomy? @stevejburge

**Comment by stevejburge** [comment]
So I made a copy of a taxonomy from another plugin

I can't delete the original taxonomy, or the copy taxonomy

**Comment by olatechpro** [comment]
After checking the complicity, i realised user should not be able to edit external taxonomy slug since we don't have control over the code.

**Comment by stevejburge** [comment]
@olatechpro Yes, good point

**Comment by olatechpro** [comment]
In addition, many plugin that register taxonomy will probably do so for a purpose and will reference the slug or get the taxonomy in their plugin by slug. So, allowing user to change the slug may break the site (This is the most important  reason why we shouldn't allow deleting or editing core function of an external taxonomy )

**Comment by stevejburge** [comment]
@olatechpro Agreed. Good thinking
