### ISSUE TITLE
Tag figure/figcaption invalid

### ISSUE THREAD

**Issue by ucallrt** [TaxoPress/taxopress#77]
Seems that Simple Tags is having an issue with reading and tagging captions. On any of my posts where there are captions on photos, I get this error: 

Warning: DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 3 in /home3/bikeworl/public_html/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 3 in /home3/bikeworl/public_html/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

This can be seen on this post:
https://www.bikeworldnews.com/2017/06/22/latest-uci-approved-frames-list-621/

**Comment by herewithme** [comment]
Hello @ucallrt 

Can you send me the HTML code from the WP visual editor (code tab)
Or the URL of the post concerned?

Have you tried the original replacement engine?
You must uncheck "Try new engine replacement?" In the "Autolinks" tab.

**Comment by ucallrt** [comment]
Unchecking 'Try new engine replacement' solved the issue after I re-updated the post. Thanks!

Here's the original HTML, though:

With just nine days before the start of the 104th Tour de France with a time trial in Dusseldorf, Germany, the UCI has posted their latest approved list for frames and forks.

Ahead of the Grand Depart, there are a few big names on the list. Boardman gets their range topping aero road bike approved, though it will not be raced at the Tour. Japanese brand Boma has their new Swoop TRK track bike approved. This $3,580 frame, or $5,370 depending on carbon used, is targeted at the recent changes made in the Olympic cycling events on the track.

[caption id="attachment_80195" align="alignright" width="298"]<a href="https://www.bikeworldnews.com/2017/06/22/latest-uci-approved-frames-list-621/colnago_v2-r__77499-1496339104/" rel="attachment wp-att-80195"><img class="wp-image-80195 size-medium" src="https://www.bikeworldnews.com/wp-content/uploads/2017/06/Colnago_V2-R__77499.1496339104-298x300.png" alt="" width="298" height="300" /></a> The Colnago V2-R is coming on June 26th.[/caption]

Team UAE-Abu Dhabi's supplier, Colnago, has the new V2-R in rim and disc brake version approved. The successor of the V1, The V2-R is rumored to be a climber's bike with aerodynamic considerations. More to come on 6/26.

Speaking of aero frames, Guerciotti adds the aero Eureka DX 50 to their line-up.

Without a time trial bike listed on their website, the "TT" is the bike that Silber Pro Cycling has been racing in North America this year. From images of the bike from Silber's page, it features a bayonet style front fork and possibly replaceable stem that can either be run flat with the top tube or as a riser to get the bars higher. The frame features wheel hugging cut outs on the down and seat tubes. Water bottle mounts on the downtube provide a high or low mounting option.

Pinarello snuck in their new top of the line F10 race bike with disc brakes. I'd be surprised to see many Team Sky riders running discs for the Tour, but on days featuring big descents, you could see them out there.

[caption id="attachment_80193" align="alignright" width="300"]<a href="https://www.bikeworldnews.com/2017/06/22/latest-uci-approved-frames-list-621/crux/" rel="attachment wp-att-80193"><img class="size-medium wp-image-80193" src="https://www.bikeworldnews.com/wp-content/uploads/2017/06/Crux-300x165.jpg" alt="" width="300" height="165" /></a> The new Specialized S-Works Crux.[/caption]

Finally, the big red S has their new Crux approved well before cross season arrives. The new race bike from Specialized offers additional clearance over past Crux models, which would be great for cyclists not worrying about the UCI's tire width limits. With the Diverge carrying the flag for gravel and adventure racing, the Crux shed some of the additional odds and ends that were there to make it a little more versatile and turns it into an all-out racing machine. There have been rumors of a hydrophobic property coming for top level S-Works paint jobs to help the Crux keep the mud and grime from accumulating on the frame.
<h3><a href="https://www.boardmanbikes.com/gb_en/">Boardman</a></h3>
AIR – Five sizes from XXS-L
Approved 6/15/17 – BOAR-AIR-RD

[caption id="attachment_80194" align="alignright" width="300"]<a href="https://www.bikeworldnews.com/2017/06/22/latest-uci-approved-frames-list-621/swp_trk/" rel="attachment wp-att-80194"><img class="size-medium wp-image-80194" src="https://www.bikeworldnews.com/wp-content/uploads/2017/06/swp_trk-300x150.png" alt="" width="300" height="150" /></a> Boma Swoop TRK[/caption]
<h3><a href="http://www.boma.jp/en/">Boma</a></h3>
<a href="http://www.boma.jp/en/products/frame_set/swooptrk/">Swoop TRK</a> – Three sizes from S-L
Approved 6/15/17 – BOMA-SW-TR
<h3><a href="http://www.colnago.com/">Colnago</a></h3>
V2-R Rim and Disc – Eight sizes from 42-58
Approved 6/19/17 – COLN-V2R-RD
<h3><a href="http://www.guerciotti.it/en/">Guerciotti</a></h3>
Eureka DX50 – Four sizes from S-XL
Approved 6/20/17 – GUER-EU1-RD
<h3><a href="http://www.jamisbikes.com/usa/index.html">Jamis</a></h3>
[caption id="attachment_80192" align="alignright" width="300"]<a href="https://www.bikeworldnews.com/2017/06/22/latest-uci-approved-frames-list-621/s3a-cowanaction/" rel="attachment wp-att-80192"><img class="size-medium wp-image-80192" src="https://www.bikeworldnews.com/wp-content/uploads/2017/06/s3a-cowanaction-300x197.jpg" alt="" width="300" height="197" /></a> Jamis' new TT bike under a Silber Pro Cycling rider.[/caption]

TT – Four sizes from S-XL
Approved 5/31/17 – JAMI-TT-TT
<h3><a href="https://ktmbikeindustries.com/">KTM</a></h3>
<a href="http://www.ktm-bikes.at/en/bikes/bikedetail.html?action=bike_details&amp;bike_id=100&amp;cHash=0717e128bfde3c119194c2f85670686b">Revelator Sky (Disc)</a> – Five sizes from 49-59
Approved 6/15/17 – KTM-REV3-RD
<h3><a href="http://www.pinarello.com/en/">Pinarello</a></h3>
<a href="http://www.pinarello.com/en/bikes-2017/road/dogma-f10">Dogma F10 (Disc)</a> – Eleven sizes from 44-62
Approved 6/19/17 – PINA-D10D-RD
<h3><a href="https://www.specialized.com/us/en">Specialized</a></h3>
<a href="https://www.specialized.com/us/en/bikes/road/cyclocross/s-workscrux/129089">Crux 18</a> – Seven sizes from 46-61
Approved 5/24/17 – SPE-CRU2-CX

**Comment by herewithme** [comment]
Thank you for the detail, I look at it in the next few weeks.
