### ISSUE TITLE
Issue with some character being typed: & and e

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#770]
> Taxopress has some bug with the & symbol see screen shots of text and code

<img width="909" alt="Screen-Shot-2021-08-14-at-6 27 43-am-28c7f53e90302af8dbe061b9a977439d" src="https://user-images.githubusercontent.com/3868028/129453316-8fe7f4f3-deee-43b0-90aa-345f692c2c51.png">
<img width="1201" alt="Screen-Shot-2021-08-14-at-6 26 56-am-68730d90d3a20785cbf6a3ed01824a7d" src="https://user-images.githubusercontent.com/3868028/129453317-6af3a3be-290f-4296-8554-a0c38de2d841.png">

**Comment by stevejburge** [comment]
> We are unable to type the letter "e" in the text editor of our Wordpress site.
> I have confirmed that TaxoPress is the plugin that causes this.
> Here is a link to a video of it happening.

https://www.loom.com/share/70d7dde4553743a9a7ee12ed74731b60?sharedAppSource=personal_library

**Comment by stevejburge** [comment]
> When I try to add a link in the text editor I can't type the letter e
> All other letters of alphabet work - only letter e can not be typed.
> If we disable Taxopress then we can type the letter e but if you again enable taxopress the letter e will not type.

![Screenshot-2021-07-28-at-07-35-05-Edit-Page-%u2039-Cash-For-Junk-Cars-fc68d13964e469fb8b7e05d23b2129fb](https://user-images.githubusercontent.com/3868028/129453409-b102e01f-3a56-4e14-b6fb-3a421c7c91c3.png)

**Comment by olatechpro** [comment]
Hi @stevejburge , i fixed other issue but can't relate with the '&' symbol, what's really the issue ?

**Comment by olatechpro** [comment]
Nevermind, i've been able to recreate the issue with autolink @stevejburge

**Comment by stevejburge** [comment]
Great, thanks @olatechpro
