### ISSUE TITLE
Issue with Auto Links in H2 tags

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#771]
One user is reporting that the links still appear in H2
![Screen Shot 2021-08-14 at 12 49 24 PM](https://user-images.githubusercontent.com/3868028/129453508-b4010472-f328-4177-ac8a-5571ccce412a.png)

**Comment by olatechpro** [comment]
Hi @stevejburge, check my explanation here. As that's the possibility #722

**Comment by olatechpro** [comment]
So, the solution is disabling legacy as that may be the one that replace the tag inside h2
@stevejburge 
<img width="1138" alt="128318137-83643e9b-c8d1-4128-8ce8-1c03cc0c6c95" src="https://user-images.githubusercontent.com/46832636/129453669-c1d610ce-0bcc-45fc-91eb-9e6cdec5dd2a.png">

**Comment by stevejburge** [comment]
Thanks. I'll test and ask the customer
