### ISSUE TITLE
Update the menu link for "Auto Terms"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#775]
Let's exactly take the same approach as with "Taxonomies" and "Auto Links"

Tabs can be: 
- General (Choose post type and category)
- Terms to Use
- Options
- Old Content

**Comment by olatechpro** [comment]
@stevejburge , i'm thinking we should port all old auto terms in new UI. This way, we can scrap auto terms legacy and remove option in current settings but that means free version may have more than 1 existing auto terms.

What do you think and how do we enter old auto terms data ?

**Comment by stevejburge** [comment]
Thanks @olatechpro 

Is there a big advantage to removing the old legacy settings?

If we do, I'd like to keep our "1 Setting in Free. Unlimited in Pro" approach. We can always offer people a Pro membership if they complain

**Comment by olatechpro** [comment]
If we didn't remove old settings, it mean previous auto terms configuration will always run and user won't see screen to edit their previous settings or you want us to move whole current auto terms screen to legacy ?
@stevejburge

**Comment by stevejburge** [comment]
Yes, moving the old system to Legacy is the alternative.

Maybe you're correct. We can't move everything to Legacy and maybe it will cause problems in the future

**Comment by olatechpro** [comment]
Right now, moving the whole aut terms screen to legacy won't be easy.

We can't put a [form] inside another [form] and auto terms screen settings action can't be put in current settings page form.

So, what's your decision on how to handle users old auto terms data?

**Comment by stevejburge** [comment]
I'm happy to go with your recommendation. Let's port all old auto terms into the new UI.
