### ISSUE TITLE
Auto link selective html tags

### ISSUE THREAD

**Issue by nms73631** [TaxoPress/taxopress#78]
Hello there!
Thanks for the fantastic plugin!

I'm having an issue where the plugin auto links tags inside a heading like H1 or other things and since it's injecting an anchor link tag inside the parent tag it makes the styles mixed with each other.
For example in my case it auto links a tag inside an H1 and the font size for the linked tag becomes different than the H1
It would be really nice if it was possible to make the plugin only auto link from texts inside a p tag

Can you please fix this or give me a temporary issue?! with CSS, jQuery or PHP?

Thanks a lot :) 👍

**Comment by herewithme** [comment]
A web page to show me?

**Comment by nms73631** [comment]
Thanks for the reply :)
I have managed to overwrite the styles so they don't get mixed.

here's the test page for you to see:
http://presschi.com/%D9%BE%D8%B3%D8%AA-%D8%AA%D8%B3%D8%AA%DB%8C-7/

I have also described the situation in an screenshot that I've attached to this comment.
![image](https://user-images.githubusercontent.com/25494156/28056308-ca9d4c52-6631-11e7-9157-18436aa4373a.png)

**Comment by nms73631** [comment]
I think if there was an option to only scan the texts of the "p" tag and not the whole document like h1 and ... for tags this problems would be solved.

**Comment by herewithme** [comment]
It is certainly a good idea to exclude the titles of the replacements, we should foresee an evolution in this direction.

In the short term, there must be a solution by directly modifying the plugin: https://github.com/BeAPI/simple-tags/blob/master/inc/class.client.autolinks.php

Replace 
`foreach ( $xpath->query( '//text()[not(ancestor::a)]' ) as $node ) {`

By
`foreach ( $xpath->query( '//text()[not(ancestor::a)][not(ancestor::h1)]' ) as $node ) {`

But you must use the "new" replacement engine, not the old alternative.

**Comment by nms73631** [comment]
Thanks your solution solved the mentioned problem but using the new replacement engine caused countless "Warning: DOMDocument::loadHTML(): Tag article invalid in Entity, line: 55 in /home/wp_nnv6p5/presschi.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204" errors.
http://presschi.com/%D9%BE%D8%B3%D8%AA-%D8%AA%D8%B3%D8%AA%DB%8C-7/

![image](https://user-images.githubusercontent.com/25494156/28109341-0be91862-6704-11e7-8f21-f684951d1463.png)
![image](https://user-images.githubusercontent.com/25494156/28109494-8089d79c-6704-11e7-8689-4610dbdae7eb.png)

**Comment by nms73631** [comment]
would you please tell me how can I resolve this warning errors?

**Comment by nms73631** [comment]
Hi there!
Any ideas how to fix these errors when I activate the replacement engine?!
