### ISSUE TITLE
Undefined property: WP_Post_Type::$taxonomy

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#783]
> I am seeing this error in our logs being reported multiple times:
> 
> PHP Notice: Undefined property: WP_Post_Type::$taxonomy in /home/…/wp-content/plugins/simple-tags/inc/class.client.php on line 71

https://wordpress.org/support/topic/undefined-property-wp_post_typetaxonomy/

**Comment by olatechpro** [comment]
We fixed this already
