### ISSUE TITLE
Linked terms: Add one term, the others are added automatically

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#801]
One request for this feature: Auto Assign Post Category https://wordpress.org/plugins/auto-assign-post-category/

Single tags can be mapped to multiple categories
Useful for post authors to assign multiple categories automatically.
Even you update the existing posts it will assign categories.

**Comment by stevejburge** [comment]
One more:

>  is there a way to automatically assign tags/taxonomies to categories?
> For instance post gets created and CategoryA is assigned to it, so automatically the post also gets assigned determined tags/taxonomies that we decide are related to CategoryA ?

**Comment by stevejburge** [comment]
One more:

> When a writer creates a new post on our site under a specific category, I'd like it to automatically tag the post as well. For example, a new post with category "Recruitment" would automatically have a tag of "closed" and "recintel" added. I'd need to have different rules for different categories. Is this possible?

**Comment by ojopaul** [comment]
### Additional note from slack:
- Basically, "If term A is added, also add terms B, C and D'
- Or perhaps with our new feature ...
- "If term A (or a synonym of term A) is added, also add terms B, C and D"
- Maybe you can only link terms in the same taxonomy?
