### ISSUE TITLE
Add different CSS classes to different displays

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#809]
> I add different CSS classes to the different taxonomies? So for example if I have one custom taxonomy for authors and one for books, I would like to use a red background for author links and blue background for book links.

Can we add a CSS classes option to:

- Term for Current Post
- Term Display
- Related Post
- Auto Links

**Comment by stevejburge** [comment]
The customer is asking to add CSS to "Terms for Current Post" but it would be a useful feature for all our displays

**Comment by olatechpro** [comment]
> The customer is asking to add CSS to "Terms for Current Post" but it would be a useful feature for all our displays

I still don't understand, are we adding a text input field and naming it custom css or we're just applying this to the tag out.

Is this applying to the term wrap div or every link?
