### ISSUE TITLE
Improve the UI for Auto Terms "Keywords list"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#822]
<img width="1208" alt="Screen Shot 2021-09-01 at 1 14 01 PM" src="https://user-images.githubusercontent.com/3868028/131714767-680548da-10a0-4a6f-94af-401e24f1c0dd.png">

**Comment by olatechpro** [comment]
This UI is already deprecated since we have new screen for auto terms #833 #833
