### ISSUE TITLE
CSS not working for "Terms for Current Post" div

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#823]
In my testing, the link CSS is working for single "Terms for Current Post" links, but not for the whole div.

This is my example, using the same CSS for "Terms for Current Post" and also "Terms Display"

<img width="723" alt="Screen Shot 2021-09-01 at 2 15 41 PM" src="https://user-images.githubusercontent.com/3868028/131723054-3bb231f8-3848-44e7-9b6a-9f61c4a24675.png">

**Comment by stevejburge** [comment]
@olatechpro Here's what I see
<img width="980" alt="Screen Shot 2021-09-01 at 3 14 33 PM" src="https://user-images.githubusercontent.com/3868028/131730407-bfaf6720-49b8-4129-a2f4-75904373bc76.png">

**Comment by olatechpro** [comment]
You're suppose to enter the class name, not with dot (.) since normally, you don't give a div class with the dot value. I only put dot compatibility in some cases.

**Comment by stevejburge** [comment]
@olatechpro Ah, OK. Let's clear that up, please

Maybe a line of instruction under the settings?

**Comment by olatechpro** [comment]
Well, I think it's pretty straight forward for people that really need it. For example, if I need to add class to html attribute, I won't definitely put < div class =".class-name"? But of course, we can add the description under the input as you suggested

**Comment by stevejburge** [comment]
Yes, please

Let's explain the required format. For example, do people need the dot?
