### ISSUE TITLE
Auto Links has a bug with "

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#824]
I discovered it on this post: https://taxopress.com/taxopress-3-2-2/

This is the text in the post. There's a link with "Terms Display" in it:
<img width="563" alt="Screen Shot 2021-09-01 at 3 20 46 PM" src="https://user-images.githubusercontent.com/3868028/131731188-8565123c-54d5-4862-b2b9-62ea77a35ed1.png">

And this was the final output:
<img width="841" alt="Screen Shot 2021-09-01 at 3 17 04 PM" src="https://user-images.githubusercontent.com/3868028/131731053-5917b313-c1e8-44ca-9e51-030eaeb102ba.png">

**Comment by olatechpro** [comment]
Maybe we should release a bug fix release tomorrow as this can't wait till auto terms is completed? @stevejburge

**Comment by stevejburge** [comment]
I think this is going to be a fairly rare one. 

Let's wait unless we get a few complaints
