### ISSUE TITLE
Add option to exclude/disable auto link for post

### ISSUE THREAD

**Issue by olatechpro** [TaxoPress/TaxoPress#826]
Just like Auto terms, enabling option to exclude/disable auto link for an individual post may be a good feature as we uncover and fix bugs related to auto link in some posts.

This way, the client will be able to use auto link on other posts while we fix whatever the issue may be and for whatever reason a client may not want a post to be auto link, it may come in handy too.

What's your take on this @stevejburge and do you feel we should include this in current milestone or it should wait ?

**Comment by stevejburge** [comment]
@olatechpro 100% a good idea. I've added this to our follow-up release for Auto-Terms
