### ISSUE TITLE
Use one box for "All terms" or "Specific terms"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#843]
It's not all clear that this is an A/B or Yes/No choice

"Specific terms only" would be a good label

<img width="852" alt="Screen Shot 2021-09-13 at 12 40 48 PM" src="https://user-images.githubusercontent.com/3868028/133123564-f8ec0778-874b-4f6c-a3b0-8a00cb15e723.png">

**Comment by olatechpro** [comment]
You mean, like this and that's all.No changes for options description ?
@stevejburge 
![label](https://user-images.githubusercontent.com/46832636/133124284-80f495c7-655c-4849-bcb2-b57693bbebfc.jpg)

**Comment by stevejburge** [comment]
Yes, that's it.

Label: Which terms to use?

Description: Use all the terms in the selected taxonomy. Please test this option carefully as it can use significant server resources if you have many terms.

Description: Use only some terms in the selected taxonomy. Use the boxes below to choose the terms to use.
