### ISSUE TITLE
Possible to use auto-complete

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#846]
@olatechpro Feel free to say "no", but is there any way we can use Autocomplete for these boxes?
![Screen Shot 2021-09-13 at 1 22 50 PM](https://user-images.githubusercontent.com/3868028/133128880-e269efdc-bb77-4437-b155-5bda631d8d57.png)

**Comment by olatechpro** [comment]
Sure, we can use auto complete features on them.

**Comment by stevejburge** [comment]
Awesome, I think that will make it much easier to use.

I wonder, is there someway we could show a list of the terms? People could click on them to activate them? Similar to our own suggested tags feature?

**Comment by olatechpro** [comment]
> Awesome, I think that will make it much easier to use.
> 
> I wonder, is there someway we could show a list of the terms? People could click on them to activate them? Similar to our own suggested tags feature?

Make sense.

**Comment by stevejburge** [comment]
Thanks. It may not be perfect, but I'm thinking of the best and easiest way for people to see their terms

**Comment by stevejburge** [comment]
OK, this is worth thinking through carefully

We've had a request to use all word EXCEPT the ones chosen: https://github.com/TaxoPress/TaxoPress/issues/65

**Comment by stevejburge** [comment]
The same thing here too: https://github.com/TaxoPress/TaxoPress/issues/112

**Comment by olatechpro** [comment]
Are we suspending this for now or we're adding another input like text area for stop words?

Can't really understand the relation of linked issues to the auto complete we're adding for the boxes

@stevejburge

**Comment by stevejburge** [comment]
Maybe we need 3 options:

- Include all terms
- Include only specified terms
- Exclude only specified terms

**Comment by olatechpro** [comment]
Why can't user 
- include specified term
OR
- include all terms
AND
- exclude specified terms?
-
Any reason why exclude specified terms can't stay on it own giving user ability to use all terms but at the same time exclude certain terms ?

@stevejburge

**Comment by stevejburge** [comment]
Yes, sorry, that is what I meant

- Include all terms
- Include all terms except specified terms
- Include only specified terms

**Comment by olatechpro** [comment]
Maybe we should go for a single text area for each specified option and allow separating multiple terms with comma (This will integrate well with the auto complete and click feature in term of usability) ?

That way, the page won't be messy.

**Comment by stevejburge** [comment]
Yes, I'm willing to give that a try
