### ISSUE TITLE
Add an advertising sidebar banner

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#848]
In the Free version, let's add a sidebar banner to all admin pages:
![Screen Shot 2021-09-13 at 1 24 56 PM](https://user-images.githubusercontent.com/3868028/133129211-10fac8cc-282d-4d1c-8acd-cd976bfb030a.png)

https://wordpress.org/plugins/peters-login-redirect/ has a good example:

<img width="364" alt="Screen Shot 2021-09-13 at 1 26 40 PM" src="https://user-images.githubusercontent.com/3868028/133129537-eb704ab1-872b-49e1-970c-85330c1a204f.png">

**Comment by ojopaul** [comment]
What should be the content of the sidebar banner ?

**Comment by stevejburge** [comment]
@ojopaul 

Title: Upgrade to TaxoPress Pro"

Description: Enhance the power of TaxoPress with the Pro version:

Unlimited “Term Display”
Unlimited “Terms for Current Posts”
Unlimited “Related Posts”
Unlimited “Auto Links”
Unlimited “Auto Terms”
Unlimited “Suggest Terms”
Fast, professional support
No ads inside the plugin


We can also duplicate the support box shown in the image above, please

Need TaxoPress Support

First link: https://wordpress.org/support/plugin/simple-tags/

Second link: https://taxopress.com/docs/
