### ISSUE TITLE
Design tweak for review banner

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#863]
<img width="1329" alt="Screen Shot 2021-09-14 at 3 45 49 PM" src="https://user-images.githubusercontent.com/3868028/133323821-aab2613d-bfcf-467a-980a-d4af662c21aa.png">

**Comment by htmgarcia** [comment]
Hold on this until we figure out https://github.com/publishpress/PublishPress-Blocks/issues/731

**Comment by htmgarcia** [comment]
@stevejburge starter proposal:
![Screen Shot 2021-09-15 at 14 06 55](https://user-images.githubusercontent.com/4999794/133494406-70035954-afbd-4741-bda1-f31dc183aec9.png)

**Comment by stevejburge** [comment]
Yes, that's more like it, thanks!

**Comment by htmgarcia** [comment]
@stevejburge update:
![Screen Shot 2021-09-15 at 14 47 11](https://user-images.githubusercontent.com/4999794/133499550-41b69ecf-c745-4d5e-8321-2c6ce00460b6.png)

**Comment by stevejburge** [comment]
Awesome, thanks

This can be a template for all the PublishPress plugins too
