### ISSUE TITLE
Cannot create a tag when using the words that sound the same but have difference in letters and meaning

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#886]
1. Select TaxoPress from Dasboard
2. Select AutoLinks from dropdown list
3. Click "Add New" button
4. Fill in the fields --> in "Tittle" field write the name of the selected post
5. Go to "Post Types --> select all checkboxes
6. Click "Add AutoLinks" button
7. Create a new post
8. In a post use several words that sound the same but have difference in letters and or meaning (for ex. word green can represent a color or a name like "Mr.Green")
9. Create many tags using this words 
Note:

Expected Results: when the same word is written with at least one difference such as one letter, two tags should be created

Actual results:  when it's needed to only link a word with a specific writing such as a upper-case letters, autolinks are created for every other word that is spelled the same no matter the difference in upper case or lower case (for example when it's needed to tag only a word "Green" which has a capital letter, the autolinks are still created for other "green")

![image](https://user-images.githubusercontent.com/87830117/133953338-06cbffc8-49e1-4acc-ba13-008533f7cb54.png)

**Comment by ojopaul** [comment]
@stevejburge @olatechpro. I didn't understand this issue very well. Based on my understanding, are you asking me to add control where 'green' is not same as 'GREEN' due to uppercase difference ?

**Comment by stevejburge** [comment]
@ojopaul Good question. Let's postpone this and I'll ask the reporter for more info

**Comment by ojopaul** [comment]
> @ojopaul Good question. Let's postpone this and I'll ask the reporter for more info

Okay
