### ISSUE TITLE
Not able to correct a tag after saving 

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#893]
1. Select TaxoPress from Dasboard
2. Select AutoLinks from dropdown list
3. Click "Add New" button
4. Fill in the fields --> in "Tittle" field write the name of the selected post
5. Go to "Post Types --> select all checkboxes
6. Click "Add AutoLinks" button
7. Create a new post
8. Create a tag (for example "CoMpAnY")
9. Delete the tag
10. Create a new tag using the same word (for example "company")
10. Note: the tag is saved under the previous name

Expected results: after deleting there is an ability to correct a tag
Actual results: if a tag needs a correction (for example "CoMpAnY" --> "company") after deleting and creating a new one, the tag is saved as the previous one.

![WordPress_snapshot3](https://user-images.githubusercontent.com/87830117/134106721-d4dab896-dd07-437f-bfed-d86332f78f5e.gif)

**Comment by stevejburge** [comment]
@mgrant00 Thanks. Sorry, this is normal WordPress behavior
