### ISSUE TITLE
Cannot create a tag for words with an apostrophe in a foreign language

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#897]
When creating a tag using a word with an apostrophe in a foreign language (in Ukrainian language some names and last names include an apostrophe for example "Лук'яненко") , the autolink is not created. While the autolinks can still be created with an apostrophe in English (for example " D’Artagnan").
![WordPress_snapshot6](https://user-images.githubusercontent.com/87830117/134280300-6db7cc6f-5d1e-4d0b-8293-3b4ad457fad9.gif)
![WordPress_snapshot7](https://user-images.githubusercontent.com/87830117/134280302-93569412-b529-4053-82a7-ef7dc0624d2b.gif)
![WordPress_snapshot8](https://user-images.githubusercontent.com/87830117/134280303-613016d5-9d62-4548-b58a-d5e6f7bb961b.gif)

**Comment by stevejburge** [comment]
@mgrant00 Thanks for reporting this. Sorry, this is default WordPress behavior
