### ISSUE TITLE
The warning message is absent when creating a tag using two or more lines of words

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#899]
There is no message or any sign to warn that the tag cannot be created with invalid input (for example: creating a tag using two lines of text at the same time) . The code line appears in the tag text field, and disappears when the post is viewed.
![WordPress_snapshot10](https://user-images.githubusercontent.com/87830117/134438500-6993f719-354e-4021-a4a0-64f0acf49a2f.gif)
![WordPress_snapshot11](https://user-images.githubusercontent.com/87830117/134438512-2f31c286-78cd-4617-842a-c228e81ccb5c.gif)

**Comment by stevejburge** [comment]
Hi @mgrant00. Sorry, this is default Wordpress, not a TaxoPress problem
