### ISSUE TITLE
When a big piece of text is used to create a tag the text inside the tag gets mixed up

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#901]
When trying to create a new tag using a big part of text, the tag is created but the text field is mixed up.
![WordPress_snapshot18 (2)](https://user-images.githubusercontent.com/87830117/134591159-d78f4d1e-1b2e-4661-a4a0-0bb09ca0ec75.gif)

**Comment by stevejburge** [comment]
@mgrant00 Can you explain this in more detail, please? Are you manually copy-pasting the text?

**Comment by mgrant00** [comment]
Steps to Reproduce:

1. Select TaxoPress from Dasboard
2. Select AutoLinks from dropdown list
3. Click "Add New" button
4. Fill in the fields --> in "Tittle" field write the name of the selected post
5. Go to "Post Types --> select all checkboxes
6. Click "Add AutoLinks" button
7. Create a new post
8. Type or insert a big chunk of text
9. Copy all the text
10. Paste it in the tag text field

Note: the tag is divided into smaller tags the order of which is mixed up

**Comment by stevejburge** [comment]
Sorry @mgrant00, many of the issues you are reporting at default WordPress. They are not related to TaxoPress
