### ISSUE TITLE
It takes more than one click to delete a tag that links a big piece of text

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#902]
When creating a tag to link more than one line of words, inside the text field the tag is divided into smaller tags that link pieces of the text. Which than cannot be deleted with only one click.
![WordPress_snapshot18](https://user-images.githubusercontent.com/87830117/134595733-22fda65f-6936-42d7-9f24-e26d000f2998.gif)

**Comment by stevejburge** [comment]
@mgrant00 Sorry, this is default WordPress, not TaxoPress
