### ISSUE TITLE
Impossible to create two tags with the same words 

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#903]
When creating two tags which include the same words (for example cute and cute baby), the link for the second tag is not created. While two tags that include the same words can be created, if there is a third tag that doesn't include the used word in between the two tags.

Steps To Reproduce:

1. Select TaxoPress from Dasboard
2. Select AutoLinks from dropdown list
3. Click "Add New" button
4. Fill in the fields --> in "Tittle" field write the name of the selected post
5. Go to "Post Types --> select all checkboxes
6. Click "Add AutoLinks" button
7. Create a new post
8. Type in the two sentences: "The baby seal is so cute", "It is a cute baby"
9. Create the tags for words "cute" and "cute baby"
10. Update the table

Note: only one link is created

11. Go back to the post
12. Delete the second tag ("cute baby")
13. Create the tag "seal"
14. Create the tag "cute baby" again
15. Update the post
16. Click "View Post" button

Note: the 3 tags are created.

![WordPress_snapshot_seal](https://user-images.githubusercontent.com/87830117/134746202-6628a283-8c05-416f-8e6a-dc45c9bff358.gif)

![WordPress_snapshot_seal2 ](https://user-images.githubusercontent.com/87830117/134746208-13705c57-2511-4045-945b-edcb1cb15ada.gif)

![WordPress_snapshot_seal 3](https://user-images.githubusercontent.com/87830117/134746228-cad08878-27fb-4d57-813a-e3d03442fc36.gif)

**Comment by stevejburge** [comment]
Good point @mgrant00. This could be a new setting - how to handle tags with multiple words
