### ISSUE TITLE
Add the option to run "Auto Terms" for different statuses

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#905]
Right now, you have to publish content for "Auto Terms" to work.

It could be helpful if Auto Terms ran when people clicked "Update", even in the post was in draft

**Comment by ojopaul** [comment]
@stevejburge , where should i put this option and should it be a single checkbox ?

**Comment by ojopaul** [comment]
@stevejburge @olatechpro , where should i put this option and should it be a single checkbox ?

**Comment by olatechpro** [comment]
@stevejburge @olatechpro  .....I'm still waiting for response on this

**Comment by olatechpro** [comment]
Do you think we should include all post status as drop down or a simple checkbox to support draft alone in additional to publish post status?

If we're going for drop down of post status, that means it's going to be multiple selection type so they can combine post status. 

Will still wait for but wait for 
@stevejburge input first

**Comment by stevejburge** [comment]
@ojopaul Good question. Maybe this could be a simple checkbox: "Use "Auto Terms" for unpublished content"

It can be disabled by default

**Comment by ojopaul** [comment]
> @ojopaul Good question. Maybe this could be a simple checkbox: "Use "Auto Terms" for unpublished content"
> 
> It can be disabled by default

Okay, just for clarification, when unpublished content is selected, will this apply to draft status and publish status alone or the term unpublish means other status inclusive ?

**Comment by stevejburge** [comment]
Good questions again? 

Maybe we start with two checkboxes?

Left: Content statuses
Right: Add terms for published content.  (checked by default)
Right: Add terms for unpublished content. (unchecked by default)
