### ISSUE TITLE
The text is deformed when trying to create an autolink while the text is already linked from another site

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#908]
When inserting the content from the different site (for example Wikipedia) which already has some links and trying to create autolinks with another words the text is deformed. While, if the links from the pasted text are removed, and the new tags are added, the text is not deformed.

1. Select TaxoPress from Dasboard
2. Select AutoLinks from dropdown list
3. Click "Add New" button
4. Fill in the fields --> in "Tittle" field write the name of the selected post
5. Go to "Post Types --> select all checkboxes
6. Click "Add AutoLinks" button
7. Create a new post
8. Copy any text that includes a linked word from a website
9. Paste it in the new post
10. Create a tag for any word that is not linked 
11. Update the table

Note: the text is deformed and only shows some parts of it

1. Remove the links copied from the website
2. Create a new tag 
3. Update the table
4. Click "View Post" button

Note: the autolinks are create, the text is not deformed

![WordPress_snapshot20](https://user-images.githubusercontent.com/87830117/134994490-1b8a4c20-070d-4013-99ce-12615de14055.gif)

![WordPress_snapshot21](https://user-images.githubusercontent.com/87830117/134994504-36c3f07f-e9e7-44db-a029-234455aa4722.gif)

**Comment by stevejburge** [comment]
@olatechpro Should we allow some kind of priority with Auto Links compared to other links?

**Comment by olatechpro** [comment]
@stevejburge , can you provide me with sample text with this issue ?

I copied text from here( https://en.wikipedia.org/wiki/Ad_hoc_testing ) and then added 'commonly' and 'documentation ' tags but nothing happen
