### ISSUE TITLE
Cannot create a linked image tag

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#909]
When pasting the copied image to insert in the tag text field, nothing happens.

![WordPress_snapshot22](https://user-images.githubusercontent.com/87830117/134995885-aa28eab7-7ebc-494b-8465-351afbc14b78.gif)

**Comment by stevejburge** [comment]
@mgrant00 Sorry, this is normal WordPress behavior. It's not TaxoPress
