### ISSUE TITLE
cannot separate autolinks with integer from decimal

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#911]
When creating a tag with an integer, the automatic link captures it even if the number is part of a decimal.

![WordPress_snapshot23](https://user-images.githubusercontent.com/87830117/135137190-5909f4d9-908a-4320-8a22-e96ffa49bb94.gif)

**Comment by ojopaul** [comment]
Does that mean autolinks should only link whole word ? I'm confirming this since i didn't know how it works before @stevejburge @olatechpro

**Comment by stevejburge** [comment]
@ojopaul Let's postpone this one too. It probably needs a bigger rethink of how we handle AutoLinks
