### ISSUE TITLE
Cannot insert the video link above the text 

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#913]
When pasting a link for any video (for example from YouTube or other source) above all of the text (without using the insert video option) the whole video appears instead. While, when inserting the same link somewhere at the end of the text or when starting a new paragraph, only the link appears.

![WordPress_snapshot31](https://user-images.githubusercontent.com/87830117/135364304-51c0aa29-fe8b-4c37-a2f3-0b62b25b45ab.gif)

**Comment by stevejburge** [comment]
sorry @mgrant00 

Please make sure you are reporting TaxoPress issues
