### ISSUE TITLE
Allow Auto-Terms to work with imported posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#918]
We have a customer who imports posts by RSS. They use the Echo RSS and Newsomatic RSS plugins

Can we add setting to control how Auto Terms are added in this situation? It could be a pro feature.

**Comment by stevejburge** [comment]
This may be one approach: https://github.com/TaxoPress/TaxoPress/issues/440

**Comment by stevejburge** [comment]
One more import request:

> I'm working on cosmetics price and reviews comparison web-app and interested in your plugin and in my woocommerce store products import through octoparse mysql database so, auto tagging is work or not.

**Comment by ojopaul** [comment]
@stevejburge , can you link me to this plugin so i can check how to support post imported using the plugin ?

**Comment by stevejburge** [comment]
@ojopaul Researching this, I think this can be solved with https://github.com/TaxoPress/TaxoPress/issues/440
