### ISSUE TITLE
Cannot create autolink using superscript and subscript

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#919]
If copy the characters with superscripts and subscripts  from the post (for example math or chemical formulas), and then paste them into the tag text field, the link is not created.

![WordPress_snapshot35](https://user-images.githubusercontent.com/87830117/135661133-bddffd87-525a-4a64-8241-9fba176fb7a9.gif)

**Comment by stevejburge** [comment]
@mgrant00 sorry, again this is not taxopress
