### ISSUE TITLE
The data is successfully saved when the amount of characters is higher than 32 in "Stop Words" text field on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#922]
When inserting the value that is more 32 characters in the "Stop Words" text field on the "Manage Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms
Click "Add New" --> General
Fill in "Title" text field
Go to "Terms to Use" --> type in more than 32 characters in the "Stop Words" text field
Click "Add Auto Terms" button
Note: the message "Settings updated successfully." appears

![WordPress_snapshot41](https://user-images.githubusercontent.com/87830117/135893952-850e5b3f-ccc6-43b0-9590-62e623d7b737.gif)

**Comment by stevejburge** [comment]
@ojopaul The maximum length of a taxonomy term is 32 so anything longer won't work. But again - it's a minor issue we can ignore

**Comment by ojopaul** [comment]
> @ojopaul The maximum length of a taxonomy term is 32 so anything longer won't work. But again - it's a minor issue we can ignore

I'm i missing something on this feature ? The field is stop words and not taxonomy which i believe give user options to enter words excluded from terms ? If so, what's it relationship with taxonomy terms length ?

Maybe if you explain better, will know what needed to be done there or you simply mean all fields in the settings should be maximum of 32 length irrespective of expected value ? @stevejburge

**Comment by stevejburge** [comment]
We can ignore this one as a minor.

Essentially "Auto Terms" is pulling from the terms table, so any entry longer than 32 won't work
