### ISSUE TITLE
Absence of  some "Post Type"

### ISSUE THREAD

**Issue by archi673** [TaxoPress/TaxoPress#923]
When I want to change "Post Type" on "Downloads" or "Products" in taxonomy created by default or just created, I can't do it because of missing these two "Post Types". There is no "Post Types' such as "Downloads" and "Products", but they are shown in instruction
![My PC](https://user-images.githubusercontent.com/86455618/135954759-dbe5435e-4ba4-451f-ab19-47c30d44908c.png)
![Instruction](https://user-images.githubusercontent.com/86455618/135954860-cb58ad3f-be9d-42a8-8f7f-5eb1ff880f75.png)

**Comment by stevejburge** [comment]
@archi673 you will need to install plugins to see "Downloads" and "Products"
