### ISSUE TITLE
No "Rewrite" option for the "Category" and "Tag" taxonomies

### ISSUE THREAD

**Issue by archi673** [TaxoPress/TaxoPress#924]
When I'm choosing the "Permalink" menu for the "Category" and "Tag" taxonomies there is no "Rewrite" option as shown in the instruction. 
![Instruction](https://user-images.githubusercontent.com/86455618/135956444-1e29791f-0a7d-4c41-bd67-c6b9a6a5aa73.png)
![My PC](https://user-images.githubusercontent.com/86455618/135956446-c008c7ab-e70c-4914-8fc1-dd071966a5d7.png)

**Comment by stevejburge** [comment]
Thanks. It isn't possible to change the slug for core taxonomies
