### ISSUE TITLE
Ability to save the changes when the "Stop Words" text field is empty on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#927]
There is no warning or error message such as "Please complete the following required fields to save your changes:" when creating an Auto Term and leaving the "Stop Words" text field empty.

TaxoPress --> Auto Terms
Click "Add New" --> General
Fill in "Title" text field
Go to "Terms to Use" --> leave the "Stop Words" text field empty
Click "Add Auto Terms" button
Note: no error message shown, the changes are saved successfully 

![WordPress_snapshot43](https://user-images.githubusercontent.com/87830117/135934121-11602c3f-e0e4-4ee7-85a9-324100e9aae1.gif)

**Comment by stevejburge** [comment]
@olatechpro Stop words seems to be marked as required, but is not
<img width="407" alt="Screen Shot 2021-10-05 at 2 03 49 PM" src="https://user-images.githubusercontent.com/3868028/136078225-6d142930-f428-47c3-bdb8-49bd72a91e16.png">
