### ISSUE TITLE
Use "Counter" and "Descending" as the defaults

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#942]
![Screen Shot 2021-10-11 at 10 32 53 AM](https://user-images.githubusercontent.com/3868028/136808294-6a169e6d-58b2-4bb9-bd85-ce38920677d1.png)

**Comment by stevejburge** [comment]
100% brand-new install

**Comment by olatechpro** [comment]
Okay, I think I see what you're talking about. The issue is with the suggested  term created on installation.

Will fix that
