### ISSUE TITLE
Adding Categories isn't working

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#949]
The Categories are showing as added, but they are not actually added. The same is true for other taxonomies. Only Tags works.

![Screen Shot 2021-10-11 at 10 51 23 AM](https://user-images.githubusercontent.com/3868028/136811172-0e1d2a7e-a447-439a-8632-725f137dc998.png)

**Comment by olatechpro** [comment]
Click tags was created for tags like taxonomy and not category likes. That's the reason it won't work with category likes type taxonomy.

But since we're enabling support for them, will have to see how to go about it if it's possible and how.
