### ISSUE TITLE
Ability to save data when the entered value starts with a space in "Stop words" text field on "Manage Auto Terms" page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#960]
When inserting the value that starts with a space in the "Stop words" text field on the "Manage Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms
Edit any Auto Terms --> Terms to Use
Type in several spaces in the "Stop words" text field
Click "Save Auto Terms" button
Note: the message "Settings updated successfully" appears

![WordPress_snapshot51](https://user-images.githubusercontent.com/87830117/136999349-7a3c33f2-9a64-47a7-aace-8888d61967a8.gif)

**Comment by ojopaul** [comment]
Same as previous one, user has total control and will on value entered on the field and so far it's a valid text number or characters. @stevejburge @olatechpro
