### ISSUE TITLE
Hi, I find this error after publish

### ISSUE THREAD

**Issue by JoaoLamares** [TaxoPress/taxopress#97]
Hi, I find this error after publish one post. and wen I look the home page I find it in another post. Can you help? 

Warning: DOMDocument::loadHTML(): ID sfsiplusid_google already defined in Entity, line: 1 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): ID sfsiplusid_youtube already defined in Entity, line: 1 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): Tag figure invalid in Entity, line: 1 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): Tag figcaption invalid in Entity, line: 2 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): ID sfsiplusid_google already defined in Entity, line: 8 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

Warning: DOMDocument::loadHTML(): ID sfsiplusid_youtube already defined in Entity, line: 13 in /home/joaolama/jlpress.com/wp-content/plugins/simple-tags/inc/class.client.autolinks.php on line 204

You can see it at https://jlpress.com
Thnaks

**Comment by herewithme** [comment]
Hey @JoaoLamares 

On this settings page :
YOURSITE.com/wp-admin/options-general.php?page=st_options

Uncheck this "Try new engine replacement ?"
