### ISSUE TITLE
New "Suggest Terms" label

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#972]
"This feature helps when you're writing content. "Suggest Terms" can show a metabox where you can browse all your existing terms. "Suggest Terms" can also analyze your content and find new ideas for terms."

<img width="828" alt="Screen Shot 2021-10-13 at 11 09 54 AM" src="https://user-images.githubusercontent.com/3868028/137161602-ec9d7b39-1319-4d26-9774-49ce674d2c91.png">

**Comment by olatechpro** [comment]
@stevejburge, the screenshot you shared is showing Existing terms menu and there by confusing me whether you're refering to 'suggest terms' menu just like you did for 'show existing terms' menu in #970 or you mean main screen as in the screenshot below:
![st](https://user-images.githubusercontent.com/46832636/137722368-b3539705-3e59-49d7-aa2c-d89e3146a2d0.jpg)
