### ISSUE TITLE
Search box doesn't show any results when the space is entered before the value at the Auto Terms page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#993]
When inserting a name of the existing Auto term with a space  before the value, the message "No item available" appears.

TaxoPress --> Auto Terms
Click on Search box --> type in the existing Auto term name with a space at the beginning
Click "Search Auto Terms" button
Note: The message "No item available" appears

![WordPress_snapshot64](https://user-images.githubusercontent.com/87830117/137754586-27226723-0e67-4ba1-9c52-a0e31f9b4bfd.gif)

**Comment by ojopaul** [comment]
@stevejburge this shouldn't be an issue since no keyword was entered for the search ?

**Comment by stevejburge** [comment]
@ojopaul This is also a minor issue. We can move
