### ISSUE TITLE
Search box doesn't show any results when the space is entered after the value at the Auto Terms page

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#994]
When inserting a name of the existing Auto term with a space at the end, the message "No item available" appears.

TaxoPress --> Auto Terms
Click on Search box --> type in the existing Auto term name with a space at the end
Click "Search Auto Terms" button
Note: The message "No item available" appears

![WordPress_snapshot63](https://user-images.githubusercontent.com/87830117/137754112-a8ba6a26-0908-4908-8242-7eb85f76351e.gif)

**Comment by ojopaul** [comment]
@stevejburge this shouldn't be an issue as since input text will determine results ?

**Comment by stevejburge** [comment]
@ojopaul I guess this is a minor bug that may confuse one or two people. We can leave it
