### ISSUE TITLE
The data is successfully saved when the entered value starts with 0 in "Number of items per page" drop-down list box on "Auto Terms" page 

### ISSUE THREAD

**Issue by mgrant00** [TaxoPress/TaxoPress#999]
When inserting the value that starts with 0 in the "Number of items per page" drop-down list on the "Auto Terms" page, the data is successfully saved.

TaxoPress --> Auto Terms --> Screen Options
Type in "001" in the "Number of items per page" drop-down list
Click "Apply" button
Note: the data updated successfully

![WordPress_snapshot67](https://user-images.githubusercontent.com/87830117/137932043-1c8645c1-c3e3-439f-8b19-3c602a0c7896.gif)

**Comment by ojopaul** [comment]
I just tested this and that doesn't been the case. Can you confirm this ? @stevejburge @olatechpro
